// lib/engine/packs/autofficina.js
//
// Sector Pack "autofficina" v1 — conoscenza di SETTORE (officina meccanica
// auto, Italia), non di una singola officina. Prezzi, orari, servizi offerti,
// marchi trattati, promozioni, personale e indirizzo non stanno qui: arrivano
// solo dai dati del tenant. Il motore è identico agli altri settori: questo
// file è solo dati (lessico, intent, entità, regole di urgenza e sicurezza,
// FAQ generali).

export const SETTORE = 'autofficina';
export const VERSIONE = 1;
export const CHANGELOG = 'v1: primo Sector Pack autofficina — lessico di officina (tagliando, revisione, freni, frizione, distribuzione, spie, diagnosi, clima, gomme, marche/modelli/anni/alimentazione), 20 intent, 14 entità, urgenze LOW-CRITICAL (freni, sterzo, fumo/fiamme, carburante/gas, spie olio/temperatura, perdite, incidente), sicurezza anti-diagnosi/anti fai-da-te/anti stime, 27 FAQ di settore.';

// ---------------------------------------------------------------------------
// Dati ripetitivi del lessico (marche, modelli, anni) generati da tabelle.
// ---------------------------------------------------------------------------
const MARCHE = [
  ['fiat', ['fiat']],
  ['lancia', ['lancia']],
  ['alfa_romeo', ['alfa romeo', 'alfa', 'alfaromeo']],
  ['ford', ['ford']],
  ['volkswagen', ['volkswagen', 'vw', 'wolksvagen', 'volskwagen', 'wolkswagen']],
  ['audi', ['audi']],
  ['bmw', ['bmw', 'bmv']],
  ['mercedes', ['mercedes', 'mercedez', 'merceds', 'mercedes benz']],
  ['opel', ['opel']],
  ['peugeot', ['peugeot', 'pegeot', 'peugeout', 'peugot']],
  ['citroen', ['citroen']],
  ['renault', ['renault']],
  ['dacia', ['dacia']],
  ['toyota', ['toyota']],
  ['nissan', ['nissan']],
  ['honda', ['honda']],
  ['mazda', ['mazda']],
  ['hyundai', ['hyundai', 'hiunday']],
  ['kia', ['kia']],
  ['suzuki', ['suzuki']],
  ['skoda', ['skoda']],
  ['seat', ['seat']],
  ['cupra', ['cupra']],
  ['volvo', ['volvo']],
  ['jeep', ['jeep']],
  ['mini', ['mini cooper', 'mini countryman', 'la mia mini']],
  ['smart', ['smart fortwo', 'smart forfour', 'la mia smart']],
  ['tesla', ['tesla']],
  ['land_rover', ['land rover', 'range rover']],
  ['mitsubishi', ['mitsubishi']],
  ['porsche', ['porsche']],
  ['maserati', ['maserati']],
  ['lexus', ['lexus']],
  ['subaru', ['subaru']],
  ['chevrolet', ['chevrolet']],
];

// Modelli frequenti sul parco circolante italiano. Le forme ambigue con
// parole comuni ("punto", "tipo", "corsa", "polo") richiedono la marca.
// [valore, forme, marca implicita]
const MODELLI = [
  ['panda', ['panda'], 'fiat'],
  ['500', ['fiat 500', 'cinquecento', '500x', '500l', 'la mia 500'], 'fiat'],
  ['punto', ['fiat punto', 'grande punto'], 'fiat'],
  ['tipo', ['fiat tipo'], 'fiat'],
  ['ypsilon', ['ypsilon'], 'lancia'],
  ['doblo', ['doblo'], 'fiat'],
  ['ducato', ['ducato'], 'fiat'],
  ['fiorino', ['fiorino'], 'fiat'],
  ['golf', ['golf'], 'volkswagen'],
  ['polo', ['vw polo', 'volkswagen polo'], 'volkswagen'],
  ['tiguan', ['tiguan'], 'volkswagen'],
  ['clio', ['clio'], 'renault'],
  ['captur', ['captur'], 'renault'],
  ['megane', ['megane'], 'renault'],
  ['twingo', ['twingo'], 'renault'],
  ['sandero', ['sandero'], 'dacia'],
  ['duster', ['duster'], 'dacia'],
  ['yaris', ['yaris'], 'toyota'],
  ['qashqai', ['qashqai'], 'nissan'],
  ['juke', ['juke'], 'nissan'],
  ['focus', ['ford focus'], 'ford'],
  ['fiesta', ['fiesta'], 'ford'],
  ['kuga', ['kuga'], 'ford'],
  ['astra', ['astra'], 'opel'],
  ['corsa', ['opel corsa'], 'opel'],
  ['mokka', ['mokka'], 'opel'],
  ['208', ['peugeot 208', 'la mia 208'], 'peugeot'],
  ['308', ['peugeot 308', 'la mia 308'], 'peugeot'],
  ['berlingo', ['berlingo'], 'citroen'],
  ['a3', ['audi a3'], 'audi'],
  ['a4', ['audi a4'], 'audi'],
  ['serie_1', ['bmw serie 1', 'serie 1'], 'bmw'],
  ['serie_3', ['bmw serie 3', 'serie 3'], 'bmw'],
  ['giulietta', ['giulietta'], 'alfa_romeo'],
  ['stelvio', ['stelvio'], 'alfa_romeo'],
  ['renegade', ['renegade'], 'jeep'],
  ['compass', ['jeep compass'], 'jeep'],
  ['picanto', ['picanto'], 'kia'],
  ['sportage', ['sportage'], 'kia'],
  ['swift', ['suzuki swift'], 'suzuki'],
  ['vitara', ['vitara'], 'suzuki'],
  ['octavia', ['octavia'], 'skoda'],
  ['ibiza', ['ibiza'], 'seat'],
];

const ANNI = Array.from({ length: 32 }, (_, i) => 1995 + i);

export const pack = {
  identity: {
    settore: 'autofficina',
    nome_ruolo: 'officina meccanica',
    entita_nome: 'nome_cliente',
    descrizione: 'Sei l\'assistente digitale di un\'officina meccanica per auto. Accogli i clienti con tono cortese, concreto e diretto; gestisci richieste di appuntamento (tagliando, revisione, riparazioni), preventivi, informazioni e urgenze. Non sei un meccanico: non fai diagnosi del guasto a distanza, non indichi costi né tempi di lavorazione, non dai istruzioni di riparazione fai-da-te.',
  },
  mission: 'Capire cosa serve al cliente e alla sua auto, raccogliere solo le informazioni necessarie (nome, tipo di intervento o problema, marca e modello), organizzare l\'appuntamento e far arrivare subito all\'officina le situazioni di pericolo.',
  tone_default: 'professionale',
  conversation_rules: [
    'Messaggi brevi (2-3 frasi), linguaggio semplice e concreto, senza tecnicismi inutili.',
    'Se il cliente descrive freni che non rispondono o pedale a vuoto, sterzo bloccato, fumo o fiamme dal cofano, odore di benzina o di gas, spia dell\'olio o della temperatura accesa, perdite di liquidi, odore di bruciato o un incidente: la prima frase invita a NON guidare e ad accostare in sicurezza se è in marcia; se c\'è pericolo per le persone invita a chiamare il 112 o il soccorso stradale. Solo dopo si raccolgono i dati per l\'officina.',
    'Una sola domanda per messaggio e mai su un\'informazione già data (nome, marca, modello, problema).',
    'Mai diagnosi del guasto a distanza ("è la frizione", "sarà la batteria", "non è niente"): la causa la stabilisce il meccanico dopo aver controllato l\'auto.',
    'Mai dire se si può continuare a guidare con una spia accesa o un sintomo: serve il meccanico; nel dubbio si consiglia di non guidare.',
    'Mai istruzioni di riparazione o manutenzione fai-da-te (smontare, staccare la batteria, azzerare le spie, rabboccare o cambiare liquidi e pezzi).',
    'Mai stime di costo né di tempi di lavorazione o di consegna: li comunica solo l\'officina, sulla base dei suoi dati.',
    'Per lo stato di un\'auto già in officina non inventare nulla: passa la richiesta allo staff.',
  ],
  prohibited_claims: [
    'dire al cliente cosa ha l\'auto o quale pezzo è rotto',
    'dire che si può continuare a guidare o che un sintomo non è grave',
    'dare istruzioni di riparazione o manutenzione fai-da-te',
    'indicare costi, sconti, tempi di lavorazione, orari o disponibilità non presenti nelle fonti',
    'dire quali marche, servizi o ricambi l\'officina tratta se non è nei dati dell\'officina',
    'garantire esiti, risultati o l\'assenza di guasti',
  ],
  business_rules: [
    'Annullamenti e spostamenti di appuntamenti esistenti vanno passati allo staff.',
    'Le richieste sullo stato di un\'auto in officina ("è pronta?") vanno passate allo staff: il sistema non conosce lo stato dei lavori.',
    'Le situazioni di pericolo (freni, sterzo, fumo, carburante, spie rosse, incidente) hanno priorità sulla raccolta dati normale.',
  ],

  entities: [
    { id: 'servizio', descrizione: 'Il tipo di intervento o lavoro richiesto.', tipo: 'enum', priorita: 10,
      valori: ['tagliando', 'revisione', 'pre_revisione', 'cambio_olio', 'filtri', 'freni', 'frizione', 'distribuzione', 'batteria', 'candele', 'diagnosi', 'climatizzatore', 'gomme', 'assetto', 'scarico', 'ammortizzatori', 'impianto_elettrico', 'luci', 'carrozzeria', 'controllo_generale', 'altro'],
      domanda_varianti: ['Di che intervento ha bisogno: un tagliando, la revisione, o altro?', 'Mi dice che lavoro vorrebbe fare sull\'auto?', 'Per cosa vorrebbe portare l\'auto?'] },
    { id: 'nome_cliente', descrizione: 'Nome del cliente.', tipo: 'string', priorita: 20,
      domanda_varianti: ['Come si chiama?', 'Mi dice il suo nome, così preparo la richiesta?', 'A che nome registro la richiesta?'] },
    { id: 'sintomo', descrizione: 'Il problema, rumore, spia o sintomo che il cliente descrive sull\'auto.', tipo: 'string', priorita: 15,
      domanda_varianti: ['Mi racconta che problema sta avendo con l\'auto?', 'Che cosa succede, esattamente? Un rumore, una spia, altro?', 'Può descrivermi brevemente il problema?'] },
    { id: 'marca', descrizione: 'Marca dell\'auto.', tipo: 'string', priorita: 30,
      domanda_varianti: ['Che auto ha? Mi dice marca e modello?', 'Di che marca e modello è l\'auto?'] },
    { id: 'modello', descrizione: 'Modello dell\'auto.', tipo: 'string', priorita: 32,
      domanda_varianti: ['Che modello è?'] },
    { id: 'anno', descrizione: 'Anno di immatricolazione dell\'auto.', tipo: 'string', priorita: 34 },
    { id: 'alimentazione', descrizione: 'Alimentazione: diesel, benzina, gpl, metano, ibrida, elettrica.', tipo: 'enum', priorita: 36, valori: ['diesel', 'benzina', 'gpl', 'metano', 'ibrida', 'elettrica'] },
    { id: 'targa', descrizione: 'Targa dell\'auto (se il cliente la fornisce).', tipo: 'string', priorita: 38,
      domanda_varianti: ['Mi può dare la targa dell\'auto?'] },
    { id: 'chilometri', descrizione: 'Chilometri percorsi dall\'auto.', tipo: 'string', priorita: 40,
      domanda_varianti: ['Più o meno quanti chilometri ha l\'auto?'] },
    { id: 'giorno', descrizione: 'Giorno preferito per portare l\'auto.', tipo: 'string', priorita: 60 },
    { id: 'fascia_oraria', descrizione: 'Mattina, pomeriggio o sera.', tipo: 'enum', priorita: 61, valori: ['mattina', 'pomeriggio', 'sera'] },
    { id: 'cliente_nuovo', descrizione: 'Se è la prima volta che il cliente porta l\'auto in questa officina.', tipo: 'enum', priorita: 50, valori: ['si', 'no'] },
    { id: 'auto_sostitutiva', descrizione: 'Se il cliente chiede un\'auto sostitutiva o di cortesia.', tipo: 'enum', priorita: 70, valori: ['richiesta'] },
    { id: 'telefono', descrizione: 'Numero di telefono se il cliente lo fornisce (di norma già noto da WhatsApp).', tipo: 'string', priorita: 99 },
  ],

  lexicon: [
    // ---- Servizi (l'ordine conta: a parità di entità vince la prima voce trovata) ----
    { canonical: 'pre_revisione', entity: 'servizio', value: 'pre_revisione', synonyms: ['pre revisione', 'prerevisione', 'controllo pre revisione', 'controllo prima della revisione', 'controllo per la revisione', 'preparare per la revisione', 'preparare l auto per la revisione', 'prepararla per la revisione', 'prepararla alla revisione', 'preparazione revisione'], errors: ['prerevisone'] },
    { canonical: 'revisione', entity: 'servizio', value: 'revisione', synonyms: ['revisione', 'revisioni', 'revisione periodica', 'revisione auto', 'revisione ministeriale', 'revisionare', 'collaudo', 'bollino della revisione', 'revisione scaduta', 'revisione in scadenza'], slang: ['rivisione', 'fare la revisione'], errors: ['revisone', 'revisioen', 'rivisione', 'revizione'] },
    { canonical: 'tagliando', entity: 'servizio', value: 'tagliando', synonyms: ['tagliando', 'tagliandi', 'tagliando completo', 'tagliando auto', 'manutenzione ordinaria', 'manutenzione programmata', 'manutenzione periodica', 'controllo periodico', 'spia del tagliando', 'spia tagliando', 'spia service', 'scadenza tagliando', 'tagliando in scadenza', 'service'], slang: ['fare il service', 'fare la manutenzione', 'manutenzione'], errors: ['taglindo', 'tagliadno', 'tagiando', 'tagliano', 'tagliand', 'tagliandp'] },
    { canonical: 'cambio_olio', entity: 'servizio', value: 'cambio_olio', synonyms: ['cambio olio', 'cambio dell olio', 'cambiare l olio', 'cambiare olio', 'sostituzione olio', 'sostituire l olio', 'olio e filtri', 'cambio olio e filtri', 'cambio olio motore', 'rabbocco olio', 'rabboccare l olio', 'cambiare olio e filtri'], slang: ['fare l olio', 'fare olio', 'cambio oilo'], errors: ['cambio olo', 'camio olio', 'cambo olio'] },
    { canonical: 'filtri', entity: 'servizio', value: 'filtri', synonyms: ['filtro', 'filtri', 'filtro aria', 'filtro dell aria', 'filtro abitacolo', 'filtro antipolline', 'filtro carburante', 'filtro gasolio', 'filtro olio', 'filtri aria'], errors: ['filtri aira'] },
    { canonical: 'freni', entity: 'servizio', value: 'freni', synonyms: ['freni', 'freno', 'pastiglie', 'pastiglie freno', 'pastiglie dei freni', 'dischi', 'dischi freno', 'dischi dei freni', 'ganasce', 'liquido freni', 'liquido dei freni', 'impianto frenante', 'cambio pastiglie', 'pinze freno'], slang: ['pasticche', 'pastiglie davanti', 'pastiglie dietro'], errors: ['frenii', 'pastiglei', 'pastilie', 'pastiglie fremi'] },
    { canonical: 'frizione', entity: 'servizio', value: 'frizione', synonyms: ['frizione', 'cambio frizione', 'kit frizione', 'disco frizione', 'volano', 'volano bimassa', 'cambiare la frizione'], errors: ['frizzione', 'frizone', 'frizzione'] },
    { canonical: 'distribuzione', entity: 'servizio', value: 'distribuzione', synonyms: ['cinghia di distribuzione', 'cinghia distribuzione', 'distribuzione', 'catena di distribuzione', 'catena distribuzione', 'kit distribuzione', 'cinghia dentata', 'cinghia servizi', 'cinghia', 'pompa dell acqua', 'pompa acqua'], abbreviations: ['cinghia distr'], errors: ['distribuzoine', 'distrbuzione', 'cinghia di distribuzoine'] },
    { canonical: 'batteria', entity: 'servizio', value: 'batteria', synonyms: ['batteria', 'batterie', 'cambio batteria', 'sostituzione batteria', 'sostituire la batteria', 'accumulatore', 'batteria dell auto'], errors: ['bateria', 'battria', 'batteira'] },
    { canonical: 'candele', entity: 'servizio', value: 'candele', synonyms: ['candele', 'candela', 'candelette', 'cambio candele', 'bobina', 'bobine', 'cambiare le candele'], errors: ['candelle', 'candle'] },
    { canonical: 'diagnosi', entity: 'servizio', value: 'diagnosi', synonyms: ['diagnosi', 'diagnostica', 'diagnosi computerizzata', 'diagnosi elettronica', 'centralina', 'lettura centralina', 'lettura errori', 'leggere gli errori', 'leggere la centralina', 'errori centralina', 'presa obd', 'collegare il computer', 'collegare lo scanner', 'passare al computer', 'passare la macchina al computer', 'scanner'], slang: ['passarla al computer', 'passarla al pc', 'controllo col computer'], errors: ['diagnosi elettronca', 'diagnosti', 'diagnoisi'] },
    { canonical: 'climatizzatore', entity: 'servizio', value: 'climatizzatore', synonyms: ['clima', 'aria condizionata', 'climatizzatore', 'condizionatore', 'ricarica clima', 'ricarica del clima', 'ricarica aria condizionata', 'ricarica gas clima', 'ricaricare il clima', 'sanificazione clima', 'sanificazione abitacolo', 'igienizzazione clima', 'compressore clima', 'compressore del clima'], slang: ['aria condizonata', 'ricarica aria'], errors: ['climatizzatoe', 'aria condizionnata', 'aria condizonata'] },
    { canonical: 'gomme', entity: 'servizio', value: 'gomme', synonyms: ['gomme', 'gomma', 'pneumatici', 'pneumatico', 'cambio gomme', 'cambio gomma', 'gomme invernali', 'gomme estive', 'gomme termiche', 'cambio stagionale', 'equilibratura', 'equilibrare', 'bilanciatura', 'convergenza', 'gommista', 'montaggio gomme'], slang: ['le ruote', 'ruote'], errors: ['pneumatci', 'pneumatichi', 'equilibratua', 'convergneza', 'convergenzza'] },
    { canonical: 'assetto', entity: 'servizio', value: 'assetto', synonyms: ['assetto', 'assetto ruote', 'campanatura', 'allineamento ruote', 'allineamento', 'geometria ruote', 'convergenza ruote'], errors: ['assettto'] },
    { canonical: 'impianto_di_scarico', entity: 'servizio', value: 'scarico', synonyms: ['marmitta', 'marmitte', 'silenziatore', 'tubo di scarico', 'catalizzatore', 'terminale di scarico', 'impianto di scarico', 'sonda lambda'], errors: ['marmita', 'marmitta rota'] },
    { canonical: 'ammortizzatori', entity: 'servizio', value: 'ammortizzatori', synonyms: ['ammortizzatori', 'ammortizzatore', 'sospensioni', 'sospensione', 'molle', 'balestre', 'tamponi'], errors: ['ammortizatori', 'amortizzatori', 'ammortizzatroi'] },
    { canonical: 'impianto_elettrico', entity: 'servizio', value: 'impianto_elettrico', synonyms: ['impianto elettrico', 'alternatore', 'motorino di avviamento', 'motorino avviamento', 'motorino d avviamento', 'fusibile', 'fusibili', 'cablaggio'], errors: ['alternatoe'] },
    { canonical: 'luci', entity: 'servizio', value: 'luci', synonyms: ['lampadina', 'lampadine', 'faro', 'fari', 'fanale', 'fanali', 'luci', 'luce di stop', 'frecce', 'freccia', 'faro fulminato'], errors: ['lampadne'] },
    { canonical: 'carrozzeria', entity: 'servizio', value: 'carrozzeria', synonyms: ['carrozzeria', 'carrozziere', 'ammaccatura', 'ammaccature', 'paraurti', 'graffio', 'graffi', 'verniciatura', 'lattoneria', 'raddrizzatura'], errors: ['carozzeria', 'carrozzria'] },
    { canonical: 'controllo_generale', entity: 'servizio', value: 'controllo_generale', synonyms: ['controllo generale', 'controllo completo', 'controllo dell auto', 'controllo della macchina', 'far controllare l auto', 'far controllare la macchina', 'controllata alla macchina', 'controllata all auto', 'check up', 'checkup', 'dare un occhiata alla macchina', 'dare un occhiata all auto', 'controllo prima di partire', 'controllo prima delle vacanze', 'controllo per le vacanze', 'controllo per il viaggio', 'controllo auto'], errors: ['controlo generale'] },

    // ---- Auto sostitutiva / tipo cliente ----
    { canonical: 'auto_sostitutiva', entity: 'auto_sostitutiva', value: 'richiesta', synonyms: ['auto sostitutiva', 'macchina sostitutiva', 'vettura sostitutiva', 'auto di cortesia', 'macchina di cortesia', 'vettura di cortesia', 'auto in prestito', 'macchina in prestito', 'auto muletto', 'muletto', 'macchina a noleggio', 'auto a noleggio', 'auto di scorta', 'una macchina per i giorni'], intent: 'info_auto_sostitutiva', errors: ['auto sostitutia', 'auto sostituiva'] },
    { canonical: 'cliente_nuovo', entity: 'cliente_nuovo', value: 'si', synonyms: ['sono nuovo', 'sono nuova', 'prima volta che vengo', 'non sono mai venuto', 'non sono mai venuta', 'non sono mai stato da voi', 'non sono mai stata da voi', 'non vi conosco', 'sono un nuovo cliente', 'sono una nuova cliente', 'e la prima volta', 'prima volta da voi', 'prima volta in questa officina', 'prima volta che porto l auto'] },
    { canonical: 'cliente_esistente', entity: 'cliente_nuovo', value: 'no', synonyms: ['sono gia cliente', 'sono gia venuto', 'sono gia venuta', 'sono gia stato da voi', 'sono gia stata da voi', 'sono un vostro cliente', 'sono una vostra cliente', 'sono vostro cliente', 'vengo da voi da anni', 'sono cliente da anni', 'sono gia stato in officina da voi'] },

    // ---- Alimentazione (forme prudenti: "benzina"/"gasolio" da soli compaiono in "odore di benzina") ----
    { canonical: 'diesel', entity: 'alimentazione', value: 'diesel', synonyms: ['diesel', 'turbodiesel', 'a gasolio', 'e a gasolio', 'motore diesel', 'versione diesel', 'e un diesel', 'tdi', 'hdi', 'jtd', 'multijet', 'cdti', 'dci', 'crdi'], errors: ['disel', 'diessel'] },
    { canonical: 'benzina', entity: 'alimentazione', value: 'benzina', synonyms: ['a benzina', 'e a benzina', 'motore a benzina', 'motore benzina', 'versione benzina', 'e una benzina', 'una benzina', 'tsi', 'tfsi', 'tce', 'puretech'] },
    { canonical: 'gpl', entity: 'alimentazione', value: 'gpl', synonyms: ['gpl', 'a gpl', 'bifuel', 'bi fuel', 'impianto gpl'] },
    { canonical: 'metano', entity: 'alimentazione', value: 'metano', synonyms: ['a metano', 'e a metano', 'impianto a metano', 'metano'] },
    { canonical: 'ibrida', entity: 'alimentazione', value: 'ibrida', synonyms: ['ibrida', 'ibrido', 'hybrid', 'mild hybrid', 'full hybrid', 'plug in', 'phev', 'hev'], errors: ['ibirda'] },
    { canonical: 'elettrica', entity: 'alimentazione', value: 'elettrica', synonyms: ['auto elettrica', 'auto elettriche', 'macchina elettrica', 'macchine elettriche', 'veicoli elettrici', 'vettura elettrica', 'veicolo elettrico', 'full electric', 'bev', 'e una elettrica', 'la mia elettrica'] },

    // ---- Sintomi: l'ordine conta (le voci più specifiche prima delle generiche) ----
    { canonical: 'freni_problema', entity: 'sintomo', value: 'freni_problema', negabile: true, synonyms: ['freni che fischiano', 'freni che stridono', 'freni che cigolano', 'freno che fischia', 'freni rumorosi', 'pastiglie finite', 'pastiglie consumate', 'freni consumati', 'freni spugnosi', 'pedale del freno', 'pedale del freno duro', 'frenata lunga', 'quando freno', 'frenando', 'non frena', 'non frenano', 'frena male', 'frena poco', 'non frena bene', 'freni non funzionano', 'freni non rispondono', 'senza freni', 'pedale a vuoto', 'pedale del freno a vuoto', 'pedale arriva fino in fondo', 'pedale fino in fondo', 'pedale arriva a fondo', 'pedale del freno arriva fino in fondo', 'il pedale va a fondo', 'pedale che affonda', 'pedale va a terra'], intent: 'problema_veicolo', errors: ['frena mlae'] },
    { canonical: 'spia_olio', entity: 'sintomo', value: 'spia_olio', negabile: true, synonyms: ['spia olio', 'spia dell olio', 'spia della pressione olio', 'spia della pressione dell olio', 'spia olio motore', 'spia dell olio motore', 'spia pressione olio', 'spia pressione dell olio', 'spia livello olio', 'spia del livello olio'], intent: 'problema_veicolo', errors: ['spia dell oilo'] },
    { canonical: 'spia_temperatura', entity: 'sintomo', value: 'spia_temperatura', negabile: true, synonyms: ['spia temperatura', 'spia della temperatura', 'spia temperatura acqua', 'spia refrigerante', 'spia liquido refrigerante', 'spia del liquido refrigerante', 'spia dell acqua'], intent: 'problema_veicolo' },
    { canonical: 'spia_airbag', entity: 'sintomo', value: 'spia_airbag', negabile: true, synonyms: ['spia airbag', 'spia dell airbag', 'spia air bag', 'spia degli airbag', 'spia dell air bag'], intent: 'problema_veicolo', errors: ['spia arbag', 'spia airbga'] },
    { canonical: 'spia_batteria', entity: 'sintomo', value: 'spia_batteria', negabile: true, synonyms: ['spia batteria', 'spia della batteria', 'spia alternatore', 'spia dell alternatore'], intent: 'problema_veicolo' },
    { canonical: 'spia_freni', entity: 'sintomo', value: 'spia_freni', negabile: true, synonyms: ['spia freni', 'spia dei freni', 'spia abs', 'spia dell abs', 'spia esp', 'spia dell esp'], intent: 'problema_veicolo' },
    { canonical: 'spia_fap', entity: 'sintomo', value: 'spia_fap', negabile: true, synonyms: ['spia fap', 'spia del fap', 'spia dpf', 'spia del dpf', 'spia filtro antiparticolato', 'spia del filtro antiparticolato', 'fap intasato', 'filtro antiparticolato intasato'], intent: 'problema_veicolo' },
    { canonical: 'spia_motore', entity: 'sintomo', value: 'spia_motore', negabile: true, synonyms: ['spia motore', 'spia del motore', 'spia gialla del motore', 'spia arancione del motore', 'check engine', 'spia check engine', 'spia iniezione', 'spia dell iniezione', 'spia motore accesa'], intent: 'problema_veicolo', errors: ['spia moto', 'spia motre', 'spai motore'] },
    { canonical: 'spia_generica', entity: 'sintomo', value: 'spia_generica', negabile: true, synonyms: ['spia accesa', 'una spia', 'si e accesa la spia', 'mi si e accesa una spia', 'si accende una spia', 'si e accesa una spia', 'spia rossa', 'spia gialla', 'spia arancione', 'spia sul cruscotto', 'spia del cruscotto', 'luce sul cruscotto', 'lucina sul cruscotto', 'lucetta sul cruscotto', 'spie accese', 'spie sul cruscotto'], intent: 'problema_veicolo' },
    { canonical: 'fumo_cofano', entity: 'sintomo', value: 'fumo_cofano', negabile: true, synonyms: ['fumo dal cofano', 'fumo sotto il cofano', 'dal cofano esce fumo', 'dal cofano esce del fumo', 'dal cofano esce un sacco di fumo', 'dal cofano esce tanto fumo', 'dal motore esce fumo', 'fumo bianco dal cofano', 'fumo nero dal cofano', 'fumo dal motore', 'fumo dal vano motore', 'fuma il cofano', 'fuma il motore', 'esce fumo dal cofano', 'esce fumo dal motore', 'cofano che fuma', 'fumo dal radiatore'], intent: 'emergenza_veicolo' },
    { canonical: 'fumo_scarico', entity: 'sintomo', value: 'fumo_scarico', negabile: true, synonyms: ['fumo dallo scarico', 'fumo nero', 'fumo bianco', 'fumo blu', 'fumo grigio', 'fa fumo', 'fuma', 'esce fumo', 'fumo dalla marmitta', 'fumata nera'], intent: 'problema_veicolo' },
    { canonical: 'odore_bruciato', entity: 'sintomo', value: 'odore_bruciato', negabile: true, synonyms: ['odore di bruciato', 'puzza di bruciato', 'sento puzza di bruciato', 'sento odore di bruciato', 'odore di frizione bruciata', 'odore di plastica bruciata', 'odore di olio bruciato', 'odore di gomma bruciata', 'puzza di gomma bruciata', 'puzza di plastica bruciata', 'puzza di frizione'], intent: 'emergenza_veicolo' },
    { canonical: 'odore_carburante', entity: 'sintomo', value: 'odore_carburante', negabile: true, synonyms: ['odore di benzina', 'puzza di benzina', 'odore di carburante', 'puzza di carburante', 'odore di gasolio', 'puzza di gasolio', 'odore di gas', 'puzza di gas', 'sento odore di benzina', 'sento puzza di benzina'], intent: 'emergenza_veicolo' },
    { canonical: 'perdita_liquidi', entity: 'sintomo', value: 'perdita_liquidi', negabile: true, synonyms: ['perde olio', 'perde acqua', 'perde liquido', 'perde liquidi', 'perde benzina', 'perde refrigerante', 'perde antigelo', 'perdita di olio', 'perdita di liquido', 'perdita di liquidi', 'perdita di refrigerante', 'perdita olio', 'perdita liquido', 'macchia di olio', 'macchia d olio', 'macchia sotto la macchina', 'macchia sotto l auto', 'macchie sotto la macchina', 'pozza sotto la macchina', 'pozza sotto l auto', 'gocciola', 'sgocciola', 'liquido sotto la macchina', 'liquido sotto l auto', 'olio sotto la macchina', 'olio per terra', 'pozzanghera di liquido', 'pozzanghera di olio', 'pozza di liquido', 'pozza di olio', 'chiazza di olio', 'chiazza di liquido', 'chiazza sotto la macchina', 'chiazza sotto l auto', 'liquido verde', 'liquido arancione', 'liquido rosa'], intent: 'emergenza_veicolo', errors: ['perde oilo'] },
    { canonical: 'surriscaldamento', entity: 'sintomo', value: 'surriscaldamento', negabile: true, synonyms: ['si surriscalda', 'surriscaldamento', 'surriscaldato', 'motore surriscaldato', 'temperatura alta', 'temperatura acqua alta', 'la temperatura sale', 'temperatura motore alta', 'bolle', 'bolle l acqua', 'motore bollente', 'va in temperatura'], intent: 'emergenza_veicolo', errors: ['surriscalda', 'surscaldamento'] },
    { canonical: 'sterzo_bloccato', entity: 'sintomo', value: 'sterzo_bloccato', negabile: true, synonyms: ['sterzo bloccato', 'volante bloccato', 'sterzo si e bloccato', 'volante si e bloccato', 'si e bloccato lo sterzo', 'si e bloccato il volante', 'lo sterzo e bloccato', 'il volante e bloccato', 'ho perso lo sterzo', 'non riesco a sterzare', 'sterzo che non gira', 'volante che non gira'], intent: 'emergenza_veicolo' },
    { canonical: 'sterzo_problema', entity: 'sintomo', value: 'sterzo_problema', negabile: true, synonyms: ['sterzo duro', 'sterzo pesante', 'sterzo che tira', 'la macchina tira', 'l auto tira', 'tira a destra', 'tira a sinistra', 'volante storto', 'volante duro', 'gioco nello sterzo', 'sterzo ballerino'], intent: 'problema_veicolo' },
    { canonical: 'incidente', entity: 'sintomo', value: 'incidente', synonyms: ['incidente', 'ho fatto un incidente', 'ho avuto un incidente', 'tamponato', 'tamponata', 'tamponamento', 'mi hanno tamponato', 'mi hanno tamponata', 'airbag scoppiati', 'airbag aperti'], intent: 'emergenza_veicolo' },
    { canonical: 'urto', entity: 'sintomo', value: 'urto', synonyms: ['ho urtato', 'ho sbattuto', 'ho strisciato', 'ho preso un palo', 'ho preso una buca', 'ho preso un marciapiede', 'ho battuto', 'ho preso una botta'], intent: 'problema_veicolo' },
    { canonical: 'non_parte', entity: 'sintomo', value: 'non_parte', negabile: true, synonyms: ['non parte', 'non si accende', 'non si avvia', 'non si mette in moto', 'non vuole partire', 'non parte piu', 'non ne vuole sapere di partire', 'fa click ma non parte', 'macchina morta', 'auto morta', 'si spegne', 'si e spenta', 'si e spento il motore', 'si ferma da sola', 'si ferma in mezzo alla strada'], intent: 'problema_veicolo', errors: ['non partte'] },
    { canonical: 'batteria_scarica', entity: 'sintomo', value: 'batteria_scarica', synonyms: ['batteria scarica', 'batteria a terra', 'batteria morta', 'batteria andata', 'batteria da cambiare', 'batteria e scarica'], intent: 'problema_veicolo' },
    { canonical: 'vibrazione', entity: 'sintomo', value: 'vibrazione', negabile: true, synonyms: ['vibra', 'vibrazione', 'vibrazioni', 'vibrazioni al volante', 'volante che vibra', 'tremolio', 'trema', 'tremore', 'sobbalza', 'scuote', 'sterzo che vibra', 'trema il volante'], intent: 'problema_veicolo', errors: ['vibbra'] },
    { canonical: 'rumore', entity: 'sintomo', value: 'rumore', negabile: true, synonyms: ['rumore', 'rumori', 'rumorino', 'rumoretto', 'fa rumore', 'strano rumore', 'rumore strano', 'sento un rumore', 'sento dei rumori', 'fischio', 'fischia', 'stride', 'stridio', 'cigola', 'cigolio', 'scricchiola', 'ticchetta', 'ticchettio', 'borbotta', 'ronza', 'ronzio', 'sbatte', 'tic tic', 'toc toc', 'clack', 'sferragli'], intent: 'problema_veicolo', errors: ['rumorre', 'ruomore', 'rumoree'] },
    { canonical: 'perdita_potenza', entity: 'sintomo', value: 'perdita_potenza', negabile: true, synonyms: ['strattona', 'strappi', 'strappa', 'perde colpi', 'tossisce', 'balbetta', 'singhiozza', 'va a scatti', 'non ha forza', 'perde potenza', 'non tira piu', 'manca potenza', 'poca potenza', 'va in protezione', 'modalita protezione', 'limp mode', 'e debole', 'non accelera'], intent: 'problema_veicolo', errors: ['stratona', 'strattonna'] },
    { canonical: 'cambio_difficile', entity: 'sintomo', value: 'cambio_difficile', negabile: true, synonyms: ['marce che non entrano', 'marcia non entra', 'non entra la marcia', 'non entrano le marce', 'cambio duro', 'cambio rumoroso', 'cambio che gratta', 'grattano le marce', 'gratta la marcia', 'si impunta il cambio', 'frizione che slitta', 'la frizione slitta', 'frizione dura', 'pedale della frizione', 'frizione che scivola', 'frizione molle'], intent: 'problema_veicolo' },
    { canonical: 'clima_non_funziona', entity: 'sintomo', value: 'clima_non_funziona', negabile: true, synonyms: ['clima non funziona', 'aria condizionata non funziona', 'aria condizionata non raffredda', 'il clima non raffredda', 'clima non raffredda', 'non fa freddo', 'non esce aria fredda', 'il condizionatore non va', 'clima non va', 'esce aria calda dal clima', 'puzza il clima', 'odore dal clima', 'il clima puzza', 'il condizionatore puzza'], intent: 'problema_veicolo' },
    { canonical: 'gomma_problema', entity: 'sintomo', value: 'gomma_problema', synonyms: ['gomma a terra', 'gomma bucata', 'foratura', 'ho forato', 'gomma forata', 'gomma sgonfia', 'pneumatico a terra', 'pneumatico bucato', 'gomma consumata', 'gomme lisce', 'gomme consumate', 'pressione bassa', 'gomma scoppiata', 'e scoppiata la gomma', 'scoppiata una gomma'], intent: 'problema_veicolo' },
    { canonical: 'scarico_rumoroso', entity: 'sintomo', value: 'scarico_rumoroso', negabile: true, synonyms: ['marmitta rotta', 'marmitta bucata', 'scarico rumoroso', 'scarico che fa rumore', 'marmitta che fa rumore', 'scarico bucato', 'scarico a terra'], intent: 'problema_veicolo' },
    { canonical: 'consumo_anomalo', entity: 'sintomo', value: 'consumo_anomalo', negabile: true, synonyms: ['consuma olio', 'consuma troppo', 'consuma tanto', 'consuma molto olio', 'consumo olio', 'consumi alti', 'consumi elevati', 'consuma troppa benzina', 'consuma troppo gasolio'], intent: 'problema_veicolo' },
    { canonical: 'problema_generico', entity: 'sintomo', value: 'problema_generico', negabile: true, synonyms: ['qualcosa che non va', 'ha un problema', 'c e un problema', 'non va bene', 'non funziona', 'qualcosa non va', 'strani rumori', 'comportamento strano'], intent: 'problema_veicolo' },

    // ---- Concetti di conversazione (collegano all'intent, nessuna entità) ----
    { canonical: 'prezzo', synonyms: ['prezzo', 'prezzi', 'costo', 'costi', 'quanto costa', 'quanto costano', 'quanto viene', 'quanto mi viene', 'quanto mi costa', 'quanto devo pagare', 'quanto spendo', 'tariffa', 'tariffe', 'listino', 'quanto si paga', 'quanto prendete', 'quanto vi prendete', 'costo orario', 'manodopera'], intent: 'info_prezzi' },
    { canonical: 'orari', synonyms: ['orari', 'orario', 'aperti', 'aperto', 'chiusi', 'apertura', 'chiusura', 'fino a che ora', 'a che ora aprite', 'a che ora chiudete', 'pausa pranzo'], intent: 'info_orari' },
    { canonical: 'indirizzo', synonyms: ['indirizzo', 'dove siete', 'dove vi trovate', 'dove si trova', 'come vi raggiungo', 'come arrivo', 'parcheggio', 'posizione', 'dov e l officina'], intent: 'info_posizione' },
    { canonical: 'pagamento', synonyms: ['pagamento', 'pagamenti', 'rate', 'rateale', 'rateizzare', 'rateizzazione', 'finanziamento', 'bancomat', 'carta di credito', 'carte di credito', 'carte', 'contanti', 'fattura', 'pos', 'satispay', 'assegno', 'ricevuta'], intent: 'info_pagamenti' },
    { canonical: 'preventivo', synonyms: ['preventivo', 'preventivi', 'preventivare', 'stima dei costi', 'stima del costo', 'stima di spesa', 'stima', 'quanto mi costerebbe'], intent: 'richiesta_preventivo' },
    { canonical: 'appuntamento', synonyms: ['appuntamento', 'prenotare', 'prenotazione', 'prenoto', 'fissare', 'disponibilita', 'posto libero', 'slot'], intent: 'prenota_intervento' },
    { canonical: 'stato_lavori', synonyms: ['e pronta la mia auto', 'e pronta la macchina', 'a che punto siete', 'ritirare la macchina', 'ritirare l auto', 'ritirare la mia auto', 'ritiro l auto', 'ritiro la macchina'], intent: 'stato_lavori' },
    { canonical: 'soccorso', synonyms: ['carro attrezzi', 'soccorso stradale', 'carroattrezzi', 'carro soccorso', 'in panne', 'sono in panne', 'auto in panne', 'macchina in panne', 'rimasto a piedi', 'rimasta a piedi', 'mi ha lasciato a piedi'], intent: 'emergenza_veicolo' },

    // ---- Marche (entità `marca`), modelli (`modello`) e anni (`anno`) generati dalle tabelle ----
    ...MARCHE.map(([valore, forme]) => ({ canonical: `marca_${valore}`, entity: 'marca', value: valore, synonyms: forme })),
    ...MODELLI.map(([valore, forme]) => ({ canonical: `modello_${valore}`, entity: 'modello', value: valore, synonyms: forme })),
    // Il modello implica la marca ("la mia Panda" -> Fiat): così non si richiede una marca già nota.
    ...MODELLI.map(([valore, forme, marca]) => ({ canonical: `marca_da_modello_${valore}`, entity: 'marca', value: marca, synonyms: forme })),
    ...ANNI.map((a) => ({ canonical: `anno_${a}`, entity: 'anno', value: String(a), synonyms: [String(a)] })),
  ],

  intents: [
    { id: 'prenota_intervento', nome: 'Prenotazione intervento', categoria: 'BOOKING', priorita: 20, safety_level: 'LOW',
      descrizione: 'Il cliente vuole portare l\'auto in officina per un intervento (tagliando, revisione, riparazione) o chiede disponibilità.',
      esempi: ['vorrei prenotare', 'vorrei un appuntamento', 'vorrei prendere un appuntamento', 'vorrei fissare un appuntamento', 'mi serve un appuntamento', 'avete posto domani', 'avete posto oggi', 'avete posto questa settimana', 'avete disponibilita', 'avete disponibilita questa settimana', 'quando posso portare l auto', 'quando posso portare la macchina', 'posso portare l auto', 'posso portare la macchina', 'devo portare l auto', 'devo portare la macchina', 'vorrei portare l auto in officina', 'vorrei portare la macchina in officina', 'posso passare domani', 'quando posso passare', 'quando posso venire', 'posso venire', 'quando posso portarla', 'quando riuscite a prendermi la macchina', 'quando siete liberi', 'cerco un appuntamento', 'posso prenotare', 'prenotazione'],
      keywords: ['prenotare', 'prenotazione', 'appuntamento', 'disponibilita', 'fissare'],
      combinazioni: [
        { entity: 'servizio', con: ['vorrei', 'mi serve', 'mi servirebbe', 'avrei bisogno', 'ho bisogno', 'devo fare', 'devo fissare', 'devo portare', 'vorrei fare', 'voglio fare', 'mi occorre', 'cerco', 'posso portare', 'posso passare', 'portare la macchina', 'portare l auto', 'volevo fare', 'dovrei', 'dovrei fare', 'quando potete', 'quando riuscite', 'e scaduta', 'e scaduto', 'scade', 'in scadenza', 'scadenza', 'spia del tagliando', 'spia tagliando', 'spia service', 'devo cambiare', 'devo sostituire', 'da cambiare', 'da fare', 'da sostituire', 'prenotare', 'prenotazione', 'prenoto', 'appuntamento', 'fissare', 'voglio solo', 'vorrei solo', 'devo solo', 'mi serve solo', 'solo il', 'solo la', 'solo un', 'solo una', 'solo per'], con_entities: ['giorno', 'fascia_oraria'], non_con_concepts: ['preventivo', 'prezzo'], score: 0.8 },
        { entity: 'servizio', con: [], con_entities: ['marca', 'modello', 'anno'], non_con_concepts: ['preventivo', 'prezzo'], score: 0.72 },
        { entity: 'cliente_nuovo', con: ['vorrei venire', 'vorrei portare', 'vorrei un appuntamento'], score: 0.7 },
      ],
      required_entities: ['servizio', 'nome_cliente'], optional_entities: ['marca', 'modello', 'anno', 'alimentazione', 'targa', 'chilometri', 'giorno', 'fascia_oraria', 'cliente_nuovo', 'auto_sostitutiva'],
      actions: ['ask_missing_information', 'propose_slot', 'create_booking', 'create_lead'] },
    { id: 'richiesta_preventivo', nome: 'Richiesta preventivo', categoria: 'LEAD', priorita: 25, safety_level: 'LOW',
      descrizione: 'Il cliente chiede un preventivo o una stima per un intervento o una riparazione.',
      esempi: ['vorrei un preventivo', 'mi fate un preventivo', 'mi serve un preventivo', 'mi fate un preventivo per', 'preventivo per la frizione', 'preventivo per i freni', 'preventivo per la distribuzione', 'vorrei sapere quanto mi costerebbe la riparazione', 'una stima dei costi', 'potete farmi una stima', 'stima del costo', 'preventivo per la riparazione', 'preventivo gratuito', 'quanto mi costerebbe in tutto', 'mi fate un preventivo per l auto', 'mi potete fare un preventivo'],
      keywords: ['preventivo', 'preventivi'],
      required_entities: ['servizio', 'nome_cliente'], optional_entities: ['marca', 'modello', 'anno', 'alimentazione', 'targa', 'chilometri'],
      actions: ['ask_missing_information', 'create_lead', 'notify_owner'] },
    { id: 'problema_veicolo', nome: 'Problema, rumore o spia', categoria: 'SUPPORT', priorita: 15, safety_level: 'MEDIUM', campi_tenant: true,
      descrizione: 'Il cliente descrive un problema all\'auto (rumore, spia, vibrazione, difficoltà di avviamento) non necessariamente urgente.',
      esempi: ['la macchina fa un rumore strano', 'l auto fa un rumore strano', 'la macchina fa un rumore', 'l auto fa un rumore', 'la macchina vibra', 'l auto vibra', 'ho un problema con la macchina', 'ho un problema con l auto', 'ho un problema alla macchina', 'ho un problema all auto', 'la macchina ha un problema', 'l auto ha un problema', 'c e qualcosa che non va', 'qualcosa non va', 'ho una spia accesa sul cruscotto della macchina', 'mi si e accesa una spia sul cruscotto della macchina', 'la macchina non parte', 'l auto non parte', 'la macchina non si accende', 'l auto non si accende', 'la macchina strattona', 'l auto strattona', 'la macchina perde colpi', 'si e spenta la macchina', 'il clima non funziona', 'la batteria e scarica', 'ho forato una gomma', 'ho una gomma a terra', 'la macchina tira', 'fa uno strano rumore'],
      keywords: ['problema con la macchina', 'problema con l auto', 'problema alla macchina', 'problema all auto'],
      required_entities: ['sintomo', 'nome_cliente'], optional_entities: ['marca', 'modello', 'anno', 'alimentazione', 'targa', 'chilometri', 'giorno', 'fascia_oraria', 'cliente_nuovo'],
      actions: ['ask_missing_information', 'propose_slot', 'notify_owner', 'create_lead'] },
    { id: 'emergenza_veicolo', nome: 'Emergenza o pericolo', categoria: 'EMERGENCY', priorita: 5, safety_level: 'HIGH',
      descrizione: 'Situazione di pericolo o auto ferma: freni, sterzo, fumo, carburante, spie rosse, perdite, incidente, panne. Serve contatto rapido con l\'officina e, se c\'è pericolo, soccorso.',
      esempi: ['ho un problema urgente con la macchina', 'ho un problema urgente con l auto', 'e urgente', 'e un emergenza', 'ho un emergenza con la macchina', 'ho fatto un incidente', 'ho avuto un incidente', 'sono in panne', 'sono rimasto in panne', 'la macchina e in panne', 'sono rimasto a piedi', 'mi serve il carro attrezzi', 'ho bisogno del carro attrezzi', 'mi serve il soccorso stradale', 'ho bisogno di aiuto subito', 'sono fermo in strada', 'sono bloccato in strada', 'sono fermo in autostrada', 'ho bisogno subito di un meccanico', 'mi serve subito un meccanico'],
      keywords: ['urgente', 'urgenza', 'emergenza', 'subito', 'carro attrezzi', 'soccorso stradale', 'in panne', 'incidente'],
      required_entities: ['nome_cliente'], optional_entities: ['sintomo', 'marca', 'modello', 'targa'],
      actions: ['ask_missing_information', 'notify_owner', 'emergency_escalation'] },
    { id: 'stato_lavori', nome: 'Stato dell\'auto in officina', categoria: 'HUMAN_HANDOFF', priorita: 12, safety_level: 'LOW',
      descrizione: 'Il cliente chiede se l\'auto è pronta, a che punto è la riparazione o quando può ritirarla. Il sistema non conosce lo stato dei lavori: passa allo staff.',
      esempi: ['e pronta la mia auto', 'e pronta la macchina', 'la mia auto e pronta', 'la macchina e pronta', 'posso ritirare la macchina', 'posso ritirare l auto', 'quando posso ritirare la macchina', 'quando posso ritirare l auto', 'quando e pronta la macchina', 'quando e pronta l auto', 'a che punto siete con la mia auto', 'a che punto siete con la macchina', 'a che punto e la riparazione', 'ci sono novita sulla macchina', 'ci sono novita sull auto', 'avete finito con la macchina', 'avete finito con l auto', 'sono pronti i lavori', 'e finita la macchina', 'e finita l auto'],
      keywords: ['ritirare', 'a che punto siete', 'a che punto e', 'novita sulla macchina', 'novita sull auto', 'e pronta', 'e pronto'],
      required_entities: [], optional_entities: ['marca', 'modello', 'targa'], actions: ['human_handoff'] },
    { id: 'info_prezzi', nome: 'Informazioni prezzi', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il cliente chiede quanto costa un intervento o una riparazione.',
      esempi: ['quanto costa', 'che prezzo avete', 'quanto viene', 'quanto mi viene', 'quanto devo pagare', 'mi dici il costo', 'avete un listino', 'quali sono i prezzi', 'quanto costa un tagliando', 'quanto costa la revisione', 'quanto costa cambiare', 'prezzi', 'costo', 'quanto prendete', 'quanto costano', 'qual e il costo della manodopera', 'quanto vi prendete'],
      keywords: ['prezzo', 'prezzi', 'costo', 'costi', 'tariffe', 'listino', 'manodopera'],
      required_entities: [], optional_entities: ['servizio', 'marca', 'modello'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_orari', nome: 'Informazioni orari', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il cliente chiede gli orari di apertura dell\'officina.',
      esempi: ['a che ora aprite', 'a che ora chiudete', 'siete aperti il sabato', 'siete aperti oggi', 'quali sono gli orari', 'fino a che ora siete aperti', 'orari di apertura', 'siete aperti a pranzo', 'siete aperti domenica', 'fate orario continuato', 'a che ora posso portare l auto', 'a che ora posso passare', 'siete aperti ad agosto'],
      keywords: ['orari', 'orario', 'aperti', 'chiusi'],
      required_entities: [], optional_entities: ['giorno'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_posizione', nome: 'Informazioni posizione', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il cliente chiede dove si trova l\'officina o come raggiungerla.',
      esempi: ['dove siete', 'qual e l indirizzo', 'come vi raggiungo', 'dove si trova l officina', 'c e parcheggio', 'come arrivo da voi', 'indirizzo dell officina', 'dov e l officina', 'dove posso parcheggiare', 'dove lascio la macchina', 'dove vi trovate', 'avete un parcheggio'],
      keywords: ['indirizzo', 'parcheggio', 'dove siete', 'dove vi trovate', 'dov e l officina', 'dove posso parcheggiare'],
      required_entities: [], optional_entities: [], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_servizi', nome: 'Informazioni servizi e marchi trattati', categoria: 'DISCOVERY', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il cliente chiede quali lavori fa l\'officina, quali marche tratta, se ha un certo servizio (carro attrezzi, auto ibride, ricambi originali).',
      esempi: ['che servizi offrite', 'che lavori fate', 'di cosa vi occupate', 'fate la revisione', 'fate le revisioni', 'fate i tagliandi', 'fate il tagliando', 'fate la pre revisione', 'fate il cambio olio', 'fate la diagnosi', 'fate la diagnosi con la centralina', 'fate la frizione', 'fate i freni', 'fate le gomme', 'fate il cambio gomme', 'fate la convergenza', 'fate la ricarica del clima', 'ricaricate il clima', 'ricaricate l aria condizionata', 'fate anche la carrozzeria', 'fate carrozzeria', 'fate il carro attrezzi', 'fate soccorso stradale', 'avete il carro attrezzi', 'avete il soccorso stradale', 'trattate anche la mia marca', 'trattate tutte le marche', 'lavorate su tutte le marche', 'lavorate sulle auto elettriche', 'trattate le auto ibride', 'fate assistenza sulle ibride', 'riparate anche le ibride', 'fate anche le auto elettriche', 'usate ricambi originali', 'montate ricambi originali', 'avete ricambi originali', 'fate anche i furgoni', 'fate anche le moto', 'fate anche i gpl', 'fate impianti gpl'],
      keywords: ['servizi', 'vi occupate', 'trattate', 'lavorate su', 'fate assistenza', 'ricambi originali', 'ricambi'],
      combinazioni: [
        { entity: 'marca', con: ['trattate', 'lavorate', 'riparate', 'fate assistenza', 'seguite', 'avete esperienza', 'fate manutenzione'], score: 0.8 },
        { entity: 'alimentazione', con: ['trattate', 'lavorate', 'riparate', 'fate assistenza', 'seguite', 'avete esperienza', 'fate manutenzione'], score: 0.8 },
      ],
      required_entities: [], optional_entities: ['servizio', 'marca', 'alimentazione'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_pagamenti', nome: 'Pagamenti', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Modalità di pagamento, rate, fattura.',
      esempi: ['accettate carte', 'si puo pagare a rate', 'fate rateizzazione', 'accettate il bancomat', 'avete il finanziamento', 'accettate carte di credito', 'fate fattura', 'si paga con la carta', 'si puo pagare con il pos', 'pagamento in contanti', 'si puo pagare dopo', 'pagamento alla consegna'],
      keywords: ['rate', 'rateale', 'finanziamento', 'bancomat', 'contanti', 'fattura', 'rateizzare'],
      required_entities: [], optional_entities: [], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_auto_sostitutiva', nome: 'Auto sostitutiva', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il cliente chiede se è disponibile un\'auto sostitutiva o di cortesia mentre l\'officina lavora sulla sua.',
      esempi: ['avete l auto sostitutiva', 'avete un auto sostitutiva', 'avete una macchina sostitutiva', 'date l auto sostitutiva', 'c e l auto sostitutiva', 'mi date un auto di cortesia', 'avete auto di cortesia', 'avete un muletto', 'mi serve un auto sostitutiva', 'mi serve l auto sostitutiva', 'se lascio la macchina mi date un auto', 'ho bisogno di una macchina mentre la lascio', 'senza macchina per qualche giorno'],
      keywords: ['sostitutiva', 'di cortesia', 'muletto', 'auto in prestito'],
      required_entities: [], optional_entities: [], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_documenti', nome: 'Cosa portare', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Cosa serve portare in officina (documenti, libretto, chiavi, ecc.).',
      esempi: ['cosa devo portare', 'che documenti servono', 'devo portare il libretto', 'serve la carta di circolazione', 'serve il libretto', 'serve il libretto di circolazione', 'devo portare qualcosa', 'cosa serve per la revisione', 'cosa serve per il tagliando', 'servono i documenti', 'serve la targa', 'devo lasciare le chiavi', 'devo portare il libretto dei tagliandi', 'serve il libretto uso e manutenzione'],
      keywords: ['documenti', 'libretto', 'carta di circolazione', 'libretto di circolazione', 'libretto dei tagliandi'],
      required_entities: [], optional_entities: [], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_interventi', nome: 'Come funziona un intervento', categoria: 'INFORMATION', priorita: 32, safety_level: 'MEDIUM',
      descrizione: 'Domande generali sui lavori: cos\'è, a cosa serve, ogni quanto si fa, differenza tra interventi, durata in generale, significato delle spie.',
      esempi: ['cos e il tagliando', 'cosa comprende il tagliando', 'cosa si controlla nel tagliando', 'ogni quanto si fa il tagliando', 'ogni quanto va fatto il tagliando', 'differenza tra tagliando e revisione', 'che differenza c e tra tagliando e revisione', 'ogni quanto si fa la revisione', 'quando scade la revisione', 'cosa serve per fare la revisione', 'cos e la pre revisione', 'a cosa serve la pre revisione', 'a cosa serve la revisione', 'a cosa serve il tagliando', 'cos e la diagnosi', 'a cosa serve la diagnosi', 'a cosa serve la spia', 'cosa significa la spia', 'cosa vuol dire la spia', 'cosa significa la spia dell olio', 'cosa significa la spia motore', 'cosa significa la spia airbag', 'cos e il fap', 'cos e il filtro antiparticolato', 'ogni quanto si cambia l olio', 'ogni quanto va cambiato l olio', 'ogni quanto si cambiano le pastiglie', 'ogni quanto si cambia la cinghia di distribuzione', 'quando va cambiata la cinghia di distribuzione', 'ogni quanto si ricarica il clima', 'cos e la convergenza', 'cos e l equilibratura', 'a cosa serve l equilibratura', 'quanto dura la batteria', 'quanto dura il tagliando', 'quanto ci vuole per il tagliando', 'quanto ci vuole per un tagliando', 'quanto tempo ci vuole per la revisione', 'cos e il liquido freni', 'va cambiato il liquido dei freni', 'ogni quanto si cambiano le candele', 'a cosa servono gli ammortizzatori', 'si fa il tagliando anche sulle ibride', 'perdo la garanzia se faccio il tagliando fuori dalla casa', 'cosa devo fare se si accende una spia', 'che informazioni servono per un preventivo'],
      keywords: ['cos e', 'a cosa serve', 'a cosa servono', 'cosa significa', 'cosa vuol dire', 'ogni quanto', 'differenza', 'quanto dura', 'quanto ci vuole', 'consiste', 'quando va cambiat', 'quando si cambia'],
      required_entities: [], optional_entities: ['servizio'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_personale', nome: 'Informazioni sul personale', categoria: 'INFORMATION', priorita: 33, safety_level: 'LOW',
      descrizione: 'Chi sono i meccanici o il titolare dell\'officina.',
      esempi: ['chi sono i meccanici', 'chi lavora sulla mia macchina', 'chi e il titolare', 'chi e il meccanico', 'quanti meccanici avete', 'avete un elettrauto', 'avete un gommista', 'chi e il responsabile dell officina', 'con chi parlo per i preventivi'],
      keywords: ['meccanici', 'meccanico', 'titolare', 'elettrauto', 'responsabile'],
      required_entities: [], optional_entities: [], actions: ['search_knowledge', 'answer_information'] },
    { id: 'cancella_appuntamento', nome: 'Annullamento appuntamento', categoria: 'CANCELLATION', priorita: 10, safety_level: 'LOW',
      descrizione: 'Il cliente vuole disdire un appuntamento già preso.',
      esempi: ['devo disdire', 'vorrei cancellare l appuntamento', 'non posso venire', 'annullare l appuntamento', 'devo annullare', 'disdire la prenotazione', 'non riesco a venire', 'non posso portare l auto', 'devo annullare il tagliando', 'cancellate la prenotazione', 'devo cancellare la revisione', 'vorrei disdire', 'devo cancellare', 'vorrei annullare', 'annullate la prenotazione', 'annulla la prenotazione', 'annullare la prenotazione', 'annullate l appuntamento', 'cancella la prenotazione', 'disdico la prenotazione', 'annullare il tagliando', 'annullare la revisione', 'cancellare la revisione', 'cancellare il tagliando', 'disdire il tagliando', 'disdire la revisione'],
      keywords: ['disdire', 'disdetta', 'annullare', 'cancellare', 'cancellate'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'sposta_appuntamento', nome: 'Spostamento appuntamento', categoria: 'RESCHEDULE', priorita: 10, safety_level: 'LOW',
      descrizione: 'Il cliente vuole spostare un appuntamento già preso.',
      esempi: ['devo spostare l appuntamento', 'posso cambiare giorno', 'vorrei rimandare', 'posso anticipare l appuntamento', 'posso spostare a un altro giorno', 'devo cambiare orario', 'posticipare l appuntamento', 'posso portare l auto un altro giorno', 'devo spostare il tagliando', 'possiamo spostare la revisione', 'posso spostare', 'devo spostare', 'vorrei spostare', 'spostare la revisione', 'spostare il tagliando', 'spostare la prenotazione', 'posso anticipare', 'posso posticipare', 'posso rimandare', 'vorrei anticipare', 'vorrei posticipare'],
      keywords: ['spostare', 'rimandare', 'anticipare', 'posticipare', 'rinviare', 'slittare'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'reclamo', nome: 'Reclamo', categoria: 'COMPLAINT', priorita: 8, safety_level: 'MEDIUM',
      descrizione: 'Insoddisfazione per un lavoro, un prezzo o un servizio ricevuto; problema tornato dopo la riparazione.',
      esempi: ['sono insoddisfatto', 'vorrei fare un reclamo', 'voglio lamentarmi', 'il lavoro non e andato bene', 'sono molto arrabbiato', 'ho avuto un brutto servizio', 'non sono contento del lavoro', 'sono stato trattato male', 'sono deluso dal servizio', 'il problema e tornato dopo la riparazione', 'dopo la riparazione fa ancora lo stesso rumore', 'non avete risolto il problema', 'lavoro fatto male', 'mi avete fatto pagare troppo', 'avete danneggiato la mia auto', 'la macchina e peggio di prima', 'dopo essere stata da voi'],
      keywords: ['reclamo', 'lamentarmi', 'lamentela', 'insoddisfatto', 'insoddisfatta', 'arrabbiato', 'arrabbiata', 'trattato male', 'trattata male', 'inaccettabile', 'deluso', 'delusa', 'vergogna', 'fatto male', 'non avete risolto', 'non e stato risolto', 'danneggiato', 'peggio di prima'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'parla_con_persona', nome: 'Richiesta di una persona', categoria: 'HUMAN_HANDOFF', priorita: 1, safety_level: 'LOW',
      descrizione: 'Il cliente chiede di parlare con una persona o con il meccanico.',
      esempi: ['voglio parlare con una persona', 'mi passate qualcuno', 'vorrei parlare con il meccanico', 'vorrei parlare con il titolare', 'chiamatemi', 'richiamatemi', 'posso parlare con l officina'],
      keywords: ['operatore', 'meccanico', 'titolare'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'saluto', nome: 'Saluto', categoria: 'DISCOVERY', priorita: 40, safety_level: 'LOW', solo_isolato: true,
      descrizione: 'Solo un saluto, senza richiesta.',
      esempi: ['ciao', 'buongiorno', 'buonasera', 'salve', 'buon pomeriggio', 'ehi', 'ciao a tutti', 'buondi'],
      keywords: [], required_entities: [], optional_entities: [], actions: ['answer_information'] },
    { id: 'chiusura', nome: 'Ringraziamento o chiusura', categoria: 'FOLLOW_UP', priorita: 40, safety_level: 'LOW', solo_isolato: true,
      descrizione: 'Il cliente ringrazia o chiude la conversazione.',
      esempi: ['grazie', 'grazie mille', 'ok grazie', 'perfetto grazie', 'va bene', 'ok', 'a posto', 'ricevuto', 'ci sentiamo', 'ottimo grazie'],
      keywords: [], required_entities: [], optional_entities: [], actions: ['answer_information'] },
  ],

  urgency_rules: {
    // CRITICAL: pericolo immediato per le persone o per la guida -> risposta predefinita
    // (non guidare, accostare, 112/soccorso) senza chiamate al modello.
    critical: [
      // freni e sterzo
      'non frena', 'non frenano', 'frena male', 'frena poco', 'non frena bene', 'non frenava', 'non frenavano', 'freni non funzionano', 'freni non rispondono', 'freni che non funzionano', 'freni non vanno', 'freno non va', 'freno non tiene', 'freni non tengono', 'senza freni', 'sono senza freni', 'ho perso i freni', 'ho perso il freno', 'freni spariti',
      'pedale a vuoto', 'pedale del freno a vuoto', 'pedale arriva fino in fondo', 'pedale fino in fondo', 'pedale arriva a fondo', 'pedale del freno arriva fino in fondo', 'pedale del freno va a fondo', 'il pedale va a fondo', 'pedale va a fondo', 'pedale che affonda', 'pedale del freno affonda', 'pedale va a terra', 'pedale del freno molle', 'il freno va a fondo',
      'sterzo bloccato', 'volante bloccato', 'sterzo si e bloccato', 'volante si e bloccato', 'si e bloccato lo sterzo', 'si e bloccato il volante', 'lo sterzo e bloccato', 'il volante e bloccato', 'ho perso lo sterzo', 'non riesco a sterzare', 'sterzo che non gira', 'volante che non gira',
      // fumo e fuoco
      'fumo dal cofano', 'fumo sotto il cofano', 'dal cofano esce fumo', 'dal cofano esce del fumo', 'dal cofano esce un sacco di fumo', 'dal cofano esce tanto fumo', 'dal motore esce fumo', 'fumo bianco dal cofano', 'fumo nero dal cofano', 'fumo dal motore', 'fumo dal vano motore', 'fuma il cofano', 'fuma il motore', 'esce fumo dal cofano', 'esce fumo dal motore', 'cofano che fuma', 'fumo dal radiatore',
      'fiamme', 'ha preso fuoco', 'prende fuoco', 'va a fuoco', 'sta andando a fuoco', 'incendio', 'incendiata', 'incendiato',
      // carburante e gas
      'odore di benzina', 'puzza di benzina', 'odore di carburante', 'puzza di carburante', 'odore di gasolio forte', 'perde benzina', 'perdita di benzina', 'perdita di carburante', 'perde carburante',
      'odore di gas', 'puzza di gas',
      // persone
      'ci sono feriti', 'ci sono dei feriti', 'persone ferite', 'c e un ferito', 'ci sono persone ferite', 'sono ferito', 'sono ferita', 'ho un ferito', 'feriti',
      'airbag scoppiati', 'si sono aperti gli airbag', 'airbag aperti', 'airbag esplosi',
    ],
    // HIGH: auto da non guidare / intervento urgente -> priorità all'officina e invito alla prudenza.
    high: [
      'spia olio accesa', 'spia dell olio accesa', 'spia della pressione olio rossa', 'spia della pressione olio accesa', 'spia della pressione dell olio rossa', 'spia della pressione dell olio accesa', 'spia olio rossa', 'spia dell olio rossa', 'olio rossa', 'spia pressione olio rossa', 'spia dell olio e rossa', 'spia dell olio e accesa', 'spia olio e rossa', 'spia olio e accesa', 'pressione olio e rossa', 'pressione olio e accesa', 'pressione dell olio e rossa', 'spia della temperatura e rossa', 'spia della temperatura e accesa', 'spia temperatura e rossa', 'spia temperatura e accesa', 'accesa la spia dell olio', 'accesa la spia olio', 'accende la spia dell olio', 'accende la spia olio', 'si accende la spia dell olio', 'spia pressione olio accesa', 'spia dell olio motore accesa',
      'spia temperatura accesa', 'spia della temperatura accesa', 'spia temperatura rossa', 'spia della temperatura rossa', 'accesa la spia della temperatura', 'accesa la spia temperatura', 'accende la spia della temperatura', 'spia refrigerante accesa',
      'spia freni accesa', 'spia dei freni accesa', 'accesa la spia freni', 'accesa la spia dei freni', 'spia rossa', 'spia rossa accesa',
      'si surriscalda', 'surriscaldamento', 'surriscaldato', 'motore surriscaldato', 'temperatura alta', 'temperatura acqua alta', 'la temperatura sale', 'temperatura motore alta', 'bolle', 'bolle l acqua', 'motore bollente',
      'perde olio', 'perde acqua', 'perde liquido', 'perde liquidi', 'perde refrigerante', 'perde antigelo', 'perdita di olio', 'perdita di liquido', 'perdita di liquidi', 'perdita di refrigerante', 'perdita olio', 'perdita liquido', 'macchia di olio sotto', 'macchia sotto la macchina', 'macchia sotto l auto', 'macchie sotto la macchina', 'pozza sotto la macchina', 'pozza sotto l auto', 'liquido sotto la macchina', 'liquido sotto l auto', 'olio sotto la macchina', 'olio per terra', 'gocciola', 'sgocciola', 'pozzanghera di liquido', 'pozzanghera di olio', 'pozza di liquido', 'pozza di olio', 'chiazza di olio', 'chiazza di liquido', 'chiazza sotto la macchina', 'chiazza sotto l auto', 'liquido verde', 'liquido arancione', 'liquido rosa',
      'odore di bruciato', 'puzza di bruciato', 'sento puzza di bruciato', 'sento odore di bruciato', 'odore di frizione bruciata', 'odore di plastica bruciata', 'odore di olio bruciato', 'odore di gomma bruciata', 'puzza di gomma bruciata', 'puzza di plastica bruciata',
      'incidente', 'ho fatto un incidente', 'ho avuto un incidente', 'tamponato', 'tamponata', 'tamponamento', 'mi hanno tamponato', 'mi hanno tamponata',
      'sono in panne', 'in panne', 'sono rimasto a piedi', 'sono rimasta a piedi', 'mi ha lasciato a piedi', 'mi ha lasciata a piedi', 'sono fermo in strada', 'sono ferma in strada', 'sono bloccato in strada', 'sono bloccata in strada', 'sono fermo in autostrada', 'sono ferma in autostrada', 'sono bloccato in autostrada', 'si e fermata in mezzo alla strada', 'si e fermata in autostrada',
      'gomma scoppiata', 'e scoppiata la gomma', 'scoppiata una gomma', 'volante che vibra forte', 'rumore forte dai freni', 'rumore metallico dai freni', 'freni che stridono forte',
      'e urgente', 'urgentissimo', 'emergenza', 'e un emergenza', 'ho bisogno subito', 'mi serve subito un meccanico', 'mi serve il carro attrezzi', 'ho bisogno del carro attrezzi', 'serve il carro attrezzi', 'mi serve il soccorso stradale', 'ho bisogno del soccorso stradale',
    ],
    // MEDIUM: disturbo che merita priorità ma senza pericolo immediato dichiarato.
    medium: [
      'spia motore', 'spia del motore', 'spia airbag', 'spia dell airbag', 'spia batteria', 'spia della batteria', 'spia fap', 'spia del fap', 'spia dpf', 'spia abs', 'spia esp', 'spia accesa', 'una spia', 'si e accesa la spia', 'spie accese', 'spia gialla', 'spia arancione',
      'rumore', 'rumori', 'fa rumore', 'strano rumore', 'rumore strano', 'fischia', 'stride', 'cigola', 'scricchiola', 'ticchetta',
      'vibra', 'vibrazione', 'vibrazioni', 'tremolio', 'trema', 'sobbalza',
      'non parte', 'non si accende', 'non si avvia', 'non si mette in moto', 'si spegne', 'si e spenta', 'batteria scarica', 'batteria a terra', 'batteria morta',
      'strattona', 'strappi', 'perde colpi', 'perde potenza', 'non ha forza', 'va in protezione',
      'fumo dallo scarico', 'fumo nero', 'fumo bianco', 'fumo blu', 'fa fumo', 'esce fumo',
      'pastiglie finite', 'pastiglie consumate', 'freni che fischiano', 'freni che stridono', 'freni che cigolano', 'freni consumati', 'frenata lunga',
      'sterzo duro', 'sterzo pesante', 'la macchina tira', 'l auto tira', 'tira a destra', 'tira a sinistra',
      'marce che non entrano', 'non entra la marcia', 'frizione che slitta', 'la frizione slitta', 'cambio duro',
      'clima non funziona', 'non fa freddo', 'il clima non raffredda', 'marmitta rotta', 'marmitta bucata', 'scarico rumoroso',
      'gomma a terra', 'gomma bucata', 'ho forato', 'foratura', 'consuma olio', 'ho urtato', 'ho sbattuto',
    ],
  },

  escalation_rules: {
    handoff_triggers: [
      'parlare con una persona', 'parlare con un operatore', 'parlare con qualcuno', 'parlare con un umano', 'parlare con un meccanico', 'parlare con il meccanico', 'parlare con il titolare', 'parlare con il responsabile', 'parlare con l officina', 'parlare con il capo officina', 'parlare con un tecnico',
      'sentire il meccanico', 'sentire il titolare', 'voglio una persona', 'passatemi qualcuno', 'mi passate qualcuno', 'mi passi qualcuno', 'passatemi il meccanico', 'mi passate il meccanico', 'passatemi il titolare',
      'chiamatemi', 'richiamatemi', 'mi richiamate', 'mi richiami', 'mi chiamate', 'mi chiama qualcuno', 'non sei una persona', 'sei un robot', 'sei un bot', 'sei una macchina',
      'operatore', 'persona vera', 'persona reale', 'persona in carne e ossa',
    ],
    max_unknown_turns: 2,
    sensitive_insist: 2,
    messaggio_handoff: 'Certo, passo subito la sua richiesta a una persona dell\'officina, che la ricontatterà il prima possibile.',
  },

  safety_rules: {
    sensibile: true,
    // Richieste del cliente che equivalgono a chiedere una diagnosi a distanza,
    // se si può guidare, una riparazione fai-da-te o una valutazione di gravità.
    // ("diagnosi" da sola NON è qui: è un servizio prenotabile, "fare la diagnosi con la centralina".)
    diagnosi_patterns: [
      'cosa ha la mia auto', 'cosa ha la mia macchina', 'che cos ha la mia auto', 'che cos ha la mia macchina', 'cosa ha la macchina', 'cosa ha l auto', 'che cos ha la macchina', 'che cos ha l auto',
      'che problema ha', 'che problema potrebbe essere', 'che guasto', 'quale guasto', 'cosa si e rotto', 'cosa potrebbe essere', 'cosa puo essere', 'che cosa puo essere', 'che cosa potrebbe essere', 'cosa potrebbe avere', 'cosa puo avere',
      'dimmi cosa ho', 'dimmi cosa ha', 'dimmi almeno cosa', 'cosa ho secondo te', 'secondo te cos e', 'secondo te cosa', 'secondo voi cosa', 'secondo lei cosa', 'secondo te e', 'secondo voi e', 'secondo lei e', 'sara la batteria', 'sara la frizione', 'sara la cinghia', 'sara il turbo', 'sara l alternatore',
      'e grave', 'e pericoloso', 'e pericolosa', 'e normale che', 'devo preoccuparmi', 'mi devo preoccupare', 'e preoccupante', 'e serio', 'cosa seria', 'cosa grave', 'e una cosa grave',
      'posso continuare a guidare', 'posso guidare', 'posso ancora guidare', 'si puo guidare', 'si puo ancora guidare', 'posso usare la macchina', 'posso andare avanti', 'posso arrivare fino', 'posso viaggiare', 'e sicuro guidare', 'quanto posso ancora guidare', 'quanti chilometri posso fare',
      'posso aspettare', 'posso rimandare', 'si puo aspettare', 'posso ignorare la spia',
      'posso farlo da solo', 'posso farlo io', 'posso ripararlo', 'come si ripara', 'come posso riparare', 'come si cambia', 'come posso cambiare', 'come faccio a cambiare', 'come faccio a sostituire', 'come faccio a riparare', 'come si sostituisce', 'come lo sostituisco', 'come lo cambio', 'come lo sistemo', 'come lo aggiusto', 'posso smontare', 'posso staccare la batteria', 'posso resettare', 'come resetto', 'come azzero la spia', 'azzerare la spia', 'resettare la spia', 'cancellare gli errori', 'cancellare l errore', 'spegnere la spia', 'togliere la spia',
      'dammi una diagnosi', 'fammi una diagnosi', 'diagnosi a distanza', 'diagnosi per messaggio', 'diagnosi via whatsapp', 'diagnosi da qui', 'come smontare', 'come si smonta', 'come si monta', 'come monto', 'come sostituire', 'come cambiare', 'come riparare', 'istruzioni per cambiare', 'istruzioni per riparare', 'secondo voi con', 'secondo te con', 'secondo lei con', 'cosa mi consigli', 'cosa mi consiglia', 'cosa mi consigliate', 'cosa devo fare per la spia', 'cosa devo fare con la spia',
    ],
    // Frasi che la RISPOSTA del modello non deve mai contenere (verificaRisposta).
    vietato: [
      // diagnosi e rassicurazioni
      'e sicuramente la', 'e sicuramente il', 'sara sicuramente', 'probabilmente e la', 'probabilmente e il', 'probabilmente e un', 'probabilmente sara', 'hai la frizione', 'ha la frizione', 'sara la batteria', 'sara la frizione', 'sara la cinghia',
      'non e niente', 'non e nulla', 'non e grave', 'non si preoccupi', 'non ti preoccupare', 'stia tranquillo', 'stia tranquilla', 'puo stare tranquillo', 'puo stare tranquilla', 'non c e pericolo', 'nessun pericolo', 'non e pericoloso', 'puo aspettare', 'puoi aspettare', 'puo andare avanti', 'puoi andare avanti', 'puo proseguire', 'guidare tranquillamente', 'guidare senza problemi', 'puo guidare senza',
      // fai-da-te
      'smonti', 'smontare', 'svita', 'svitare', 'stacchi la batteria', 'stacca la batteria', 'scolleghi la batteria', 'scollega la batteria', 'azzeri la spia', 'azzera la spia', 'resetti la spia', 'resetta la spia', 'rabbocchi', 'rabbocca', 'sostituisca lei', 'sostituisci tu', 'cambi lei', 'cambia tu',
      // stime di costo e di tempo, promozioni, claim sul tenant
      'costera circa', 'costa circa', 'dovrebbe costare', 'verra circa', 'spenderebbe circa', 'sara pronta', 'sara pronto', 'pronta in giornata', 'pronto in giornata', 'pronta domani', 'pronto domani', 'pronta entro', 'pronto entro', 'ci vogliono', 'ci vorranno', 'ci vorra', 'ci vuole circa', 'un paio d ore', 'in giornata',
      'gratis', 'gratuito', 'gratuita', 'in omaggio', 'tutte le marche', 'tutti i marchi', 'tutti i modelli', 'officina autorizzata', 'concessionaria ufficiale',
      'mg', 'milligrammi',
    ],
    messaggio_sicurezza: 'Non posso stabilire a distanza cosa abbia l\'auto, se sia sicuro guidarla o come ripararla: serve il meccanico, che può controllarla. Se avverte freni diversi dal solito, fumo, odore di bruciato o spie rosse non guidi e chiami il soccorso stradale. Se vuole, la aiuto subito a fissare un controllo in officina.',
    messaggio_emergenza: 'Capisco, la situazione può essere pericolosa. Se è alla guida, rallenti con prudenza, si fermi appena può in sicurezza, spenga il motore e non riparta; se vede fumo o fiamme o sente odore di carburante o di gas si allontani dall\'auto. Se ci sono feriti o un pericolo immediato chiami subito il 112, per il carro attrezzi il soccorso stradale. Avviso immediatamente l\'officina.',
  },

  response_rules: { max_frasi: 3, una_domanda_per_messaggio: true, emoji: 'mai' },

  default_questions: {
    servizio: ['Di che intervento ha bisogno: un tagliando, la revisione, o altro?', 'Mi dice che lavoro vorrebbe fare sull\'auto?', 'Per cosa vorrebbe portare l\'auto?'],
    nome_cliente: ['Come si chiama?', 'Mi dice il suo nome, così preparo la richiesta?', 'A che nome registro la richiesta?'],
    sintomo: ['Mi racconta che problema sta avendo con l\'auto?', 'Che cosa succede, esattamente? Un rumore, una spia, altro?', 'Può descrivermi brevemente il problema?'],
    marca: ['Che auto ha? Mi dice marca e modello?', 'Di che marca e modello è l\'auto?'],
  },

  common_scenarios: [
    'Tagliando, revisione o cambio olio con prenotazione e raccolta di nome e auto',
    'Rumore, spia o problema all\'auto con raccolta dati e priorità',
    'Pericolo (freni, sterzo, fumo, carburante, spie rosse, perdite, incidente): invito a non guidare e passaggio rapido all\'officina',
    'Domande su prezzi, orari, auto sostitutiva, pagamenti: solo da dati del tenant',
    'Richieste di diagnosi a distanza, di poter guidare o di riparazione fai-da-te: risposta di sicurezza e proposta di controllo',
    'Stato dell\'auto in officina, spostamenti, annullamenti, reclami: passaggio a una persona',
  ],

  confidence_thresholds: { intent_min: 0.55, intent_ok: 0.8 },
};

// FAQ di SETTORE: conoscenza generale, valida per qualunque officina. Nessun
// prezzo, orario, tempo di lavorazione, marchio trattato, nome o indirizzo:
// quelli stanno solo nei dati del tenant.
const f = (intent, domanda_canonica, varianti, risposta_base) => ({ intent, domanda_canonica, varianti, risposta_base, condizioni: {} });

export const faq = [
  f('info_interventi', 'Cos\'è il tagliando?', ['cosa e il tagliando', 'cos e il tagliando', 'cosa comprende il tagliando', 'a cosa serve il tagliando', 'in cosa consiste il tagliando', 'cosa si fa nel tagliando'],
    'Il tagliando è la manutenzione periodica prevista dal costruttore: in genere comprende il cambio dell\'olio e dei filtri e una serie di controlli sull\'auto, con il programma indicato nel libretto di uso e manutenzione. Cosa viene fatto esattamente dipende dal modello e dai chilometri o dagli anni dell\'auto.'),
  f('info_interventi', 'Ogni quanto si fa il tagliando?', ['ogni quanto si fa il tagliando', 'ogni quanto va fatto il tagliando', 'quando va fatto il tagliando', 'quando si fa il tagliando', 'ogni quanto devo fare il tagliando', 'come faccio a sapere quando fare il tagliando'],
    'La scadenza è indicata dal costruttore nel libretto di uso e manutenzione: di solito si considera il primo limite raggiunto tra chilometri percorsi e tempo trascorso dall\'ultimo tagliando. Su alcune auto una spia sul cruscotto segnala la scadenza.'),
  f('info_interventi', 'Che differenza c\'è tra tagliando e revisione?', ['differenza tra tagliando e revisione', 'differenza tra revisione e tagliando', 'tagliando e revisione sono la stessa cosa', 'il tagliando e la revisione sono uguali', 'che differenza c e tra tagliando e revisione'],
    'Sono due cose diverse: il tagliando è la manutenzione periodica per mantenere l\'auto in buono stato, mentre la revisione è un controllo obbligatorio per legge che verifica sicurezza ed emissioni per poter circolare. Il tagliando non sostituisce la revisione e viceversa.'),
  f('info_interventi', 'Ogni quanto si fa la revisione?', ['ogni quanto si fa la revisione', 'ogni quanto va fatta la revisione', 'quando scade la revisione', 'quando devo fare la revisione', 'quando si fa la prima revisione', 'ogni quanto la revisione dell auto'],
    'Per le auto private la prima revisione si fa in genere dopo quattro anni dall\'immatricolazione e poi ogni due anni. La scadenza precisa si legge sulla carta di circolazione o sul tagliando adesivo dell\'ultima revisione.'),
  f('info_interventi', 'Cosa serve per fare la revisione?', ['cosa serve per la revisione', 'che documenti servono per la revisione', 'cosa devo portare per la revisione', 'cosa serve per fare la revisione'],
    'In genere serve la carta di circolazione dell\'auto. Per eventuali altre indicazioni conviene verificare con l\'officina prima di portare l\'auto.'),
  f('info_interventi', 'Cos\'è la pre-revisione?', ['cos e la pre revisione', 'cosa e la pre revisione', 'cosa significa pre revisione', 'a cosa serve la pre revisione', 'serve la pre revisione', 'cos e il controllo prima della revisione'],
    'La pre-revisione è un controllo che si fa prima della revisione ufficiale per verificare gli aspetti che di solito vengono esaminati, come freni, luci, pneumatici e emissioni, così da sistemare in anticipo eventuali problemi. Non è obbligatoria e non sostituisce la revisione.'),
  f('info_interventi', 'Cosa si controlla in un controllo generale dell\'auto?', ['cosa si controlla in un controllo generale', 'cosa controllate nel controllo dell auto', 'cosa comprende il controllo completo', 'cosa si controlla prima di un viaggio'],
    'Un controllo generale riguarda di norma elementi come livelli dei liquidi, freni, luci, pneumatici, batteria e stato visibile di cinghie e componenti. L\'elenco preciso dipende dall\'officina e dall\'auto.'),
  f('info_interventi', 'Ogni quanto si cambia l\'olio motore?', ['ogni quanto si cambia l olio', 'ogni quanto va cambiato l olio', 'ogni quanto devo cambiare l olio', 'quando si cambia l olio', 'ogni quanto si fa il cambio olio'],
    'L\'intervallo dipende dal motore, dal tipo di olio e da come si usa l\'auto (molti tragitti brevi, città, autostrada): è indicato dal costruttore nel libretto di uso e manutenzione, e di solito il cambio olio si fa insieme al tagliando.'),
  f('info_interventi', 'Cosa significa la spia motore?', ['cosa significa la spia motore', 'cosa vuol dire la spia motore', 'a cosa serve la spia motore', 'cosa significa la spia del motore', 'cosa indica la spia motore', 'cos e la spia motore'],
    'La spia motore si accende quando la centralina rileva un\'anomalia, che può avere cause molto diverse. Per capire quale serve una lettura con la strumentazione diagnostica e il parere del meccanico. Se la spia lampeggia o è rossa, o se l\'auto si comporta in modo strano, è meglio non proseguire e contattare l\'officina.'),
  f('info_interventi', 'Cosa significa la spia dell\'olio?', ['cosa significa la spia dell olio', 'cosa vuol dire la spia dell olio', 'a cosa serve la spia dell olio', 'cosa indica la spia dell olio', 'cos e la spia dell olio'],
    'La spia dell\'olio segnala un problema legato alla pressione o al livello dell\'olio del motore. Se si accende in marcia è una situazione da non sottovalutare: conviene fermarsi appena possibile in sicurezza, non proseguire e contattare l\'officina o il soccorso stradale.'),
  f('info_interventi', 'Cosa significa la spia dell\'airbag?', ['cosa significa la spia dell airbag', 'cosa vuol dire la spia airbag', 'a cosa serve la spia airbag', 'cosa indica la spia airbag', 'spia airbag accesa cosa significa'],
    'La spia dell\'airbag segnala che il sistema di sicurezza ha rilevato un\'anomalia e potrebbe non funzionare correttamente in caso di incidente. Serve un controllo con strumentazione adatta da parte dell\'officina.'),
  f('info_interventi', 'Cosa devo fare se si accende una spia in viaggio?', ['cosa devo fare se si accende una spia', 'cosa fare se si accende una spia', 'che significano i colori delle spie', 'spia rossa o gialla cosa cambia', 'si accende una spia cosa faccio'],
    'In genere le spie rosse indicano un problema importante: conviene accostare in sicurezza e non proseguire. Quelle gialle o arancioni segnalano un\'anomalia da far controllare. Il significato di ogni spia è nel libretto di uso e manutenzione; per qualsiasi dubbio è meglio sentire l\'officina.'),
  f('info_interventi', 'Cos\'è la diagnosi con la centralina?', ['cos e la diagnosi', 'a cosa serve la diagnosi', 'cos e la diagnosi con la centralina', 'come funziona la diagnosi elettronica', 'cosa e la diagnosi computerizzata', 'a cosa serve leggere la centralina'],
    'La diagnosi elettronica consiste nel collegare uno strumento alla centralina dell\'auto per leggere gli errori memorizzati. Serve a capire in quale area cercare il problema, ma l\'interpretazione e le verifiche successive le fa il meccanico.'),
  f('info_interventi', 'Ogni quanto si cambiano le pastiglie dei freni?', ['ogni quanto si cambiano le pastiglie', 'quando si cambiano le pastiglie dei freni', 'ogni quanto vanno cambiate le pastiglie', 'quando vanno cambiate le pastiglie', 'quando si cambiano i dischi dei freni'],
    'Dipende molto dal tipo di guida, dal percorso e dal peso dell\'auto, quindi non c\'è una scadenza fissa. L\'usura si verifica con un controllo in officina, che è il modo sicuro per sapere quando intervenire.'),
  f('info_interventi', 'Cos\'è il liquido dei freni e va cambiato?', ['cos e il liquido freni', 'va cambiato il liquido dei freni', 'ogni quanto si cambia il liquido dei freni', 'a cosa serve il liquido dei freni', 'il liquido freni scade'],
    'Il liquido dei freni trasmette la forza del pedale all\'impianto frenante e con il tempo assorbe umidità, perdendo efficacia. Per questo il costruttore ne prevede la sostituzione periodica, indicata nel libretto di uso e manutenzione.'),
  f('info_interventi', 'Ogni quanto si cambia la cinghia di distribuzione?', ['ogni quanto si cambia la cinghia di distribuzione', 'quando va cambiata la cinghia di distribuzione', 'ogni quanto va sostituita la distribuzione', 'quando si cambia la distribuzione', 'a cosa serve la cinghia di distribuzione'],
    'La distribuzione sincronizza i movimenti del motore e va sostituita secondo gli intervalli di chilometri o di anni indicati dal costruttore, che cambiano da modello a modello. Rispettare la scadenza è importante perché una rottura può danneggiare seriamente il motore.'),
  f('info_interventi', 'Ogni quanto si cambiano le candele?', ['ogni quanto si cambiano le candele', 'quando si cambiano le candele', 'a cosa servono le candele', 'ogni quanto vanno cambiate le candele', 'quando si cambia la batteria dell auto'],
    'Le candele (nei motori a benzina) vanno sostituite secondo il piano del costruttore, che dipende dal tipo di candela e di motore. Di solito il controllo e l\'eventuale sostituzione rientrano nel tagliando.'),
  f('info_interventi', 'Quanto dura la batteria dell\'auto?', ['quanto dura la batteria', 'quanto dura la batteria dell auto', 'ogni quanto si cambia la batteria', 'quando va cambiata la batteria', 'ogni quanto va sostituita la batteria'],
    'La durata della batteria dipende dall\'uso (tragitti brevi, freddo, accessori accesi) e dall\'età. Un controllo in officina permette di verificare lo stato di carica e di salute prima che l\'auto non parta.'),
  f('info_interventi', 'A cosa serve la ricarica del clima?', ['a cosa serve la ricarica del clima', 'ogni quanto si ricarica il clima', 'ogni quanto si ricarica l aria condizionata', 'perche il clima non raffredda piu', 'cos e la sanificazione del clima', 'quando si ricarica il clima'],
    'Con il tempo l\'impianto di climatizzazione può perdere efficienza e l\'abitacolo può avere cattivi odori: un controllo periodico, con ricarica o sanificazione quando necessarie, aiuta a mantenerlo efficiente. Se il clima non raffredda, serve un controllo per capirne la causa.'),
  f('info_interventi', 'Cos\'è l\'equilibratura e la convergenza?', ['cos e la convergenza', 'cos e l equilibratura', 'a cosa serve l equilibratura', 'a cosa serve la convergenza', 'cos e l assetto', 'cosa significa convergenza'],
    'L\'equilibratura bilancia le ruote per evitare vibrazioni al volante; la convergenza (o assetto) regola l\'allineamento delle ruote per una guida stabile e un consumo uniforme degli pneumatici. Se l\'auto tira da un lato o il volante vibra, serve un controllo in officina.'),
  f('info_interventi', 'Quando vanno cambiate le gomme?', ['quando si cambiano le gomme', 'ogni quanto si cambiano le gomme', 'quando si montano le gomme invernali', 'gomme invernali obbligatorie', 'quando cambiare i pneumatici'],
    'Le gomme vanno sostituite quando il battistrada è consumato oltre il limite di legge o quando sono danneggiate o invecchiate; un controllo in officina o dal gommista lo verifica. In alcuni periodi dell\'anno e su certe strade è previsto l\'obbligo di pneumatici invernali o catene a bordo: i periodi sono indicati dalla segnaletica o dalle ordinanze.'),
  f('info_interventi', 'A cosa servono gli ammortizzatori?', ['a cosa servono gli ammortizzatori', 'quando si cambiano gli ammortizzatori', 'ogni quanto si cambiano gli ammortizzatori', 'cosa fanno gli ammortizzatori'],
    'Gli ammortizzatori mantengono le ruote a contatto con la strada e contribuiscono a stabilità e frenata. Si usurano nel tempo: se l\'auto rimbalza o balla in curva, serve un controllo in officina.'),
  f('info_interventi', 'Cos\'è il FAP o filtro antiparticolato?', ['cos e il fap', 'cos e il filtro antiparticolato', 'a cosa serve il fap', 'cosa e il dpf', 'cos e il dpf', 'che cos e il fap'],
    'Il filtro antiparticolato (FAP o DPF) è presente su molte auto diesel e trattiene le particelle inquinanti dei gas di scarico, per poi bruciarle durante la rigenerazione. Se una spia lo segnala serve un controllo in officina: non va rimosso, è parte dell\'impianto di scarico omologato.'),
  f('info_interventi', 'Si fa il tagliando anche sulle auto ibride o elettriche?', ['si fa il tagliando anche sulle ibride', 'serve il tagliando sulle auto elettriche', 'tagliando auto ibrida', 'tagliando auto elettrica', 'le auto elettriche hanno il tagliando'],
    'Sì, anche le auto ibride ed elettriche hanno una manutenzione programmata dal costruttore, con controlli su freni, sospensioni, pneumatici e sistemi specifici. Se un\'officina sia attrezzata per questi veicoli lo può dire solo l\'officina stessa.'),
  f('info_interventi', 'Se faccio il tagliando fuori dalla casa madre perdo la garanzia?', ['perdo la garanzia se faccio il tagliando fuori dalla casa', 'tagliando in officina indipendente garanzia', 'il tagliando fuori concessionaria fa decadere la garanzia', 'garanzia e tagliando in officina', 'posso fare il tagliando in una officina non ufficiale'],
    'In genere la garanzia del costruttore non decade solo perché la manutenzione è eseguita in un\'officina indipendente, se si rispettano il piano del costruttore e ricambi adeguati. Per il suo caso specifico conviene verificare le condizioni scritte nel contratto di garanzia.'),
  f('info_interventi', 'Che informazioni servono per un preventivo?', ['che informazioni servono per un preventivo', 'cosa serve per un preventivo', 'cosa devo dirvi per il preventivo', 'cosa vi serve per fare un preventivo', 'cosa serve sapere per il preventivo'],
    'Per preparare un preventivo all\'officina servono di solito marca, modello, anno, alimentazione e chilometri dell\'auto, la targa e una descrizione chiara del lavoro o del problema. Il preventivo definitivo lo formula l\'officina, spesso dopo aver visto l\'auto.'),
  f('info_interventi', 'Quanto tempo ci vuole per un intervento?', ['quanto tempo ci vuole per un tagliando', 'quanto dura il tagliando', 'quanto ci vuole per la revisione', 'quanto tempo ci vuole per la riparazione', 'in quanto tempo si fa un intervento', 'quanto tempo serve per la riparazione'],
    'I tempi dipendono dal tipo di intervento, dal modello dell\'auto, dalla disponibilità dei ricambi e dal carico di lavoro dell\'officina, quindi non è possibile indicarli in modo generale. L\'officina può darle un\'indicazione concreta una volta definito il lavoro.'),
];
