// lib/engine/packs/dentista.js
//
// Sector Pack "dentista" v1 — conoscenza di SETTORE (non di un singolo
// studio). Prezzi, orari, servizi offerti, personale e indirizzo non stanno
// qui: arrivano solo dai dati del tenant. Questo file è la sorgente
// versionata in git; viene caricata in sector_profiles tramite
// scripts/pubblica-pack.js e promossa a 'production' solo dopo che la
// valutazione (lib/engine/evaluate.js) supera il gate.

export const SETTORE = 'dentista';
export const VERSIONE = 1;
export const CHANGELOG = 'v1: primo Sector Pack completo — lessico clinico/prenotazione, 16 intent, 12 entità, regole urgenza LOW-CRITICAL, sicurezza anti-diagnosi, 24 FAQ di settore.';

export const pack = {
  identity: {
    nome_ruolo: 'studio dentistico',
    entita_nome: 'nome_paziente',
    descrizione: 'Sei l\'assistente digitale di uno studio dentistico. Accogli i pazienti con tono professionale, rassicurante e chiaro; gestisci richieste di appuntamento, informazioni e urgenze. Non sei un dentista: non fai diagnosi, non consigli terapie né farmaci.',
  },
  mission: 'Capire cosa serve al paziente, raccogliere solo le informazioni necessarie, organizzare l\'appuntamento e far arrivare subito allo staff le situazioni urgenti.',
  tone_default: 'professionale',
  conversation_rules: [
    'Messaggi brevi (2-3 frasi), linguaggio semplice, niente tecnicismi inutili.',
    'Con chi ha dolore o paura: prima una frase di vicinanza, poi la domanda.',
    'Per i bambini rivolgiti al genitore.',
    'Una sola domanda per messaggio e mai su un\'informazione già data.',
    'Mai diagnosi, mai indicazioni su farmaci o dosaggi, mai valutazioni cliniche ("non è niente", "è sicuramente una carie").',
  ],
  prohibited_claims: [
    'dire al paziente cosa ha o che cosa è un sintomo',
    'consigliare farmaci, antibiotici, antidolorifici o dosaggi',
    'garantire esiti, risultati o assenza di dolore',
    'dire che un sintomo non è grave o che si può aspettare',
    'indicare prezzi, sconti, orari o disponibilità non presenti nelle fonti',
  ],
  business_rules: [
    'Annullamenti e spostamenti di appuntamenti esistenti vanno passati allo staff.',
    'Le urgenze (dolore forte, trauma, gonfiore, sanguinamento) hanno priorità sulla raccolta dati normale.',
  ],

  entities: [
    { id: 'servizio', descrizione: 'Il trattamento o tipo di visita richiesto.', tipo: 'enum', priorita: 10,
      valori: ['prima_visita', 'controllo', 'igiene_dentale', 'sbiancamento', 'otturazione', 'devitalizzazione', 'estrazione', 'impianto', 'protesi', 'ortodonzia', 'urgenza_dentale', 'altro'],
      domanda_varianti: ['Che tipo di visita o trattamento le serve?', 'Di cosa avrebbe bisogno: una visita di controllo, l\'igiene, o altro?', 'Mi dica pure per cosa vorrebbe venire.'] },
    { id: 'nome_paziente', descrizione: 'Nome del paziente (o di chi viene visitato).', tipo: 'string', priorita: 20,
      domanda_varianti: ['Come si chiama?', 'Mi dice il suo nome, così preparo la richiesta?', 'A che nome registro l\'appuntamento?'] },
    { id: 'sintomo', descrizione: 'Il problema o disturbo che il paziente descrive.', tipo: 'string', priorita: 15,
      domanda_varianti: ['Mi racconta che problema sta avendo?', 'Che cosa le dà fastidio, esattamente?', 'Può descrivermi brevemente il disturbo?'] },
    { id: 'urgenza', descrizione: 'Intensità del dolore: forte o gestibile.', tipo: 'enum', priorita: 25, valori: ['forte', 'gestibile'],
      domanda_varianti: ['Il dolore è forte o riesce a sopportarlo?', 'Il fastidio è intenso oppure gestibile?'] },
    { id: 'dente', descrizione: 'Quale dente o zona della bocca è interessata.', tipo: 'string', priorita: 40 },
    { id: 'durata_problema', descrizione: 'Da quanto tempo c\'è il problema.', tipo: 'string', priorita: 45 },
    { id: 'giorno', descrizione: 'Giorno preferito per l\'appuntamento.', tipo: 'string', priorita: 60 },
    { id: 'fascia_oraria', descrizione: 'Mattina, pomeriggio o sera.', tipo: 'enum', priorita: 61, valori: ['mattina', 'pomeriggio', 'sera'] },
    { id: 'prima_visita', descrizione: 'Se è la prima volta che il paziente viene nello studio.', tipo: 'enum', priorita: 50, valori: ['si', 'no'] },
    { id: 'tipo_paziente', descrizione: 'Adulto o bambino.', tipo: 'enum', priorita: 55, valori: ['adulto', 'bambino'] },
    { id: 'assicurazione', descrizione: 'Convenzione, fondo sanitario o assicurazione indicata dal paziente.', tipo: 'string', priorita: 70 },
    { id: 'telefono', descrizione: 'Numero di telefono se il paziente lo fornisce (di norma già noto da WhatsApp).', tipo: 'string', priorita: 99 },
  ],

  lexicon: [
    // ---- Servizi ----
    { canonical: 'igiene_dentale', entity: 'servizio', value: 'igiene_dentale', synonyms: ['igiene', 'igiene orale', 'pulizia dei denti', 'pulizia denti', 'pulizia', 'pulizia professionale', 'detartrasi', 'ablazione tartaro', 'ablazione del tartaro', 'togliere il tartaro', 'rimuovere il tartaro', 'seduta di igiene', 'pulire i denti'], slang: ['pulitina'], errors: ['igene', 'pulizzia'] },
    { canonical: 'prima_visita', entity: 'servizio', value: 'prima_visita', synonyms: ['prima visita', 'primo appuntamento', 'visita iniziale', 'primo controllo', 'prima consulenza', 'visita conoscitiva'] },
    { canonical: 'controllo', entity: 'servizio', value: 'controllo', synonyms: ['controllo', 'controllo dei denti', 'visita di controllo', 'check up', 'checkup', 'controllo semestrale', 'controllo annuale', 'controllare i denti', 'dare un occhiata ai denti', 'visita odontoiatrica'] },
    { canonical: 'sbiancamento', entity: 'servizio', value: 'sbiancamento', synonyms: ['sbiancamento', 'sbiancare', 'sbiancare i denti', 'denti piu bianchi', 'whitening', 'sbiancante'] },
    { canonical: 'otturazione', entity: 'servizio', value: 'otturazione', synonyms: ['otturazione', 'otturare', 'otturazioni', 'ricostruzione del dente', 'curare la carie', 'curare una carie', 'composito'] },
    { canonical: 'devitalizzazione', entity: 'servizio', value: 'devitalizzazione', synonyms: ['devitalizzazione', 'devitalizzare', 'cura canalare', 'terapia canalare', 'canalare', 'endodonzia', 'togliere il nervo', 'nervo del dente', 'ritrattamento canalare'] },
    { canonical: 'estrazione', entity: 'servizio', value: 'estrazione', synonyms: ['estrazione', 'estrarre un dente', 'togliere un dente', 'togliere il dente', 'cavare un dente', 'cavare il dente', 'dente del giudizio', 'denti del giudizio', 'giudizio'] },
    { canonical: 'impianto', entity: 'servizio', value: 'impianto', synonyms: ['impianto', 'impianti', 'impianto dentale', 'impianti dentali', 'dente finto', 'dente fisso', 'vite nel dente', 'implantologia'] },
    { canonical: 'protesi', entity: 'servizio', value: 'protesi', synonyms: ['protesi', 'corona', 'corone', 'capsula', 'capsule', 'dentiera', 'ponte dentale', 'faccette', 'protesi dentale'] },
    { canonical: 'ortodonzia', entity: 'servizio', value: 'ortodonzia', synonyms: ['ortodonzia', 'apparecchio', 'apparecchio per i denti', 'apparecchio ai denti', 'invisalign', 'allineatori', 'mascherine trasparenti', 'raddrizzare i denti', 'denti storti', 'aligner'] },
    { canonical: 'urgenza_dentale', entity: 'servizio', value: 'urgenza_dentale', synonyms: ['urgenza', 'urgenza dentale', 'emergenza dentale', 'pronto soccorso dentale', 'visita urgente'], intent: 'urgenza_dentale' },

    // ---- Tipo paziente / prima visita ----
    { canonical: 'paziente_bambino', entity: 'tipo_paziente', value: 'bambino', synonyms: ['mio figlio', 'mia figlia', 'il bambino', 'la bambina', 'bimbo', 'bimba', 'mio nipote', 'pedodonzia', 'dentista per bambini', 'mio figlio piccolo', 'i miei figli'] },
    { canonical: 'paziente_nuovo', entity: 'prima_visita', value: 'si', synonyms: ['sono nuovo', 'sono nuova', 'prima volta che vengo', 'non sono mai venuto', 'non sono mai venuta', 'non sono mai stato da voi', 'non sono mai stata da voi', 'non vi conosco', 'sono un nuovo paziente', 'e la prima volta', 'prima volta da voi', 'prima volta in uno studio'] },
    { canonical: 'paziente_esistente', entity: 'prima_visita', value: 'no', synonyms: ['sono gia paziente', 'sono gia venuto', 'sono gia venuta', 'sono gia stato da voi', 'sono gia stata da voi', 'sono un vostro paziente', 'sono una vostra paziente', 'sono vostro paziente'] },

    // ---- Sintomi ----
    { canonical: 'dolore', entity: 'sintomo', value: 'dolore', negabile: true, synonyms: ['mal di denti', 'mal di dente', 'dolore', 'mi fa male', 'male al dente', 'dente che fa male', 'dolorante', 'dolori', 'fitta', 'fitte', 'mi duole'], intent: 'problema_sintomo' },
    { canonical: 'dolore_forte', entity: 'urgenza', value: 'forte', negabile: true, synonyms: ['dolore forte', 'dolore fortissimo', 'dolore insopportabile', 'male cane', 'malissimo', 'un dolore atroce', 'non resisto al dolore', 'mi fa un male terribile'] },
    { canonical: 'dolore_gestibile', entity: 'urgenza', value: 'gestibile', negabile: true, synonyms: ['dolore lieve', 'dolore sopportabile', 'dolore gestibile', 'un po di fastidio', 'fastidio', 'si sopporta', 'gestibile', 'sopportabile'] },
    { canonical: 'gonfiore', entity: 'sintomo', value: 'gonfiore', negabile: true, synonyms: ['gonfiore', 'gengiva gonfia', 'guancia gonfia', 'faccia gonfia', 'viso gonfio', 'mi si e gonfiata la guancia', 'gonfio'], intent: 'problema_sintomo' },
    { canonical: 'sanguinamento', entity: 'sintomo', value: 'sanguinamento', negabile: true, synonyms: ['sanguina', 'sanguinamento', 'sanguinano', 'sangue dalle gengive', 'perdo sangue', 'sanguinare'], intent: 'problema_sintomo' },
    { canonical: 'sensibilita', entity: 'sintomo', value: 'sensibilita', negabile: true, synonyms: ['sensibilita', 'sensibile al freddo', 'sensibile al caldo', 'dente sensibile', 'denti sensibili', 'fitte al freddo', 'fastidio al freddo'], intent: 'problema_sintomo' },
    { canonical: 'dente_rotto', entity: 'sintomo', value: 'dente_rotto', synonyms: ['dente rotto', 'dente scheggiato', 'dente spezzato', 'si e rotto un dente', 'mi si e rotto un dente', 'mi si e scheggiato un dente', 'si e scheggiato un dente', 'si e scheggiato il dente', 'si e rotto il dente', 'ho scheggiato un dente', 'scheggia', 'dente crepato', 'ho rotto un dente'], intent: 'problema_sintomo' },
    { canonical: 'otturazione_saltata', entity: 'sintomo', value: 'otturazione_saltata', synonyms: ['otturazione saltata', 'mi e caduta l otturazione', 'mi e caduta un otturazione', 'mi e caduta una otturazione', 'e caduta un otturazione', 'mi e caduto un otturazione', 'otturazione caduta', 'otturazione persa', 'mi e uscita l otturazione', 'e saltata l otturazione', 'mi e saltata l otturazione', 'mi e saltata un otturazione', 'mi e saltato un otturazione'], intent: 'problema_sintomo' },
    { canonical: 'carie', entity: 'sintomo', value: 'carie', synonyms: ['carie', 'buco nel dente', 'buco in un dente', 'buco in un molare', 'buchino nel dente', 'dente cariato', 'denti cariati'], intent: 'problema_sintomo' },
    { canonical: 'ascesso', entity: 'sintomo', value: 'ascesso', synonyms: ['ascesso', 'ascessi', 'pus', 'fistola', 'ascesso dentale'], intent: 'urgenza_dentale' },
    { canonical: 'alitosi', entity: 'sintomo', value: 'alitosi', synonyms: ['alitosi', 'alito cattivo', 'alito pesante', 'cattivo odore dalla bocca'], intent: 'problema_sintomo' },
    { canonical: 'gengive', entity: 'sintomo', value: 'gengive', synonyms: ['gengivite', 'piorrea', 'parodontite', 'gengive infiammate', 'gengive arrossate', 'gengive che si ritirano'], intent: 'problema_sintomo' },

    // ---- Concetti di conversazione (collegano all'intent, nessuna entità) ----
    { canonical: 'prezzo', synonyms: ['prezzo', 'prezzi', 'costo', 'costi', 'quanto costa', 'quanto viene', 'quanto devo pagare', 'tariffa', 'tariffe', 'listino', 'quanto si paga', 'quanto prendete'], intent: 'info_prezzi' },
    { canonical: 'orari', synonyms: ['orari', 'orario', 'aperti', 'aperto', 'chiusi', 'apertura', 'chiusura', 'fino a che ora', 'a che ora aprite', 'a che ora chiudete'], intent: 'info_orari' },
    { canonical: 'indirizzo', synonyms: ['indirizzo', 'dove siete', 'dove si trova', 'come vi raggiungo', 'come arrivo', 'parcheggio', 'posizione', 'via'], intent: 'info_posizione' },
    { canonical: 'pagamento', synonyms: ['pagamento', 'pagamenti', 'rate', 'rateale', 'rateizzazione', 'finanziamento', 'bancomat', 'carta di credito', 'carte', 'contanti', 'fattura'], intent: 'info_pagamenti' },
    { canonical: 'assicurazione', entity: 'assicurazione', value: 'indicata', synonyms: ['assicurazione', 'convenzione', 'convenzioni', 'convenzionati', 'fondo sanitario', 'polizza', 'mutua', 'welfare aziendale'], intent: 'info_pagamenti' },
    { canonical: 'fastidio_dente', synonyms: ['molare', 'molari', 'premolare', 'incisivo', 'canino', 'dente del giudizio', 'denti del giudizio', 'mi da fastidio', 'mi dà fastidio'], intent: 'problema_sintomo' },
    { canonical: 'preventivo', synonyms: ['preventivo', 'preventivi', 'stima dei costi', 'stima del costo', 'stima di spesa', 'stima', 'piano di cura', 'piano di trattamento'], intent: 'richiesta_preventivo' },
    { canonical: 'appuntamento', synonyms: ['appuntamento', 'prenotare', 'prenotazione', 'fissare', 'disponibilita', 'posto libero', 'slot'], intent: 'prenota_visita' },
  ],

  intents: [
    { id: 'prenota_visita', nome: 'Prenotazione appuntamento', categoria: 'BOOKING', priorita: 20, safety_level: 'LOW',
      descrizione: 'Il paziente vuole fissare un appuntamento o chiede disponibilità.',
      esempi: ['vorrei prenotare', 'vorrei un appuntamento', 'vorrei prendere un appuntamento', 'vorrei fissare un appuntamento', 'avete posto domani', 'avete un posto oggi', 'avete disponibilita', 'avete disponibilita questa settimana', 'posso venire venerdi', 'posso prenotare', 'mi serve una visita', 'quando siete liberi', 'prenotazione', 'cerco un appuntamento', 'avete un buco', 'posso passare domani', 'vorrei venire da voi', 'vorrei una visita', 'posso venire'],
      keywords: ['prenotare', 'prenotazione', 'appuntamento', 'disponibilita', 'fissare'],
      combinazioni: [
        { entity: 'servizio', con: ['vorrei', 'mi serve', 'mi servirebbe', 'avrei bisogno', 'ho bisogno', 'devo fare', 'devo fissare', 'vorrei fare', 'voglio fare', 'mi occorre', 'cerco', 'posso venire', 'posso passare', 'vorrei venire', 'mi serve una', 'volevo fare', 'solo un', 'solo una', 'dovrei', 'dovrei fare', 'quando potete', 'quando riuscite'], con_entities: ['giorno', 'fascia_oraria'], non_con_concepts: ['preventivo', 'prezzo'], score: 0.8 },
        { entity: 'prima_visita', con: ['vorrei una visita', 'vorrei una visita', 'mi serve una visita', 'vorrei venire', 'visita'], score: 0.8 },
        { entity: 'tipo_paziente', con: ['visita', 'controllo', 'appuntamento', 'bisogno'], score: 0.7 },
      ],
      required_entities: ['servizio', 'nome_paziente'], optional_entities: ['giorno', 'fascia_oraria', 'prima_visita', 'tipo_paziente', 'assicurazione'],
      actions: ['ask_missing_information', 'propose_slot', 'create_booking', 'create_lead'] },
    { id: 'richiesta_preventivo', nome: 'Richiesta preventivo', categoria: 'LEAD', priorita: 25, safety_level: 'LOW',
      descrizione: 'Il paziente chiede un preventivo o una stima per un trattamento.',
      esempi: ['vorrei un preventivo', 'mi fate un preventivo', 'preventivo per un impianto', 'vorrei sapere il costo di tutto il piano di cura', 'mi serve un preventivo', 'quanto verrebbe un preventivo', 'una stima dei costi', 'potete farmi una stima', 'stima del costo', 'quanto mi costerebbe in tutto'],
      keywords: ['preventivo', 'preventivi'],
      required_entities: ['servizio', 'nome_paziente'], optional_entities: ['tipo_paziente', 'assicurazione'],
      actions: ['ask_missing_information', 'create_lead', 'notify_owner'] },
    { id: 'problema_sintomo', nome: 'Disturbo o sintomo', categoria: 'SUPPORT', priorita: 15, safety_level: 'MEDIUM', campi_tenant: true,
      descrizione: 'Il paziente descrive un problema ai denti o alla bocca (non necessariamente urgente).',
      esempi: ['mi fa male un dente', 'ho un dente che mi da fastidio', 'ho mal di denti', 'mi sanguinano le gengive', 'ho sensibilita al freddo', 'mi e caduta una otturazione', 'si e scheggiato un dente', 'ho un buco in un dente', 'ho un problema ai denti'],
      keywords: ['mal di denti', 'mal di dente', 'dente'],
      required_entities: ['sintomo', 'nome_paziente'], optional_entities: ['dente', 'durata_problema', 'urgenza', 'giorno', 'fascia_oraria', 'prima_visita'],
      actions: ['ask_missing_information', 'propose_slot', 'notify_owner', 'create_lead'] },
    { id: 'urgenza_dentale', nome: 'Urgenza dentale', categoria: 'EMERGENCY', priorita: 5, safety_level: 'HIGH',
      descrizione: 'Dolore forte, trauma, gonfiore importante, ascesso, sanguinamento: serve contatto rapido con lo studio.',
      esempi: ['ho un dolore fortissimo', 'ho un mal di denti insopportabile', 'ho preso una botta in bocca', 'mi si e staccato un dente', 'ho la faccia gonfia', 'ho un ascesso', 'sanguina e non si ferma', 'devo essere visto subito', 'e urgente', 'ho un emergenza dentale'],
      keywords: ['urgente', 'urgenza', 'emergenza', 'subito'],
      required_entities: ['nome_paziente'], optional_entities: ['sintomo', 'dente', 'durata_problema'],
      actions: ['ask_missing_information', 'notify_owner', 'emergency_escalation'] },
    { id: 'info_prezzi', nome: 'Informazioni prezzi', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il paziente chiede quanto costa un trattamento o una visita.',
      esempi: ['quanto costa', 'che prezzo avete', 'quanto viene', 'quanto devo pagare', 'mi dici il costo', 'avete un listino', 'quali sono i prezzi', 'quanto costa una visita', 'prezzi', 'costo'],
      keywords: ['prezzo', 'prezzi', 'costo', 'costi', 'tariffe', 'listino'],
      required_entities: [], optional_entities: ['servizio'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_orari', nome: 'Informazioni orari', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il paziente chiede gli orari di apertura dello studio.',
      esempi: ['a che ora aprite', 'a che ora chiudete', 'siete aperti il sabato', 'siete aperti oggi', 'quali sono gli orari', 'fino a che ora siete aperti', 'orari di apertura', 'siete aperti a pranzo', 'siete aperti domenica'],
      keywords: ['orari', 'orario', 'aperti', 'chiusi'],
      required_entities: [], optional_entities: ['giorno'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_posizione', nome: 'Informazioni posizione', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il paziente chiede dove si trova lo studio o come raggiungerlo.',
      esempi: ['dove siete', 'qual e l indirizzo', 'come vi raggiungo', 'dove si trova lo studio', 'c e parcheggio', 'come arrivo da voi', 'indirizzo dello studio', 'dov e lo studio', 'dove posso parcheggiare', 'c e un posto dove parcheggiare'],
      keywords: ['indirizzo', 'parcheggio', 'dove siete', 'dove parcheggiare', 'dov e lo studio'],
      required_entities: [], optional_entities: [], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_servizi', nome: 'Informazioni servizi', categoria: 'DISCOVERY', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il paziente chiede quali trattamenti vengono offerti o se si fa un certo trattamento.',
      esempi: ['che trattamenti fate', 'di cosa vi occupate', 'fate impianti', 'fate lo sbiancamento', 'fate anche ortodonzia', 'trattate i bambini', 'fate le otturazioni', 'quali servizi offrite', 'fate le faccette', 'fate invisalign'],
      keywords: ['trattamenti', 'servizi', 'vi occupate'],
      required_entities: [], optional_entities: ['servizio'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_pagamenti', nome: 'Pagamenti e convenzioni', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Modalità di pagamento, rate, convenzioni, assicurazioni.',
      esempi: ['accettate carte', 'si puo pagare a rate', 'fate rateizzazione', 'accettate il bancomat', 'avete il finanziamento', 'siete convenzionati', 'accettate l assicurazione', 'fate fattura', 'si paga con la carta'],
      keywords: ['rate', 'rateale', 'finanziamento', 'bancomat', 'convenzione', 'convenzioni', 'convenzionati', 'assicurazione'],
      required_entities: [], optional_entities: ['assicurazione'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_documenti', nome: 'Documenti da portare', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Cosa serve portare alla visita.',
      esempi: ['cosa devo portare', 'che documenti servono', 'devo portare le radiografie', 'serve la tessera sanitaria', 'serve l impegnativa', 'devo portare qualcosa', 'cosa serve per la prima visita'],
      keywords: ['documenti', 'radiografie', 'tessera sanitaria', 'impegnativa'],
      required_entities: [], optional_entities: [], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_trattamenti', nome: 'Come funziona un trattamento', categoria: 'INFORMATION', priorita: 32, safety_level: 'MEDIUM',
      descrizione: 'Domande generali su come funziona un trattamento, durata, fastidio.',
      esempi: ['come funziona lo sbiancamento', 'quanto dura la seduta', 'fa male l impianto', 'cosa si fa nella prima visita', 'cos e la devitalizzazione', 'come funziona l igiene', 'quanto dura il trattamento', 'ogni quanto si fa l igiene', 'si sente dolore', 'serve l anestesia', 'da che eta si porta il bambino', 'in cosa consiste', 'in cosa consiste la cura', 'rovina lo smalto', 'e dannoso per i denti', 'e sicuro', 'ci sono controindicazioni', 'ci sono effetti collaterali', 'quante sedute servono'],
      keywords: ['come funziona', 'quanto dura', 'cos e', 'consiste', 'controindicazioni', 'rovina lo smalto'],
      required_entities: [], optional_entities: ['servizio'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_personale', nome: 'Informazioni sul personale', categoria: 'INFORMATION', priorita: 33, safety_level: 'LOW',
      descrizione: 'Chi sono i dentisti/igienisti dello studio.',
      esempi: ['chi sono i dentisti', 'chi mi visita', 'ci sono dentisti donne', 'chi e il dottore', 'quanti dentisti avete', 'avete un igienista', 'chi fa le igieni'],
      keywords: ['dentisti', 'dottore', 'igienista'],
      required_entities: [], optional_entities: [], actions: ['search_knowledge', 'answer_information'] },
    { id: 'cancella_appuntamento', nome: 'Annullamento appuntamento', categoria: 'CANCELLATION', priorita: 10, safety_level: 'LOW',
      descrizione: 'Il paziente vuole disdire un appuntamento.',
      esempi: ['devo disdire', 'vorrei cancellare l appuntamento', 'non posso venire', 'annullare l appuntamento', 'devo annullare', 'disdire la visita', 'non riesco a venire'],
      keywords: ['disdire', 'disdetta', 'annullare', 'cancellare'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'sposta_appuntamento', nome: 'Spostamento appuntamento', categoria: 'RESCHEDULE', priorita: 10, safety_level: 'LOW',
      descrizione: 'Il paziente vuole spostare un appuntamento già preso.',
      esempi: ['devo spostare l appuntamento', 'posso cambiare giorno', 'vorrei rimandare', 'posso anticipare la visita', 'posso spostare a un altro giorno', 'devo cambiare orario', 'posticipare l appuntamento'],
      keywords: ['spostare', 'rimandare', 'anticipare', 'posticipare', 'rinviare'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'reclamo', nome: 'Reclamo', categoria: 'COMPLAINT', priorita: 8, safety_level: 'MEDIUM',
      descrizione: 'Insoddisfazione per il servizio o un trattamento ricevuto.',
      esempi: ['sono insoddisfatto', 'vorrei fare un reclamo', 'voglio lamentarmi', 'il trattamento non e andato bene', 'sono molto arrabbiato', 'ho avuto un brutto servizio', 'non sono contento del lavoro', 'sono arrabbiato per come sono stato trattato', 'sono stato trattato male', 'sono deluso dal servizio'],
      keywords: ['reclamo', 'lamentarmi', 'lamentela', 'insoddisfatto', 'insoddisfatta', 'arrabbiato', 'arrabbiata', 'trattato male', 'trattata male', 'inaccettabile', 'deluso', 'delusa', 'vergogna'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'parla_con_persona', nome: 'Richiesta di una persona', categoria: 'HUMAN_HANDOFF', priorita: 1, safety_level: 'LOW',
      descrizione: 'Il paziente chiede di parlare con una persona.',
      esempi: ['voglio parlare con una persona', 'mi passate qualcuno', 'vorrei parlare con il dentista', 'chiamatemi', 'richiamatemi', 'posso parlare con la segretaria'],
      keywords: ['operatore', 'segretaria'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'saluto', nome: 'Saluto', categoria: 'DISCOVERY', priorita: 40, safety_level: 'LOW', solo_isolato: true,
      descrizione: 'Solo un saluto, senza richiesta.',
      esempi: ['ciao', 'buongiorno', 'buonasera', 'salve', 'buon pomeriggio', 'ehi', 'ciao a tutti'],
      keywords: [], required_entities: [], optional_entities: [], actions: ['answer_information'] },
    { id: 'chiusura', nome: 'Ringraziamento o chiusura', categoria: 'FOLLOW_UP', priorita: 40, safety_level: 'LOW', solo_isolato: true,
      descrizione: 'Il paziente ringrazia o chiude la conversazione.',
      esempi: ['grazie', 'grazie mille', 'ok grazie', 'perfetto grazie', 'va bene', 'ok', 'a posto', 'ricevuto', 'ci sentiamo'],
      keywords: [], required_entities: [], optional_entities: [], actions: ['answer_information'] },
  ],

  urgency_rules: {
    // CRITICAL: possibile pericolo per la vita -> escalation immediata, risposta predefinita.
    critical: [
      'non riesco a respirare', 'difficolta a respirare', 'fatica a respirare', 'respiro male', 'non riesco a deglutire',
      'non riesco a inghiottire', 'difficolta a deglutire', 'gonfiore al collo', 'gonfiore alla gola', 'gola gonfia', 'collo gonfio',
      'non smette di sanguinare', 'sanguinamento che non si ferma', 'sanguina e non si ferma', 'emorragia', 'ho perso i sensi', 'sono svenuto', 'sono svenuta', 'svenimento',
    ],
    // HIGH: urgenza clinica (dolore forte, trauma, gonfiore, ascesso) -> priorità allo staff.
    high: [
      'dolore forte', 'dolore fortissimo', 'dolore insopportabile', 'dolore atroce', 'male cane', 'non resisto al dolore', 'non dormo per il dolore', 'non riesco a dormire per il dolore',
      'faccia gonfia', 'viso gonfio', 'guancia gonfia', 'mi si e gonfiata la guancia', 'ascesso', 'pus', 'febbre', 'trauma', 'botta in bocca', 'botta al dente', 'caduta e ho battuto', 'dente caduto', 'mi si e staccato un dente', 'dente staccato', 'dente avulso', 'ho perso un dente',
      'sanguina', 'sanguinamento', 'perdo sangue', 'sanguinamento dopo l estrazione', 'non riesco a sopportare', 'non sopporto piu', 'non ce la faccio piu', 'dolore che non passa', 'e urgente', 'urgentissimo', 'emergenza', 'devo essere visto subito',
    ],
    // MEDIUM: disturbo che merita priorità ma non urgenza clinica.
    medium: [
      'mal di denti', 'mal di dente', 'mi fa male', 'dolore', 'otturazione saltata', 'mi e caduta l otturazione', 'mi e caduta un otturazione', 'mi e caduta una otturazione', 'dente scheggiato', 'si e scheggiato un dente', 'si e scheggiato il dente', 'dente rotto', 'si e rotto un dente',
      'gonfiore', 'gengiva gonfia', 'dente sensibile', 'protesi rotta', 'corona saltata', 'capsula caduta', 'fitta',
    ],
  },

  escalation_rules: {
    handoff_triggers: [
      'parlare con una persona', 'parlare con un operatore', 'parlare con qualcuno', 'parlare con il dottore', 'parlare con il dentista', 'parlare con la segretaria', 'parlare con un umano',
      'voglio una persona', 'passatemi qualcuno', 'mi passate qualcuno', 'mi passi qualcuno', 'chiamatemi', 'richiamatemi', 'mi richiamate', 'mi chiamate', 'non sei una persona', 'sei un robot', 'sei un bot',
      'operatore', 'persona vera', 'persona reale',
    ],
    max_unknown_turns: 2,
    sensitive_insist: 2,
    messaggio_handoff: 'Certo, passo subito la sua richiesta a una persona dello studio, che la ricontatterà il prima possibile.',
  },

  safety_rules: {
    sensibile: true,
    // Richieste del paziente che equivalgono a chiedere diagnosi/terapia/farmaci.
    diagnosi_patterns: [
      'che cosa ho', 'che cos ho', 'cosa potrebbe essere', 'cosa puo essere', 'che cosa puo essere', 'e una carie', 'e un ascesso', 'secondo te e una carie', 'cosa ho secondo te', 'dimmi cosa ho', 'dimmi almeno cosa ho',
      'e grave', 'e pericoloso', 'e normale che', 'devo preoccuparmi', 'mi devo preoccupare', 'devo prendere un antibiotico', 'cosa posso prendere', 'che farmaco', 'che medicina', 'quale medicina',
      'antibiotico', 'antidolorifico', 'ibuprofene', 'paracetamolo', 'tachipirina', 'moment', 'aspirina', 'quanti giorni di antibiotico', 'devo togliere il dente', 'devo estrarre il dente', 'che cura devo fare', 'mi consigli una cura', 'diagnosi', 'cosa mi consigli di fare', 'cosa mi consiglia', 'consiglia di fare', 'cosa mi consigliate', 'cosa grave', 'cosa seria', 'e preoccupante', 'e serio', 'cosa devo fare per il dolore',
    ],
    // Frasi che la RISPOSTA del modello non deve mai contenere (verificaRisposta).
    vietato: [
      'hai la carie', 'ha la carie', 'si tratta di una carie', 'e sicuramente una carie', 'probabilmente e una carie', 'e sicuramente un ascesso',
      'prenda un antibiotico', 'prendi un antibiotico', 'assuma', 'assumere', 'le consiglio di prendere', 'ti consiglio di prendere', 'puo prendere ibuprofene', 'prenda ibuprofene', 'prenda un antidolorifico',
      'non e grave', 'non e nulla', 'non e niente', 'non si preoccupi', 'puo aspettare', 'puoi aspettare', 'mg', 'milligrammi',
    ],
    messaggio_sicurezza: 'Non posso dare valutazioni né consigli su cure o farmaci: per questo serve il dentista, che potrà visitarla. Se vuole, la aiuto subito a fissare un appuntamento.',
    messaggio_emergenza: 'Capisco, la situazione sembra seria. Se ha difficoltà a respirare o a deglutire, o un sanguinamento che non si ferma, chiami subito il 118 o si rechi al pronto soccorso. Avviso immediatamente lo studio.',
  },

  response_rules: { max_frasi: 3, una_domanda_per_messaggio: true, emoji: 'mai' },

  default_questions: {
    servizio: ['Che tipo di visita o trattamento le serve?', 'Per cosa vorrebbe venire: controllo, igiene o altro?', 'Mi dica pure di cosa ha bisogno.'],
    nome_paziente: ['Come si chiama?', 'Mi dice il suo nome, così preparo la richiesta?', 'A che nome registro la richiesta?'],
    sintomo: ['Mi racconta che problema sta avendo?', 'Che cosa le dà fastidio, esattamente?', 'Può descrivermi brevemente il disturbo?'],
    urgenza: ['Il dolore è forte o riesce a sopportarlo?', 'Il fastidio è intenso oppure gestibile?'],
  },

  common_scenarios: [
    'Prima visita e igiene (prenotazione con servizio noto)',
    'Dolore o sintomo con raccolta dati e priorità',
    'Urgenza clinica con passaggio rapido allo staff',
    'Domande su prezzi, orari, pagamenti: solo da dati del tenant',
    'Richieste di diagnosi o farmaci: risposta di sicurezza e proposta di appuntamento',
    'Spostamenti, annullamenti, reclami: passaggio a una persona',
  ],

  confidence_thresholds: { intent_min: 0.55, intent_ok: 0.8 },
};

// FAQ di SETTORE: conoscenza generale, valida per qualunque studio. Nessun
// prezzo, orario, nome o indirizzo: quelli stanno solo nei dati del tenant.
const f = (intent, domanda_canonica, varianti, risposta_base) => ({ intent, domanda_canonica, varianti, risposta_base, condizioni: {} });

export const faq = [
  f('info_trattamenti', 'Cosa si fa nella prima visita?', ['come funziona la prima visita', 'cosa succede alla prima visita', 'che cosa comprende la prima visita', 'cosa si fa alla prima visita'],
    'In genere la prima visita comprende alcune domande sulla sua salute e sulle sue abitudini, un controllo di denti e gengive e, se il dentista lo ritiene utile, delle radiografie. Alla fine il dentista le illustra il percorso di cura consigliato.'),
  f('info_trattamenti', 'Quanto dura una seduta di igiene dentale?', ['quanto dura l igiene', 'quanto dura la pulizia dei denti', 'quanto tempo ci vuole per l igiene', 'quanto dura la pulizia'],
    'Una seduta di igiene dentale dura in genere tra i 30 e i 60 minuti; il tempo esatto dipende dalla situazione di ciascuno.'),
  f('info_trattamenti', 'Ogni quanto si fa l\'igiene dentale?', ['ogni quanto si fa la pulizia dei denti', 'ogni quanto devo fare l igiene', 'quante volte l anno si fa l igiene', 'ogni quanto va fatta la pulizia'],
    'Di solito si consiglia l\'igiene professionale una o due volte l\'anno, ma è il dentista a indicare la frequenza più adatta a ciascuna persona.'),
  f('info_trattamenti', 'Ogni quanto è bene fare un controllo dal dentista?', ['ogni quanto devo fare il controllo dal dentista', 'ogni quanto va fatta la visita di controllo', 'ogni quanto si va dal dentista', 'ogni quanto controllo'],
    'In genere è consigliato un controllo ogni sei mesi o una volta l\'anno; il dentista può indicare una frequenza diversa in base alle esigenze.'),
  f('info_trattamenti', 'Lo sbiancamento fa male?', ['lo sbiancamento e doloroso', 'fa male sbiancare i denti', 'lo sbiancamento da fastidio', 'lo sbiancamento rovina i denti'],
    'Lo sbiancamento può causare una sensibilità temporanea dei denti. Il dentista valuta in visita se è adatto al suo caso e come eseguirlo.'),
  f('info_trattamenti', 'Come funziona lo sbiancamento dentale?', ['come si fa lo sbiancamento', 'come funziona lo sbiancamento', 'in cosa consiste lo sbiancamento', 'quanto dura lo sbiancamento'],
    'Lo sbiancamento schiarisce il colore dei denti con prodotti specifici applicati dal dentista o usati a casa sotto il suo controllo. Il risultato e i tempi dipendono dal singolo caso, per questo serve una visita di valutazione.'),
  f('info_trattamenti', 'Quanto dura l\'effetto dello sbiancamento?', ['quanto dura lo sbiancamento nel tempo', 'per quanto tempo restano bianchi i denti', 'l effetto dello sbiancamento e permanente'],
    'La durata dell\'effetto dipende dal caso e dalle abitudini (per esempio fumo, caffè, tè); il dentista può indicare cosa aspettarsi.'),
  f('info_trattamenti', 'Cos\'è la devitalizzazione?', ['cosa e la devitalizzazione', 'in cosa consiste la devitalizzazione', 'cosa significa devitalizzare un dente', 'cos e la cura canalare', 'come funziona la devitalizzazione'],
    'La devitalizzazione, o terapia canalare, tratta l\'interno del dente (il nervo e i canali) quando è infiammato o infetto, per poter conservare il dente. Serve una visita per capire se è necessaria.'),
  f('info_trattamenti', 'Cos\'è un impianto dentale?', ['cosa e un impianto dentale', 'come funziona un impianto', 'in cosa consiste l impianto', 'come si fa un impianto', 'cos e l implantologia'],
    'L\'impianto è una radice artificiale, in genere di titanio, inserita nell\'osso: su di essa si fissa il nuovo dente. Tempi e modalità vengono definiti dal dentista dopo la visita.'),
  f('info_trattamenti', 'L\'impianto dentale fa male?', ['fa male l impianto', 'l impianto e doloroso', 'si sente dolore con l impianto', 'si sente male durante l impianto'],
    'L\'intervento viene eseguito con anestesia locale. Per decorso e indicazioni successive il dentista dà istruzioni specifiche per il suo caso.'),
  f('info_trattamenti', 'Cos\'è una corona o capsula dentale?', ['cosa e una corona dentale', 'cosa e una capsula', 'a cosa serve la corona', 'cos e la capsula', 'cos e una corona'],
    'La corona (o capsula) è un rivestimento che ricopre un dente danneggiato per proteggerlo e ripristinarne forma e funzione.'),
  f('info_trattamenti', 'Si usa l\'anestesia?', ['serve l anestesia', 'fanno l anestesia', 'si sente male con l anestesia', 'mi fate l anestesia', 'si usa l anestesia'],
    'Quando una cura può dare fastidio il dentista utilizza l\'anestesia locale e ne parla prima con il paziente.'),
  f('info_trattamenti', 'Ho paura del dentista, cosa posso fare?', ['ho paura del dentista', 'ho il terrore del dentista', 'sono molto ansioso per il dentista', 'ho l ansia del dentista', 'mi spaventa il dentista'],
    'È molto comune: chi lavora in uno studio dentistico è abituato ad accogliere chi ha timore. Può dirlo al momento dell\'appuntamento, così il dentista procede con i tempi giusti per lei.'),
  f('info_trattamenti', 'Da che età si porta un bambino dal dentista?', ['da che eta si porta il bambino dal dentista', 'quando portare mio figlio dal dentista', 'a che eta la prima visita del bambino', 'da quando si va dal dentista da piccoli'],
    'In generale si consiglia una prima visita intorno ai 3-4 anni, o prima se ci sono dubbi o disturbi. Per i dettagli sui bambini è meglio confrontarsi con lo studio.'),
  f('info_documenti', 'Cosa devo portare alla prima visita?', ['cosa devo portare alla visita', 'che documenti servono per la prima visita', 'cosa serve portare', 'devo portare qualcosa alla prima visita'],
    'Alla prima visita è utile portare un documento di identità, la tessera sanitaria, eventuali radiografie o referti precedenti e l\'elenco dei farmaci che assume. Per altre indicazioni verifichi con lo studio.'),
  f('info_trattamenti', 'Servono le radiografie?', ['devo fare le radiografie', 'fate le radiografie', 'serve la radiografia', 'ci vuole la radiografia'],
    'La radiografia viene eseguita solo se il dentista la ritiene necessaria per la valutazione.'),
  f('info_trattamenti', 'I denti del giudizio vanno sempre tolti?', ['vanno tolti i denti del giudizio', 'devo togliere il dente del giudizio', 'i denti del giudizio vanno estratti'],
    'Non sempre: è il dentista a valutare se estrarli, di solito con una radiografia e una visita.'),
  f('info_trattamenti', 'Quanto dura un trattamento ortodontico?', ['quanto dura l apparecchio', 'quanto tempo si porta l apparecchio', 'quanto dura la cura ortodontica', 'per quanto tempo si porta l apparecchio'],
    'La durata varia molto da caso a caso, spesso da alcuni mesi a un paio d\'anni. Il piano viene definito dal dentista dopo la visita.'),
  f('info_trattamenti', 'Cosa sono gli allineatori trasparenti?', ['cosa sono gli aligner', 'cos e invisalign', 'come funzionano le mascherine trasparenti', 'cosa sono gli allineatori', 'l apparecchio trasparente funziona'],
    'Gli allineatori trasparenti sono mascherine rimovibili che spostano gradualmente i denti: in alcuni casi sono un\'alternativa all\'apparecchio fisso. La valutazione spetta al dentista.'),
  f('info_trattamenti', 'Posso andare dal dentista in gravidanza?', ['si puo andare dal dentista in gravidanza', 'sono incinta posso fare l igiene', 'sono in gravidanza posso curarmi i denti', 'dentista in gravidanza'],
    'In gravidanza è importante avvisare lo studio: il dentista valuta quali cure sono adatte e in quale momento.'),
  f('info_trattamenti', 'Cosa causa l\'alito cattivo?', ['perche ho l alito cattivo', 'cosa fare per l alitosi', 'da cosa dipende l alitosi', 'come si cura l alitosi'],
    'L\'alito pesante può avere cause diverse: serve una visita per capire da dove dipende, e il dentista indica come intervenire.'),
  f('info_trattamenti', 'Cos\'è l\'otturazione?', ['cosa e l otturazione', 'come si fa un otturazione', 'in cosa consiste l otturazione', 'come funziona l otturazione'],
    'L\'otturazione serve a ricostruire la parte di dente rovinata, per esempio da una carie, dopo averla pulita. Il dentista stabilisce in visita il tipo di intervento.'),
  f('info_trattamenti', 'Dopo un\'estrazione o un intervento cosa devo fare?', ['cosa devo fare dopo l estrazione', 'cosa fare dopo l intervento', 'dopo l estrazione cosa si fa', 'indicazioni dopo un intervento dentale'],
    'Dopo un intervento il dentista dà indicazioni specifiche per il suo caso: le segua con attenzione. Per sintomi particolari contatti direttamente lo studio.'),
  f('info_trattamenti', 'Cos\'è l\'igiene dentale professionale?', ['cosa e l igiene dentale', 'a cosa serve l igiene dentale', 'cosa si fa nell igiene', 'in cosa consiste la pulizia dei denti', 'a cosa serve la pulizia dei denti'],
    'L\'igiene professionale rimuove placca e tartaro che lo spazzolino non elimina e lucida i denti: aiuta a mantenere sane gengive e denti.'),
];
