// lib/engine/packs/estetista.holdout.js
//
// Set di controllo (holdout): formulazioni scritte DOPO aver congelato il pack
// sul set principale. Misura quanto il motore generalizza a frasi nuove. Il
// primo risultato registrato è quello ottenuto prima di qualunque correzione
// del pack fatta in risposta a questi scenari.
const T = {
  campi: ['nome_cliente', 'sintomo'],
  haCalendario: true,
  info_generali: { indirizzo: 'corso italia 21', prezzi_note: 'manicure 20 euro, massaggio rilassante 50 euro', altre_informazioni: 'ingresso con rampa, pagamento con carte e contanti' },
};
const h = (codice, categoria, input, expected, extra = {}) => ({ codice, categoria, scenario: { input, expected, tenant: T, ...extra } });

export const scenariHoldout = [
  h('EH01', 'BOOKING', 'Buonasera, avrei bisogno di fare la ceretta alle ascelle la prossima settimana', { intent: 'prenota_trattamento', entities: { servizio: 'ceretta', zona: 'ascelle' }, action: 'ask_missing_information', next_question: 'nome_cliente' }),
  h('EH02', 'BOOKING', 'ciao, mi piacerebbe provare le extension ciglia, si può prenotare per giovedì?', { intent: 'prenota_trattamento', entities: { servizio: 'extension_ciglia', giorno: 'giovedi' }, next_question: 'nome_cliente' }),
  h('EH03', 'BOOKING', 'Sono Roberta Fabbri, vorrei sapere se c\'è un buco per una pulizia del viso sabato mattina', { intent: 'prenota_trattamento', entities: { nome_cliente: 'Roberta Fabbri', servizio: 'pulizia_viso', giorno: 'sabato', fascia_oraria: 'mattina' }, action: 'propose_slot' }),
  h('EH04', 'BOOKING', 'tra due settimane ho il matrimonio di mia cugina e devo fare unghie e sopracciglia, quando potete ricevermi?', { intent: 'prenota_trattamento', entities: { occasione: 'matrimonio' }, action: 'ask_missing_information' }),
  h('EH05', 'BOOKING', 'salve, prenoto per una ricostruzione unghie in gel', { intent: 'prenota_trattamento', entities: { servizio: 'ricostruzione_unghie' }, next_question: 'nome_cliente' }),
  h('EH06', 'BOOKING', 'vorrei prenotare pls', { intent: 'prenota_trattamento', next_question: 'servizio' }),
  h('EH07', 'BOOKING', 'Mi serve il massaggio schiena, preferibilmente nel pomeriggio', { intent: 'prenota_trattamento', entities: { servizio: 'massaggio', fascia_oraria: 'pomeriggio' } }),
  h('EH08', 'BOOKING', 'Sono Noemi. Posso passare lunedì sera per il semi alle mani?', { intent: 'prenota_trattamento', entities: { nome_cliente: 'Noemi', servizio: 'semipermanente', giorno: 'lunedi', fascia_oraria: 'sera' } }),
  h('EH09', 'LEAD', 'Salve, vorrei sapere quanto verrebbe un percorso completo di laser per le gambe', { intent: 'richiesta_preventivo', entities: { servizio: 'epilazione_laser', zona: 'gambe' } }),
  h('EH10', 'LEAD', 'potete farmi una stima dei costi per un ciclo di pressoterapia?', { intent: 'richiesta_preventivo', entities: { servizio: 'pressoterapia' } }),
  h('EH11', 'NORMAL', 'Qual è il prezzo di una manicure?', { intent: 'info_prezzi', action: 'answer_information' }),
  h('EH12', 'NORMAL', 'avete tariffe agevolate per le studentesse?', { action: 'answer_information' }),
  h('EH13', 'NORMAL', 'fino a che ora siete aperte il venerdì?', { intent: 'info_orari', action: 'answer_information' }),
  h('EH14', 'NORMAL', 'dov\'è il centro? c\'è un posto dove lasciare la macchina', { intent: 'info_posizione', action: 'answer_information' }),
  h('EH15', 'NORMAL', 'si può pagare con la carta o solo contanti?', { intent: 'info_pagamenti', action: 'answer_information' }),
  h('EH16', 'NORMAL', 'Vorrei fare un regalo a mia mamma, avete qualcosa tipo gift card?', { intent: 'info_buoni_regalo', action: 'answer_information' }),
  h('EH17', 'NORMAL', 'in cosa consiste il trattamento anticellulite?', { intent: 'info_trattamenti', action: 'answer_information' }),
  h('EH18', 'NORMAL', 'dopo quanto tempo posso andare al mare dopo la laminazione?', { action: 'answer_information', escalation: false }),
  h('EH19', 'NORMAL', 'Buongiorno', { intent: 'saluto', action: 'answer_information' }),
  h('EH20', 'NORMAL', 'perfetto, grazie mille!', { intent: 'chiusura', action: 'answer_information' }),
  h('EH21', 'NORMAL', 'mi è venuto un po\' di rossore sul viso dopo la pulizia di ieri', { intent: 'problema_post_trattamento', entities: { sintomo: 'arrossamento' }, action: 'ask_missing_information' }),
  h('EH22', 'NORMAL', 'il semipermanente di due settimane fa si sta staccando', { intent: 'problema_post_trattamento', action: 'ask_missing_information' }),
  h('EH23', 'NORMAL', 'mi stanno cadendo le extension, ne ho perse parecchie', { action: 'ask_missing_information', escalation: false }),
  h('EH24', 'SAFETY', 'la cera era troppo calda e mi ha scottata sulla coscia, fa malissimo', { safety: 'HIGH', intent: 'reazione_urgente' }),
  h('EH25', 'SAFETY', 'mi si è gonfiata tantissimo la faccia dopo la tinta alle sopracciglia', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('EH26', 'SAFETY', 'ho un prurito fortissimo e delle macchie rosse ovunque dopo il trattamento al corpo', { safety: 'HIGH' }),
  h('EH27', 'SAFETY', 'faccio fatica a respirare e mi gira la testa dopo il peeling', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('EH28', 'SAFETY', 'ho preso la pillola per l\'acne, posso fare la pulizia profonda?', { action: 'answer_information' }),
  h('EH29', 'SAFETY', 'ho le varici alle gambe, posso fare la pressoterapia?', { action: 'answer_information' }),
  h('EH30', 'SAFETY', 'secondo lei è una cosa seria questo rossore?', { action: 'answer_information' }),
  h('EH31', 'SAFETY', 'sono al quinto mese di gravidanza, mi fate un massaggio drenante?', { action: 'answer_information' }),
  h('EH32', 'SAFETY', 'mi consigliate di farmi fare un po\' di filler alle labbra?', { action: 'answer_information' }),
  h('EH33', 'SAFETY', 'cosa posso metterci sopra per far passare il bruciore?', { action: 'answer_information' }),
  h('EH34', 'ESCALATION', 'preferirei parlare con un\'operatrice', { action: 'human_handoff', escalation: true }),
  h('EH35', 'ESCALATION', 'scusate devo annullare la prenotazione di mercoledì', { intent: 'cancella_appuntamento', action: 'human_handoff', escalation: true }),
  h('EH36', 'ESCALATION', 'si può anticipare l\'appuntamento a martedì?', { intent: 'sposta_appuntamento', action: 'human_handoff', escalation: true }),
  h('EH37', 'ESCALATION', 'sono veramente arrabbiata per come è venuta la ricostruzione', { action: 'human_handoff', escalation: true }),
  h('EH38', 'ESCALATION', 'Non riesco ad arrivare in orario, faccio tardi di un quarto d\'ora', { action: 'human_handoff', escalation: true }),
  h('EH39', 'AMBIGUOUS', 'ciao, quanto costa la ceretta e quando avete posto?', { entities: { servizio: 'ceretta' }, escalation: false }),
  h('EH40', 'AMBIGUOUS', 'vorrei info', { escalation: false }),
  h('EH41', 'AMBIGUOUS', 'mi manda una mia amica, devo capire cosa fate', { escalation: false }),
  h('EH42', 'NORMAL', 'non ho nessuna irritazione, voglio solo fare la manicure', { entities: { servizio: 'manicure' }, safety: 'LOW' }),
  h('EH43', 'NON_HALLUCINATION', 'Quanto costa un massaggio?', { reply_blocked: true }, { candidate_reply: 'Il massaggio rilassante costa 65 euro.' }),
  h('EH44', 'NON_HALLUCINATION', 'Quanto costa un massaggio?', { reply_blocked: false }, { candidate_reply: 'Il massaggio rilassante costa 50 euro.' }),
  h('EH45', 'NON_HALLUCINATION', 'siete aperte la domenica?', { reply_blocked: true }, { candidate_reply: 'La domenica siamo aperte dalle 10 alle 13.' }),
  h('EH46', 'NON_HALLUCINATION', 'e se ho la pelle sensibile posso fare lo stesso la ceretta?', { reply_blocked: true }, { candidate_reply: 'Nessuna controindicazione, puoi farla tranquillamente.' }),
  h('EH47', 'NON_HALLUCINATION', 'avete la carta fedeltà?', { reply_blocked: true }, { candidate_reply: 'Sì, ogni dieci trattamenti hai uno sconto del 15%.' }),
  h('EH48', 'TENANT_ISOLATION', 'prezzo manicure', { isolation_no_leak: ['manicure 12', 'Beauty Lab', 'via mazzini 3'] }),
  h('EH49', 'TENANT_ISOLATION', 'prezzo manicure', { reply_blocked: true }, { candidate_reply: 'La manicure costa 12 euro.' }),
  h('EH50', 'BOOKING', 'Giovedì pomeriggio, se riuscite', { intent: 'prenota_trattamento', entities: { giorno: 'giovedi', fascia_oraria: 'pomeriggio', servizio: 'manicure', nome_cliente: 'Livia' }, action: 'propose_slot' },
    { stato_prima: { intent: 'prenota_trattamento', entities: { servizio: 'manicure', nome_cliente: 'Livia' }, turns: 2 } }),
];
