// lib/engine/packs/medico.js
//
// Sector Pack "medico" v1 — conoscenza di SETTORE (studio medico / ambulatorio
// in Italia, non di un singolo studio). Prezzi, orari, prestazioni davvero
// offerte, specialisti, convenzioni (SSN, assicurazioni), personale e indirizzo
// NON stanno qui: arrivano solo dai dati del tenant. Il lessico riconosce le
// parole del paziente (anche per prestazioni che uno studio specifico potrebbe
// non offrire): riconoscere "ecografia" non significa che lo studio la faccia.
//
// Settore REGOLAMENTATO: il bot non fa diagnosi, non consiglia farmaci o
// dosaggi, non interpreta esami o referti, non promette esiti, non sostituisce
// il medico. Ricette, impegnative e certificati passano alla segreteria/medico.
// Le emergenze rimandano al 112/118. Liste e FAQ sono scritte da AI: vanno
// riviste da un medico prima di un uso reale.

export const SETTORE = 'medico';
export const VERSIONE = 1;
export const CHANGELOG = 'v1: primo Sector Pack studio medico — lessico (prestazioni, specialità, sintomi, documenti), 21 intent, 14 entità, red flag CRITICAL (112/118) e HIGH, sicurezza anti-diagnosi/farmaci/referti/prognosi, ricette e certificati in passaggio a segreteria, FAQ di settore generali.';

// Voce "specialità" + voce "visita specialistica" (la visita implica la prestazione).
// Dai nomi di persona (cardiologo, oculista...) si derivano "appuntamento con/dal ...".
const spec = (id, forme, visita) => [
  { canonical: `spec_${id}`, entity: 'specialita', value: id, synonyms: forme },
  { canonical: `visita_${id}`, entity: 'prestazione', value: 'visita_specialistica',
    synonyms: [...visita, ...forme.filter((x) => /(o|a|e)$/.test(x) && !/(ia|ica|ico)$/.test(x)).flatMap((x) => ['con il', 'con la', 'con l', 'dal', 'dalla', 'dall'].map((p) => `appuntamento ${p} ${x}`))] },
];

export const pack = {
  identity: {
    nome_ruolo: 'studio medico',
    entita_nome: 'nome_paziente',
    descrizione: 'Sei l\'assistente digitale di uno studio medico / ambulatorio. Accogli i pazienti con tono professionale, rassicurante e chiaro; gestisci richieste di appuntamento, informazioni e situazioni urgenti. Non sei un medico: non fai diagnosi, non valuti sintomi, non consigli farmaci o dosaggi, non interpreti esami o referti, non prometti esiti e non decidi se una ricetta o un certificato verrà rilasciato.',
  },
  mission: 'Capire cosa serve al paziente (visita, specialista, esame, documento, disturbo), raccogliere solo le informazioni necessarie, organizzare l\'appuntamento e far arrivare subito allo staff le situazioni che richiedono attenzione clinica; in caso di emergenza indirizzare al 112/118.',
  tone_default: 'professionale',
  conversation_rules: [
    'Messaggi brevi (2-3 frasi), linguaggio semplice, niente tecnicismi inutili.',
    'Con chi sta male o è preoccupato: prima una frase di vicinanza, poi la domanda.',
    'Una sola domanda per messaggio e mai su un\'informazione già data.',
    'Se il paziente scrive per un familiare (figlio, genitore anziano), rivolgiti a chi scrive e raccogli il nome di chi verrà visitato.',
    'Mai diagnosi ("è influenza"), mai valutazioni di gravità ("non è niente"), mai farmaci o dosaggi, mai interpretazione di referti o analisi.',
    'Ricette, impegnative, certificati e rinnovi di terapia: non promettere nulla, dì che la richiesta passa alla segreteria o al medico.',
    'Se descrive sintomi che possono essere gravi (dolore al petto, difficoltà a respirare, segni di ictus, perdita di coscienza, emorragia, reazione allergica grave, pensieri di farla finita) invita subito a chiamare il 112 o il 118 e avvisa lo studio.',
  ],
  prohibited_claims: [
    'dire al paziente cosa ha o che cosa è un sintomo',
    'consigliare farmaci, antibiotici, antidolorifici, integratori, dosaggi o di sospendere una terapia',
    'interpretare esami, analisi, referti o immagini',
    'dire che un sintomo non è grave o che si può aspettare',
    'garantire esiti, guarigione o il rilascio di ricette, certificati o prescrizioni',
    'indicare prezzi, sconti, orari, convenzioni, prestazioni o specialisti non presenti nelle fonti',
  ],
  business_rules: [
    'Annullamenti e spostamenti di appuntamenti già presi vanno passati allo staff.',
    'Ricette, rinnovi di terapia, impegnative, certificati e lettura dei referti passano alla segreteria o al medico: il bot non li promette.',
    'Le situazioni a rischio (dolore toracico, difficoltà respiratoria, segni di ictus, perdita di coscienza, emorragia, anafilassi, avvelenamento, pensieri suicidi) hanno priorità su qualunque altra richiesta e rimandano al 112/118.',
    'Se serva l\'impegnativa, la tessera sanitaria o altra documentazione dipende dalla prestazione e dallo studio: va verificato con lo studio, non assunto.',
    'Le visite a domicilio e il teleconsulto vanno proposti solo se risultano dalle fonti del tenant.',
  ],

  entities: [
    { id: 'prestazione', descrizione: 'Il tipo di visita o prestazione richiesta (indica cosa il paziente cita, non cosa offre lo studio).', tipo: 'enum', priorita: 10,
      valori: ['visita_generale', 'visita_specialistica', 'controllo', 'prelievo', 'ecg', 'ecografia', 'vaccinazione', 'idoneita_sportiva', 'check_up', 'visita_domiciliare', 'teleconsulto', 'medicazione', 'altro'],
      domanda_varianti: ['Che tipo di visita o prestazione le serve?', 'Per cosa vorrebbe venire: una visita, un esame, un controllo?', 'Mi dica pure di cosa ha bisogno.'] },
    { id: 'specialita', descrizione: 'Specialità medica indicata dal paziente.', tipo: 'enum', priorita: 12,
      valori: ['cardiologia', 'dermatologia', 'ortopedia', 'ginecologia', 'pediatria', 'oculistica', 'otorino', 'neurologia', 'urologia', 'endocrinologia', 'gastroenterologia', 'pneumologia', 'allergologia', 'reumatologia', 'dietologia', 'psichiatria', 'medicina_sportiva', 'medicina_lavoro'],
      domanda_varianti: ['Di quale specialista avrebbe bisogno?', 'Per quale specialità vorrebbe la visita?'] },
    { id: 'sintomo', descrizione: 'Il disturbo che il paziente descrive con parole sue (non è una diagnosi del bot).', tipo: 'enum', priorita: 15,
      valori: ['febbre', 'tosse', 'mal_di_gola', 'mal_di_testa', 'mal_di_schiena', 'mal_di_pancia', 'nausea_vomito', 'diarrea', 'vertigini', 'eruzione_cutanea', 'dolore', 'stanchezza', 'pressione', 'palpitazioni', 'raffreddore', 'bruciore_urine', 'disturbi_sonno', 'ansia', 'ferita', 'altro'],
      domanda_varianti: ['Mi racconta che disturbo ha?', 'Che cosa la preoccupa, esattamente?', 'Può descrivermi brevemente il problema?'] },
    { id: 'nome_paziente', descrizione: 'Nome del paziente (o di chi verrà visitato).', tipo: 'string', priorita: 20,
      domanda_varianti: ['Come si chiama?', 'Mi dice il suo nome, così preparo la richiesta?', 'A che nome registro la richiesta?'] },
    { id: 'urgenza', descrizione: 'Intensità del disturbo riferita: forte o gestibile.', tipo: 'enum', priorita: 25, valori: ['forte', 'gestibile'],
      domanda_varianti: ['Il disturbo è forte o riesce a gestirlo?', 'È molto intenso oppure sopportabile?'] },
    { id: 'durata_problema', descrizione: 'Da quanto tempo c\'è il disturbo.', tipo: 'string', priorita: 45,
      domanda_varianti: ['Da quanto tempo ha questo disturbo?'] },
    { id: 'tipo_paziente', descrizione: 'Adulto o bambino.', tipo: 'enum', priorita: 55, valori: ['adulto', 'bambino'] },
    { id: 'per_chi', descrizione: 'Per chi è la richiesta, se non per chi scrive.', tipo: 'enum', priorita: 56, valori: ['figlio', 'genitore', 'familiare'] },
    { id: 'primo_accesso', descrizione: 'Se è la prima volta che il paziente viene nello studio.', tipo: 'enum', priorita: 50, valori: ['si', 'no'] },
    { id: 'ha_impegnativa', descrizione: 'Se il paziente dichiara di avere un\'impegnativa o prescrizione.', tipo: 'enum', priorita: 52, valori: ['si', 'no'] },
    { id: 'ha_referti', descrizione: 'Se il paziente dichiara di avere esami o referti precedenti.', tipo: 'enum', priorita: 53, valori: ['si', 'no'] },
    { id: 'giorno', descrizione: 'Giorno preferito per l\'appuntamento.', tipo: 'string', priorita: 60 },
    { id: 'fascia_oraria', descrizione: 'Mattina, pomeriggio o sera.', tipo: 'enum', priorita: 61, valori: ['mattina', 'pomeriggio', 'sera'] },
    { id: 'convenzione', descrizione: 'SSN, convenzione, fondo sanitario o assicurazione citati dal paziente.', tipo: 'string', priorita: 70 },
    { id: 'telefono', descrizione: 'Numero di telefono se il paziente lo fornisce (di norma già noto da WhatsApp).', tipo: 'string', priorita: 99 },
  ],

  lexicon: [
    // ---- Visite specialistiche (prima delle voci generiche) ----
    ...spec('cardiologia', ['cardiologo', 'cardiologa', 'cardiologia', 'cardiologica', 'cardiologico'], ['visita cardiologica', 'visita dal cardiologo', 'visita dalla cardiologa', 'controllo cardiologico', 'visita con il cardiologo']),
    ...spec('dermatologia', ['dermatologo', 'dermatologa', 'dermatologia', 'dermatologica', 'dermatologico'], ['visita dermatologica', 'visita dal dermatologo', 'visita dalla dermatologa', 'controllo dei nei', 'mappatura dei nei', 'mappatura nei', 'controllo nei']),
    ...spec('ortopedia', ['ortopedico', 'ortopedica', 'ortopedia'], ['visita ortopedica', 'visita dall ortopedico', 'visita con l ortopedico', 'controllo ortopedico']),
    ...spec('ginecologia', ['ginecologo', 'ginecologa', 'ginecologia', 'ginecologica', 'ginecologico'], ['visita ginecologica', 'visita dal ginecologo', 'visita dalla ginecologa', 'pap test', 'papanicolau']),
    ...spec('pediatria', ['pediatra', 'pediatria', 'pediatrica', 'pediatrico'], ['visita pediatrica', 'visita dal pediatra', 'visita con il pediatra', 'controllo pediatrico']),
    ...spec('oculistica', ['oculista', 'oculistica', 'oculistico'], ['visita oculistica', 'visita dall oculista', 'controllo della vista', 'controllo vista']),
    ...spec('otorino', ['otorino', 'otorinolaringoiatra', 'otorinolaringoiatria'], ['visita otorino', 'visita dall otorino', 'visita otorinolaringoiatrica']),
    ...spec('neurologia', ['neurologo', 'neurologa', 'neurologia', 'neurologica'], ['visita neurologica', 'visita dal neurologo', 'visita dalla neurologa']),
    ...spec('urologia', ['urologo', 'urologa', 'urologia', 'urologica'], ['visita urologica', 'visita dall urologo']),
    ...spec('endocrinologia', ['endocrinologo', 'endocrinologa', 'endocrinologia', 'endocrinologica'], ['visita endocrinologica', 'visita dall endocrinologo', 'visita dalla endocrinologa']),
    ...spec('gastroenterologia', ['gastroenterologo', 'gastroenterologa', 'gastroenterologia', 'gastroenterologica'], ['visita gastroenterologica', 'visita dal gastroenterologo']),
    ...spec('pneumologia', ['pneumologo', 'pneumologa', 'pneumologia', 'pneumologica'], ['visita pneumologica', 'visita dal pneumologo']),
    ...spec('allergologia', ['allergologo', 'allergologa', 'allergologia', 'allergologica'], ['visita allergologica', 'visita dall allergologo', 'test allergologici', 'prick test']),
    ...spec('reumatologia', ['reumatologo', 'reumatologa', 'reumatologia', 'reumatologica'], ['visita reumatologica', 'visita dal reumatologo']),
    ...spec('dietologia', ['dietologo', 'dietologa', 'dietologia', 'nutrizionista', 'dietista'], ['visita dietologica', 'visita dal nutrizionista', 'visita nutrizionale', 'visita dal dietologo']),
    ...spec('psichiatria', ['psichiatra', 'psichiatria', 'psichiatrica'], ['visita psichiatrica', 'visita dallo psichiatra', 'visita dalla psichiatra']),
    ...spec('medicina_sportiva', ['medico dello sport', 'medicina dello sport', 'medicina sportiva'], ['visita di medicina dello sport', 'visita medico sportiva']),
    ...spec('medicina_lavoro', ['medico del lavoro', 'medicina del lavoro'], ['visita medico del lavoro', 'visita di medicina del lavoro', 'sorveglianza sanitaria']),
    { canonical: 'visita_specialistica', entity: 'prestazione', value: 'visita_specialistica', synonyms: ['visita specialistica', 'visite specialistiche', 'visita dallo specialista', 'visita da uno specialista', 'uno specialista', 'visita con lo specialista', 'consulto specialistico'] },

    // ---- Prestazioni ----
    { canonical: 'idoneita_sportiva', entity: 'prestazione', value: 'idoneita_sportiva', synonyms: ['idoneita sportiva', 'idoneita agonistica', 'visita agonistica', 'visita sportiva', 'visita per idoneita', 'visita non agonistica', 'visita per lo sport', 'idoneita per lo sport', 'idoneita per il calcio', 'idoneita per il calcetto', 'idoneita per la palestra', 'idoneita per la piscina', 'idoneita per il nuoto', 'idoneita al calcio', 'certificato agonistico', 'certificato non agonistico'], errors: ['idoneita sportia'] },
    { canonical: 'visita_domiciliare', entity: 'prestazione', value: 'visita_domiciliare', synonyms: ['visita a domicilio', 'visita domiciliare', 'visite a domicilio', 'medico a domicilio', 'venire a casa', 'venite a casa', 'venire a domicilio', 'a domicilio', 'domiciliare', 'dottore a casa', 'medico a casa', 'visita a casa'] },
    { canonical: 'teleconsulto', entity: 'prestazione', value: 'teleconsulto', synonyms: ['teleconsulto', 'televisita', 'visita online', 'visita da remoto', 'videochiamata', 'video visita', 'videovisita', 'consulto online', 'visita telefonica', 'consulto telefonico', 'telemedicina'] },
    { canonical: 'prelievo', entity: 'prestazione', value: 'prelievo', synonyms: ['prelievo', 'prelievi', 'prelievo del sangue', 'prelievo di sangue', 'esami del sangue', 'esame del sangue', 'analisi del sangue', 'analisi di sangue', 'analisi cliniche', 'esame delle urine', 'analisi delle urine', 'analisi', 'esami di laboratorio', 'esami ematici', 'emocromo', 'fare le analisi', 'tampone'], errors: ['prelivo', 'analizi'] },
    { canonical: 'ecg', entity: 'prestazione', value: 'ecg', synonyms: ['ecg', 'elettrocardiogramma', 'holter', 'holter cardiaco', 'holter pressorio', 'test da sforzo', 'prova da sforzo', 'ecocardiogramma', 'ecocardio', 'eco cuore'], errors: ['elettrocardiogrma', 'ecocardiograma'] },
    { canonical: 'ecografia', entity: 'prestazione', value: 'ecografia', synonyms: ['ecografia', 'ecografie', 'eco addome', 'eco tiroide', 'ecografia addominale', 'ecografia alla tiroide', 'ecodoppler', 'eco doppler', 'ecografia mammaria', 'ecografia transvaginale', 'ecografia ostetrica', 'ecografia muscolo tendinea', 'ecografia della spalla', 'ecografia del ginocchio'], errors: ['ecografa', 'ecogarfia'] },
    { canonical: 'vaccinazione', entity: 'prestazione', value: 'vaccinazione', synonyms: ['vaccino', 'vaccini', 'vaccinazione', 'vaccinazioni', 'vaccino antinfluenzale', 'vaccino influenza', 'antinfluenzale', 'richiamo del vaccino', 'richiamo vaccino', 'vaccino antitetanico', 'antitetanica', 'vaccinarmi', 'vaccinare', 'vaccino covid', 'vaccino per i viaggi'], errors: ['vacino', 'vaccinzione'] },
    { canonical: 'check_up', entity: 'prestazione', value: 'check_up', synonyms: ['check up', 'checkup', 'check up completo', 'check up generale', 'controllo generale', 'visita di prevenzione', 'screening', 'pacchetto prevenzione', 'pacchetto di prevenzione', 'pacchetti di prevenzione', 'pacchetto check up', 'esami di routine', 'esami di controllo', 'controlli di routine'] },
    { canonical: 'medicazione', entity: 'prestazione', value: 'medicazione', synonyms: ['medicazione', 'medicare una ferita', 'togliere i punti', 'tolgo i punti', 'rimozione punti', 'cambio medicazione', 'cambiare la medicazione', 'iniezione', 'iniezioni', 'fare una puntura', 'fare un iniezione', 'flebo'] },
    { canonical: 'controllo', entity: 'prestazione', value: 'controllo', synonyms: ['controllo', 'visita di controllo', 'controllo periodico', 'rivalutazione', 'follow up', 'controllo dopo la terapia', 'controllo della pressione', 'misurazione della pressione', 'misurare la pressione'] },
    { canonical: 'visita_generale', entity: 'prestazione', value: 'visita_generale', synonyms: ['visita generale', 'visita medica', 'visita dal medico', 'visita dal dottore', 'visita con il medico', 'visita dalla dottoressa', 'visita dal medico di base', 'visita internistica', 'visita', 'una visita', 'visite', 'consulto', 'parere medico', 'dal dottore', 'dal medico', 'dalla dottoressa'] },

    // ---- Specifiche d'uso ----
    { canonical: 'paziente_bambino', entity: 'tipo_paziente', value: 'bambino', synonyms: ['mio figlio', 'mia figlia', 'il bambino', 'la bambina', 'bimbo', 'bimba', 'mio nipote', 'i miei figli', 'neonato', 'neonata', 'mio figlio piccolo', 'figlio di', 'figlia di'] },
    { canonical: 'per_figlio', entity: 'per_chi', value: 'figlio', synonyms: ['mio figlio', 'mia figlia', 'i miei figli', 'il mio bambino', 'la mia bambina', 'il mio bimbo', 'la mia bimba'] },
    { canonical: 'per_genitore', entity: 'per_chi', value: 'genitore', synonyms: ['mia madre', 'mio padre', 'mia mamma', 'mio papa', 'mia nonna', 'mio nonno', 'i miei genitori', 'mio suocero', 'mia suocera'] },
    { canonical: 'per_familiare', entity: 'per_chi', value: 'familiare', synonyms: ['mia moglie', 'mio marito', 'mia sorella', 'mio fratello', 'mio zio', 'mia zia', 'mia compagna', 'mio compagno', 'un mio familiare'] },
    { canonical: 'paziente_nuovo', entity: 'primo_accesso', value: 'si', synonyms: ['sono nuovo', 'sono nuova', 'prima volta che vengo', 'non sono mai venuto', 'non sono mai venuta', 'non sono mai stato da voi', 'non sono mai stata da voi', 'non vi conosco', 'sono un nuovo paziente', 'e la prima volta', 'prima volta da voi', 'non sono ancora paziente'] },
    { canonical: 'paziente_esistente', entity: 'primo_accesso', value: 'no', synonyms: ['sono gia paziente', 'sono gia venuto', 'sono gia venuta', 'sono gia stato da voi', 'sono gia stata da voi', 'sono un vostro paziente', 'sono una vostra paziente', 'sono vostro paziente', 'sono gia vostro paziente', 'sono gia una vostra paziente', 'sono in cura da voi', 'sono seguito da voi', 'sono seguita da voi'] },
    { canonical: 'con_impegnativa', entity: 'ha_impegnativa', value: 'si', negabile: true, synonyms: ['ho l impegnativa', 'ho la prescrizione', 'ho la ricetta rossa', 'ho una impegnativa', 'ho un impegnativa', 'ho la richiesta del medico', 'con impegnativa'] },
    { canonical: 'senza_impegnativa', entity: 'ha_impegnativa', value: 'no', synonyms: ['non ho l impegnativa', 'non ho impegnativa', 'senza impegnativa', 'non ho la prescrizione', 'non ho la ricetta'] },
    { canonical: 'con_referti', entity: 'ha_referti', value: 'si', negabile: true, synonyms: ['ho gia fatto gli esami', 'ho degli esami', 'ho i referti', 'ho gli esami', 'ho le analisi', 'ho portato gli esami', 'ho una risonanza', 'ho una radiografia', 'ho fatto le analisi', 'ho gia le analisi'] },
    { canonical: 'ssn', entity: 'convenzione', value: 'ssn', synonyms: ['ssn', 'servizio sanitario', 'servizio sanitario nazionale', 'mutuabile', 'in convenzione', 'col ticket', 'con il ticket'], intent: 'info_pagamenti' },
    { canonical: 'assicurazione', entity: 'convenzione', value: 'assicurazione', synonyms: ['assicurazione', 'assicurazioni', 'convenzione', 'convenzioni', 'convenzionati', 'convenzionato', 'fondo sanitario', 'polizza', 'polizza sanitaria', 'welfare aziendale', 'mutua', 'cassa mutua', 'unisalute', 'fondo integrativo'], intent: 'info_pagamenti' },

    // ---- Sintomi (parole del paziente, mai diagnosi) ----
    { canonical: 'urgenza_forte', entity: 'urgenza', value: 'forte', negabile: true, synonyms: ['dolore forte', 'dolore fortissimo', 'dolore insopportabile', 'male cane', 'malissimo', 'un dolore atroce', 'non resisto', 'molto forte', 'fortissimo', 'intenso', 'insopportabile'] },
    { canonical: 'urgenza_gestibile', entity: 'urgenza', value: 'gestibile', negabile: true, synonyms: ['dolore lieve', 'dolore sopportabile', 'gestibile', 'sopportabile', 'un po di fastidio', 'fastidio lieve', 'si sopporta', 'lieve', 'leggero', 'non e forte', 'non molto forte'] },
    { canonical: 'sintomo_febbre', entity: 'sintomo', value: 'febbre', negabile: true, synonyms: ['la febbre', 'ho febbre', 'ha febbre', 'di febbre', 'con febbre', 'febbre da', 'febbre alta', 'febbre e', 'febbricola', 'un po di febbre', 'temperatura alta', 'ho 38', 'ho 39', 'brividi'], intent: 'problema_sintomo' },
    { canonical: 'mal_di_gola', entity: 'sintomo', value: 'mal_di_gola', negabile: true, synonyms: ['mal di gola', 'gola infiammata', 'gola che brucia', 'gola irritata', 'placche in gola', 'tonsille', 'faringite'], intent: 'problema_sintomo' },
    { canonical: 'raffreddore', entity: 'sintomo', value: 'raffreddore', negabile: true, synonyms: ['raffreddore', 'naso chiuso', 'naso che cola', 'starnuti', 'influenza', 'sinusite', 'congestione', 'mal d orecchio', 'otite', 'mal di orecchie'], intent: 'problema_sintomo' },
    { canonical: 'tosse', entity: 'sintomo', value: 'tosse', negabile: true, synonyms: ['tosse', 'tossisco', 'tosse secca', 'tosse grassa', 'catarro', 'bronchite'], intent: 'problema_sintomo' },
    { canonical: 'mal_di_testa', entity: 'sintomo', value: 'mal_di_testa', negabile: true, synonyms: ['mal di testa', 'emicrania', 'cefalea', 'mi scoppia la testa', 'dolore alla testa', 'testa che fa male'], intent: 'problema_sintomo' },
    { canonical: 'mal_di_schiena', entity: 'sintomo', value: 'mal_di_schiena', negabile: true, synonyms: ['mal di schiena', 'dolore alla schiena', 'schiena bloccata', 'colpo della strega', 'lombalgia', 'sciatica', 'cervicale', 'torcicollo', 'male alla schiena', 'mi fa male la schiena'], intent: 'problema_sintomo' },
    { canonical: 'nausea_vomito', entity: 'sintomo', value: 'nausea_vomito', negabile: true, synonyms: ['nausea', 'vomito', 'vomitato', 'ho vomitato', 'conati di vomito', 'mi viene da vomitare', 'rimettere', 'ho rimesso'], intent: 'problema_sintomo' },
    { canonical: 'mal_di_pancia', entity: 'sintomo', value: 'mal_di_pancia', negabile: true, synonyms: ['mal di pancia', 'mal di stomaco', 'dolore alla pancia', 'dolore addominale', 'crampi alla pancia', 'bruciore di stomaco', 'gastrite', 'reflusso', 'gonfiore addominale', 'mi fa male la pancia', 'mi fa male lo stomaco'], intent: 'problema_sintomo' },
    { canonical: 'diarrea', entity: 'sintomo', value: 'diarrea', negabile: true, synonyms: ['diarrea', 'dissenteria', 'scariche', 'intestino in disordine', 'stitichezza', 'colon irritabile'], intent: 'problema_sintomo' },
    { canonical: 'vertigini', entity: 'sintomo', value: 'vertigini', negabile: true, synonyms: ['vertigini', 'capogiri', 'capogiro', 'giramenti di testa', 'mi gira la testa', 'testa che gira', 'sbandamento'], intent: 'problema_sintomo' },
    { canonical: 'eruzione', entity: 'sintomo', value: 'eruzione_cutanea', negabile: true, synonyms: ['eruzione cutanea', 'macchie sulla pelle', 'macchie rosse', 'prurito', 'orticaria', 'rash', 'pelle arrossata', 'bolle sulla pelle', 'brufoli', 'acne', 'eczema', 'dermatite', 'psoriasi', 'verruche', 'neo che', 'fuoco di sant antonio'], intent: 'problema_sintomo' },
    { canonical: 'dolore', entity: 'sintomo', value: 'dolore', negabile: true, synonyms: ['dolore', 'dolori', 'mi fa male', 'mi fanno male', 'dolorante', 'fitta', 'fitte', 'male alla', 'male al', 'dolori articolari', 'dolori muscolari', 'dolore al ginocchio', 'dolore alla spalla'], intent: 'problema_sintomo' },
    { canonical: 'stanchezza', entity: 'sintomo', value: 'stanchezza', negabile: true, synonyms: ['stanchezza', 'stanco da tempo', 'senza energie', 'spossatezza', 'debolezza', 'mi sento debole', 'mi sento molto stanco', 'mi sento molto stanca'], intent: 'problema_sintomo' },
    { canonical: 'pressione', entity: 'sintomo', value: 'pressione', negabile: true, synonyms: ['pressione alta', 'pressione bassa', 'ho la pressione', 'pressione sballata', 'ipertensione', 'ipotensione', 'colesterolo alto', 'glicemia alta', 'diabete'], intent: 'problema_sintomo' },
    { canonical: 'palpitazioni', entity: 'sintomo', value: 'palpitazioni', negabile: true, synonyms: ['palpitazioni', 'cuore che batte forte', 'battito irregolare', 'battito accelerato', 'tachicardia', 'extrasistoli', 'cuore a mille'], intent: 'problema_sintomo' },
    { canonical: 'bruciore_urine', entity: 'sintomo', value: 'bruciore_urine', negabile: true, synonyms: ['bruciore quando faccio pipi', 'bruciore alla pipi', 'bruciore urinario', 'cistite', 'bruciore a urinare', 'devo fare pipi spesso'], intent: 'problema_sintomo' },
    { canonical: 'disturbi_sonno', entity: 'sintomo', value: 'disturbi_sonno', negabile: true, synonyms: ['insonnia', 'non riesco a dormire', 'dormo male', 'non dormo bene', 'sonno disturbato'], intent: 'problema_sintomo' },
    { canonical: 'ansia', entity: 'sintomo', value: 'ansia', negabile: true, synonyms: ['ansia', 'attacco di panico', 'attacchi di panico', 'crisi di panico', 'sono molto ansioso', 'sono molto ansiosa', 'stress', 'esaurimento', 'depressione', 'umore basso', 'tristezza'], intent: 'problema_sintomo' },
    { canonical: 'ferita', entity: 'sintomo', value: 'ferita', synonyms: ['ferita', 'mi sono tagliato', 'mi sono tagliata', 'taglio', 'abrasione', 'escoriazione', 'ustione', 'mi sono ustionato', 'mi sono ustionata', 'puntura di zecca', 'puntura di vespa', 'morso', 'distorsione', 'storta', 'mi sono fatto male', 'mi sono fatta male', 'botta'], intent: 'problema_sintomo' },

    // ---- Concetti di conversazione ----
    { canonical: 'malessere', negabile: true, synonyms: ['sto male', 'non mi sento bene', 'mi sento male', 'mi sento poco bene'], intent: 'problema_sintomo' },
    { canonical: 'prezzo', synonyms: ['prezzo', 'prezzi', 'costo', 'costi', 'quanto costa', 'quanto viene', 'quanto devo pagare', 'tariffa', 'tariffe', 'listino', 'quanto si paga', 'quanto prendete', 'ticket'], intent: 'info_prezzi' },
    { canonical: 'orari', synonyms: ['orari', 'orario', 'aperti', 'aperto', 'chiusi', 'apertura', 'chiusura', 'fino a che ora', 'a che ora aprite', 'a che ora chiudete', 'orari di ricevimento', 'ricevete'], intent: 'info_orari' },
    { canonical: 'indirizzo', synonyms: ['indirizzo', 'dove siete', 'dove si trova', 'come vi raggiungo', 'come arrivo', 'parcheggio', 'posizione', 'dov e lo studio', 'dov e l ambulatorio'], intent: 'info_posizione' },
    { canonical: 'pagamento', synonyms: ['pagamento', 'pagamenti', 'bancomat', 'carta di credito', 'carte', 'contanti', 'fattura', 'rate', 'rateale', 'detraibile', 'detrazione', 'scontrino', 'rimborso'], intent: 'info_pagamenti' },
    { canonical: 'preventivo', synonyms: ['preventivo', 'preventivi', 'stima dei costi', 'stima del costo', 'pacchetto', 'pacchetti'], intent: 'richiesta_preventivo' },
    { canonical: 'appuntamento', synonyms: ['appuntamento', 'prenotare', 'prenotazione', 'fissare', 'disponibilita', 'posto libero', 'slot', 'prenoto', 'prenotarmi'], intent: 'prenota_visita' },
    { canonical: 'ricetta', synonyms: ['ricetta', 'ricette', 'ricetta medica', 'ricetta rossa', 'ricetta dematerializzata', 'rinnovo ricetta', 'rinnovo della ricetta', 'rinnovare la ricetta', 'rinnovo terapia', 'rinnovo della terapia', 'impegnativa', 'impegnative', 'prescrizione', 'prescrizioni', 'prescrivere', 'farmaci cronici', 'piano terapeutico', 'ricetta bianca'], intent: 'richiesta_ricetta' },
    { canonical: 'certificato', synonyms: ['certificato', 'certificati', 'certificato medico', 'certificato di malattia', 'certificato inps', 'attestato di malattia', 'giorni di malattia', 'mettermi in malattia', 'esonero', 'certificato di guarigione', 'certificato di sana e robusta costituzione', 'certificato di buona salute', 'certificato di idoneita', 'certificato per la palestra', 'certificato per la scuola', 'certificato per il lavoro', 'certificato di riammissione'], intent: 'richiesta_certificato' },
    { canonical: 'referti', synonyms: ['referto', 'referti', 'esito', 'esiti', 'risultati degli esami', 'risultati delle analisi', 'ritirare il referto', 'ritirare i referti', 'ritiro referti', 'ritiro referto', 'cartella clinica', 'copia della cartella', 'referto online'], intent: 'info_referti' },
  ],

  intents: [
    { id: 'prenota_visita', nome: 'Prenotazione visita o prestazione', categoria: 'BOOKING', priorita: 20, safety_level: 'LOW',
      descrizione: 'Il paziente vuole fissare una visita, un esame o una prestazione, o chiede disponibilità.',
      esempi: ['vorrei prenotare', 'vorrei un appuntamento', 'vorrei prendere un appuntamento', 'vorrei fissare una visita', 'avete posto domani', 'avete un posto oggi', 'avete disponibilita', 'avete disponibilita questa settimana', 'posso venire venerdi', 'posso prenotare', 'mi serve una visita', 'quando siete liberi', 'prenotazione', 'cerco un appuntamento', 'posso passare domani', 'vorrei venire da voi', 'vorrei una visita', 'posso venire', 'quando potete visitarmi', 'quando mi potete visitare'],
      keywords: ['prenotare', 'prenotazione', 'appuntamento', 'disponibilita', 'fissare', 'prenoto'],
      combinazioni: [
        { entity: 'prestazione', con: ['vorrei', 'mi serve', 'mi servirebbe', 'avrei bisogno', 'ho bisogno', 'devo fare', 'devo fissare', 'vorrei fare', 'voglio fare', 'mi occorre', 'cerco', 'posso venire', 'posso passare', 'vorrei venire', 'volevo fare', 'dovrei', 'dovrei fare', 'quando potete', 'quando riuscite', 'vorrei farmi', 'devo farmi', 'solo un', 'solo una', 'solo per un', 'solo per una', 'avrei necessita', 'ho necessita', 'necessito', 'ha bisogno', 'avrebbe bisogno', 'hanno bisogno'], con_entities: ['giorno', 'fascia_oraria'], non_con_concepts: ['preventivo', 'prezzo', 'ricetta', 'certificato', 'referti', 'pagamento'], score: 0.8 },
        { entity: 'specialita', con: ['vorrei', 'mi serve', 'avrei bisogno', 'ho bisogno', 'cerco', 'devo vedere', 'devo andare', 'vorrei vedere', 'vorrei andare', 'posso vedere', 'avrei necessita', 'ho necessita', 'necessito', 'ha bisogno', 'visita dal', 'visita dalla', 'visita dall', 'visita con'], con_entities: ['giorno'], non_con_concepts: ['preventivo', 'prezzo', 'ricetta', 'certificato', 'referti', 'pagamento'], score: 0.8 },
        { entity: 'primo_accesso', con: ['vorrei una visita', 'mi serve una visita', 'vorrei venire', 'visita'], score: 0.8 },
        { entity: 'tipo_paziente', con: ['visita', 'controllo', 'appuntamento', 'bisogno'], score: 0.7 },
      ],
      required_entities: ['prestazione', 'nome_paziente'], optional_entities: ['specialita', 'giorno', 'fascia_oraria', 'primo_accesso', 'tipo_paziente', 'per_chi', 'ha_impegnativa', 'convenzione'],
      actions: ['ask_missing_information', 'propose_slot', 'create_booking', 'create_lead'] },
    { id: 'richiesta_preventivo', nome: 'Richiesta preventivo', categoria: 'LEAD', priorita: 25, safety_level: 'LOW',
      descrizione: 'Il paziente chiede un preventivo o una stima per una prestazione privata o un pacchetto.',
      esempi: ['vorrei un preventivo', 'mi fate un preventivo', 'preventivo per un check up', 'vorrei sapere il costo del pacchetto completo', 'mi serve un preventivo', 'una stima dei costi', 'potete farmi una stima', 'stima del costo', 'quanto mi costerebbe in tutto', 'preventivo per una visita specialistica'],
      keywords: ['preventivo', 'preventivi'],
      required_entities: ['prestazione', 'nome_paziente'], optional_entities: ['specialita', 'convenzione'],
      actions: ['ask_missing_information', 'create_lead', 'notify_owner'] },
    { id: 'problema_sintomo', nome: 'Disturbo o sintomo', categoria: 'SUPPORT', priorita: 15, safety_level: 'MEDIUM', campi_tenant: true,
      descrizione: 'Il paziente descrive un disturbo (non urgente per le regole del pack): serve raccogliere dati e passare allo staff, senza alcuna valutazione clinica.',
      esempi: ['ho la febbre alta', 'mi e venuta la febbre', 'ho mal di gola', 'ho mal di testa da due giorni', 'ho un po di tosse', 'mi fa male la schiena', 'ho un fastidio', 'ho un problema', 'ho dei dolori', 'mi sento strano', 'ho un disturbo', 'ho un po di nausea', 'ho la pressione alta', 'ho un eruzione sulla pelle'],
      keywords: ['sintomo', 'sintomi'],
      required_entities: ['sintomo', 'nome_paziente'], optional_entities: ['durata_problema', 'urgenza', 'giorno', 'fascia_oraria', 'tipo_paziente', 'per_chi', 'primo_accesso'],
      actions: ['ask_missing_information', 'propose_slot', 'notify_owner', 'create_lead'] },
    { id: 'urgenza_medica', nome: 'Urgenza medica', categoria: 'EMERGENCY', priorita: 5, safety_level: 'HIGH',
      descrizione: 'Situazione che richiede contatto rapido con lo studio o i soccorsi (le emergenze vere passano dalle regole CRITICAL: 112/118).',
      esempi: ['ho un dolore fortissimo', 'e urgente', 'devo essere visto subito', 'ho un emergenza', 'serve un medico subito', 'ho bisogno urgente di un medico', 'sto molto male', 'sta molto male', 'sta male e ha bisogno di un medico', 'mi serve un medico adesso', 'urgentissimo'],
      keywords: ['urgente', 'urgenza', 'emergenza', 'subito'],
      required_entities: ['nome_paziente'], optional_entities: ['sintomo', 'durata_problema', 'per_chi'],
      actions: ['ask_missing_information', 'notify_owner', 'emergency_escalation'] },
    { id: 'info_prezzi', nome: 'Informazioni prezzi', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il paziente chiede quanto costa una visita o una prestazione.',
      esempi: ['quanto costa', 'che prezzo avete', 'quanto viene', 'quanto devo pagare', 'mi dici il costo', 'avete un listino', 'quali sono i prezzi', 'quanto costa una visita', 'prezzi', 'costo', 'quanto costa la visita specialistica', 'quanto costa il prelievo'],
      keywords: ['prezzo', 'prezzi', 'costo', 'costi', 'tariffe', 'listino'],
      required_entities: [], optional_entities: ['prestazione', 'specialita'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_orari', nome: 'Informazioni orari', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il paziente chiede gli orari di apertura o di ricevimento.',
      esempi: ['a che ora aprite', 'a che ora chiudete', 'siete aperti il sabato', 'siete aperti oggi', 'quali sono gli orari', 'fino a che ora siete aperti', 'orari di apertura', 'siete aperti a pranzo', 'siete aperti domenica', 'quando ricevete', 'orari di ricevimento', 'orari dell ambulatorio'],
      keywords: ['orari', 'orario', 'aperti', 'chiusi', 'ricevete'],
      required_entities: [], optional_entities: ['giorno'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_posizione', nome: 'Informazioni posizione', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il paziente chiede dove si trova lo studio o come raggiungerlo.',
      esempi: ['dove siete', 'qual e l indirizzo', 'come vi raggiungo', 'dove si trova lo studio', 'c e parcheggio', 'come arrivo da voi', 'indirizzo dello studio', 'dov e lo studio', 'dov e l ambulatorio', 'dove posso parcheggiare', 'ci sono barriere architettoniche', 'c e l ascensore', 'accesso per disabili'],
      keywords: ['indirizzo', 'parcheggio', 'dove siete', 'dove parcheggiare', 'ascensore', 'barriere'],
      required_entities: [], optional_entities: [], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_servizi', nome: 'Informazioni prestazioni offerte', categoria: 'DISCOVERY', priorita: 30, safety_level: 'LOW',
      descrizione: 'Il paziente chiede quali visite, specialisti o prestazioni sono disponibili.',
      esempi: ['che visite fate', 'di cosa vi occupate', 'quali servizi offrite', 'quali specialisti avete', 'fate anche visite pediatriche', 'fate l ecg', 'fate le analisi del sangue', 'fate i vaccini', 'avete il cardiologo', 'fate visite a domicilio', 'fate teleconsulto', 'fate la visita per l idoneita sportiva', 'avete un dermatologo', 'fate ecografie', 'trattate anche i bambini', 'visitate anche i bambini', 'avete anche la ginecologa'],
      keywords: ['che visite fate', 'quali servizi', 'vi occupate', 'quali specialisti'],
      combinazioni: [
        { entity: 'prestazione', con: ['fate', 'fate anche', 'eseguite', 'effettuate', 'offrite'], non_con_concepts: ['preventivo', 'prezzo', 'appuntamento', 'ricetta', 'certificato', 'pagamento'], score: 0.8 },
        { entity: 'specialita', con: ['fate', 'fate anche', 'offrite'], non_con_concepts: ['preventivo', 'prezzo', 'appuntamento', 'ricetta', 'certificato', 'pagamento'], score: 0.8 },
      ],
      required_entities: [], optional_entities: ['prestazione', 'specialita'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_pagamenti', nome: 'Pagamenti, SSN e convenzioni', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Modalità di pagamento, SSN/ticket, convenzioni, assicurazioni, fatture, detrazioni.',
      esempi: ['accettate carte', 'fate fattura', 'si paga con il bancomat', 'siete convenzionati', 'accettate l assicurazione', 'lavorate con il servizio sanitario', 'la visita e mutuabile', 'si paga il ticket', 'e detraibile', 'si puo avere la fattura per il 730', 'fate la fattura sanitaria', 'rimborso assicurazione', 'siete in convenzione con il fondo'],
      keywords: ['bancomat', 'convenzione', 'convenzioni', 'convenzionati', 'assicurazione', 'ssn', 'mutuabile', 'detraibile', 'ticket'],
      required_entities: [], optional_entities: ['convenzione'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_documenti', nome: 'Documenti da portare', categoria: 'INFORMATION', priorita: 30, safety_level: 'LOW',
      descrizione: 'Cosa serve portare alla visita o all\'esame.',
      esempi: ['cosa devo portare', 'che documenti servono', 'devo portare i vecchi esami', 'serve la tessera sanitaria', 'serve l impegnativa', 'devo portare qualcosa', 'cosa serve per la prima visita', 'devo portare la tessera sanitaria', 'serve un documento', 'devo portare gli esami precedenti', 'serve la prescrizione del medico'],
      keywords: ['documenti', 'tessera sanitaria', 'impegnativa', 'esami precedenti', 'cosa devo portare', 'cosa serve portare'],
      required_entities: [], optional_entities: [], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_prestazioni', nome: 'Come funziona una visita o un esame', categoria: 'INFORMATION', priorita: 32, safety_level: 'MEDIUM',
      descrizione: 'Domande generali su come funziona una visita o un esame, durata, preparazione: solo informazioni generali.',
      esempi: ['come funziona la visita', 'quanto dura la visita', 'cosa si fa nella prima visita', 'devo essere a digiuno', 'serve il digiuno per il prelievo', 'come mi preparo all esame', 'come ci si prepara all ecografia', 'quanto dura l ecg', 'fa male il prelievo', 'in cosa consiste la visita', 'quanto ci vuole per i risultati', 'cosa devo fare prima dell esame', 'come funziona l holter', 'come funziona il teleconsulto', 'come si prenota una visita specialistica', 'serve l impegnativa per la visita specialistica'],
      keywords: ['come funziona', 'quanto dura', 'digiuno', 'preparazione', 'consiste', 'come mi preparo', 'come ci si prepara'],
      required_entities: [], optional_entities: ['prestazione', 'specialita'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_referti', nome: 'Referti e cartella clinica', categoria: 'INFORMATION', priorita: 31, safety_level: 'LOW',
      descrizione: 'Come e quando ritirare referti, esiti o copia della cartella (nessuna interpretazione del contenuto).',
      esempi: ['come ritiro i referti', 'quando sono pronti i referti', 'il referto e pronto', 'posso ritirare il referto', 'si possono avere i referti online', 'posso avere i risultati delle analisi', 'dove ritiro gli esami', 'mi mandate il referto', 'potete inviarmi il referto per email', 'serve la delega per ritirare il referto', 'posso avere una copia della cartella clinica', 'quando arrivano i risultati'],
      keywords: ['referto', 'referti', 'ritirare il referto', 'ritiro referti', 'cartella clinica', 'risultati delle analisi'],
      required_entities: [], optional_entities: [], actions: ['search_knowledge', 'answer_information'] },
    { id: 'info_personale', nome: 'Informazioni sui medici', categoria: 'INFORMATION', priorita: 33, safety_level: 'LOW',
      descrizione: 'Chi sono i medici e gli specialisti dello studio.',
      esempi: ['chi sono i medici', 'chi mi visita', 'ci sono dottoresse', 'chi e il dottore', 'quanti medici avete', 'chi sono gli specialisti', 'c e una dottoressa', 'chi riceve il lunedi', 'con quale medico posso fare la visita', 'il dottore parla inglese'],
      keywords: ['medici', 'dottore', 'dottoressa', 'specialisti', 'chi mi visita'],
      required_entities: [], optional_entities: ['specialita'], actions: ['search_knowledge', 'answer_information'] },
    { id: 'richiesta_ricetta', nome: 'Ricette, impegnative e rinnovi di terapia', categoria: 'HUMAN_HANDOFF', priorita: 12, safety_level: 'MEDIUM',
      descrizione: 'Il paziente chiede una ricetta, un rinnovo di terapia o un\'impegnativa: la richiesta passa alla segreteria/medico, il bot non la promette.',
      esempi: ['mi serve la ricetta', 'vorrei rinnovare la ricetta', 'devo rinnovare la terapia', 'mi serve una ricetta per i miei farmaci', 'mi fate la ricetta', 'mi serve l impegnativa', 'serve una impegnativa per la visita', 'mi serve una prescrizione', 'ho finito le medicine e mi serve la ricetta', 'ricetta per la pressione', 'potete mandarmi la ricetta', 'ricetta dematerializzata', 'rinnovo della ricetta', 'ricetta per mia madre'],
      keywords: ['ricetta', 'ricette', 'rinnovo ricetta', 'rinnovare la ricetta', 'rinnovo terapia', 'prescrizione', 'prescrivere', 'impegnativa per'],
      required_entities: [], optional_entities: ['per_chi'], actions: ['human_handoff'] },
    { id: 'richiesta_certificato', nome: 'Certificati medici', categoria: 'HUMAN_HANDOFF', priorita: 12, safety_level: 'LOW',
      descrizione: 'Il paziente chiede un certificato (malattia, idoneità, scuola, lavoro): passa alla segreteria/medico, il bot non lo promette.',
      esempi: ['mi serve un certificato medico', 'vorrei un certificato di malattia', 'mi serve il certificato per il lavoro', 'certificato per la scuola', 'devo mettermi in malattia', 'serve un certificato per la palestra', 'mi fate il certificato inps', 'certificato di guarigione', 'certificato per il rientro a scuola', 'vorrei un certificato di idoneita', 'certificato medico per la patente'],
      keywords: ['certificato', 'certificati', 'certificato medico', 'certificato di malattia', 'in malattia'],
      required_entities: [], optional_entities: ['per_chi'], actions: ['human_handoff'] },
    { id: 'cancella_appuntamento', nome: 'Annullamento appuntamento', categoria: 'CANCELLATION', priorita: 10, safety_level: 'LOW',
      descrizione: 'Il paziente vuole disdire un appuntamento.',
      esempi: ['devo disdire', 'vorrei cancellare l appuntamento', 'non posso venire', 'annullare l appuntamento', 'devo annullare', 'disdire la visita', 'non riesco a venire', 'devo cancellare la visita', 'annullate la prenotazione', 'non posso piu venire'],
      keywords: ['disdire', 'disdetta', 'annullare', 'cancellare'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'sposta_appuntamento', nome: 'Spostamento appuntamento', categoria: 'RESCHEDULE', priorita: 9, safety_level: 'LOW',
      descrizione: 'Il paziente vuole spostare un appuntamento già preso.',
      esempi: ['devo spostare l appuntamento', 'posso cambiare giorno', 'vorrei rimandare', 'posso anticipare la visita', 'posso spostare a un altro giorno', 'devo cambiare orario', 'posticipare l appuntamento', 'posso spostare la visita', 'si puo spostare la visita', 'posso spostare', 'si puo spostare', 'posso spostarlo', 'posso rimandare', 'si puo rimandare', 'posso cambiare'],
      keywords: ['spostare', 'rimandare', 'anticipare', 'posticipare', 'rinviare'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'reclamo', nome: 'Reclamo', categoria: 'COMPLAINT', priorita: 8, safety_level: 'MEDIUM',
      descrizione: 'Insoddisfazione per il servizio o per come si è stati trattati.',
      esempi: ['sono insoddisfatto', 'vorrei fare un reclamo', 'voglio lamentarmi', 'sono molto arrabbiato', 'ho avuto un brutto servizio', 'sono arrabbiato per come sono stato trattato', 'sono stato trattato male', 'sono deluso dal servizio', 'ho aspettato troppo', 'e stato scortese con me'],
      keywords: ['reclamo', 'lamentarmi', 'lamentela', 'insoddisfatto', 'insoddisfatta', 'arrabbiato', 'arrabbiata', 'trattato male', 'trattata male', 'inaccettabile', 'deluso', 'delusa', 'vergogna', 'scortese'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'parla_con_persona', nome: 'Richiesta di una persona', categoria: 'HUMAN_HANDOFF', priorita: 1, safety_level: 'LOW',
      descrizione: 'Il paziente chiede di parlare con una persona o con il medico.',
      esempi: ['voglio parlare con una persona', 'mi passate qualcuno', 'vorrei parlare con il medico', 'chiamatemi', 'richiamatemi', 'posso parlare con la segretaria', 'vorrei parlare con la dottoressa'],
      keywords: ['operatore', 'segretaria', 'segreteria'],
      required_entities: [], optional_entities: [], actions: ['human_handoff'] },
    { id: 'saluto', nome: 'Saluto', categoria: 'DISCOVERY', priorita: 40, safety_level: 'LOW', solo_isolato: true,
      descrizione: 'Solo un saluto, senza richiesta.',
      esempi: ['ciao', 'buongiorno', 'buonasera', 'salve', 'buon pomeriggio', 'ehi', 'ciao a tutti', 'buondi'],
      keywords: [], required_entities: [], optional_entities: [], actions: ['answer_information'] },
    { id: 'chiusura', nome: 'Ringraziamento o chiusura', categoria: 'FOLLOW_UP', priorita: 40, safety_level: 'LOW', solo_isolato: true,
      descrizione: 'Il paziente ringrazia o chiude la conversazione.',
      esempi: ['grazie', 'grazie mille', 'ok grazie', 'perfetto grazie', 'va bene', 'ok', 'a posto', 'ricevuto', 'ci sentiamo', 'grazie dottore', 'grazie dottoressa'],
      keywords: [], required_entities: [], optional_entities: [], actions: ['answer_information'] },
  ],

  urgency_rules: {
    // CRITICAL: possibile pericolo per la vita -> escalation immediata, risposta predefinita (112/118).
    critical: [
      // cuore
      'dolore al petto', 'dolore forte al petto', 'forte dolore al petto', 'dolore improvviso al petto', 'dolore acuto al petto', 'dolore toracico', 'dolore al torace', 'male al petto', 'mi fa male il petto', 'fitta al petto', 'fitte al petto', 'oppressione al petto', 'peso sul petto', 'peso al petto', 'pressione sul petto', 'dolore dietro lo sterno', 'petto stretto in una morsa', 'dolore al centro del petto',
      'stretta al petto', 'stretta al torace', 'morsa al petto', 'oppressione toracica', 'fastidio al petto', 'dolore alla mascella', 'arriva fino alla mascella', 'arriva alla mascella', 'mi arriva al braccio', 'dolore che arriva al braccio', 'dolore al braccio sinistro', 'male al braccio sinistro', 'mi fa male il braccio sinistro', 'il braccio sinistro mi fa male', 'dolore alla mascella e al braccio',
      'ho un infarto', 'sto avendo un infarto', 'mi sta venendo un infarto', 'sembra un infarto', 'credo sia un infarto', 'penso sia un infarto', 'infarto in corso', 'sospetto infarto', 'arresto cardiaco', 'non ha battito', 'il cuore si e fermato',
      // respiro / allergia / soffocamento
      'non riesco a respirare', 'non riesce a respirare', 'non respira', 'non respiro', 'difficolta a respirare', 'difficolta respiratoria', 'fatico a respirare', 'faccio fatica a respirare', 'fa fatica a respirare', 'respiro con fatica', 'respirare con difficolta', 'si sta gonfiando la lingua', 'si sta gonfiando la gola', 'mi si gonfia la lingua', 'mi si gonfia la gola', 'lingua che si gonfia', 'gola che si gonfia', 'difficolta di respiro', 'fatica a respirare', 'respiro male', 'respira male', 'respiro a fatica', 'mi manca il respiro', 'mi manca il fiato', 'manca il fiato', 'mi manca l aria', 'affanno improvviso', 'senza fiato', 'labbra blu', 'labbra viola', 'si sta soffocando', 'sta soffocando', 'mi sto soffocando', 'soffocamento', 'gola che si chiude', 'la gola si chiude', 'lingua gonfia', 'gola gonfia', 'shock anafilattico', 'anafilassi', 'reazione allergica grave', 'reazione anafilattica',
      // neurologico / ictus / coscienza
      'ho un ictus', 'sta avendo un ictus', 'sospetto ictus', 'credo sia un ictus', 'penso sia un ictus', 'sembra un ictus', 'ictus in corso', 'bocca storta', 'faccia storta', 'viso storto', 'volto storto', 'faccia che cade', 'viso che cade', 'non muove il braccio', 'non muove la gamba', 'non muove piu il braccio', 'non muove piu la gamba', 'non riesce a muovere il braccio', 'non riesce a muovere la gamba', 'un lato del corpo', 'un lato del viso', 'non riesco a parlare', 'non riesce a parlare', 'parla male', 'parlo male', 'parole confuse', 'ha perso la parola', 'difficolta a parlare', 'difficolta nel parlare', 'non muovo il braccio', 'non riesco a muovere il braccio', 'non riesco a muovere la gamba', 'paralisi', 'paralizzato', 'paralizzata', 'meta del corpo', 'ho perso la vista', 'ha perso la vista', 'non vedo piu da un occhio', 'perdita improvvisa della vista',
      'mal di testa improvviso', 'improvviso mal di testa', 'mal di testa fortissimo', 'mal di testa atroce', 'mal di testa lancinante', 'mal di testa violentissimo', 'il peggior mal di testa', 'peggior mal di testa della mia vita', 'mal di testa mai avuto', 'mal di testa che non avevo mai avuto', 'cefalea improvvisa', 'cefalea fortissima', 'trauma cranico',
      'convulsioni', 'crisi epilettica', 'attacco epilettico', 'sta avendo una crisi', 'sta convulsionando', 'ho perso i sensi', 'ha perso i sensi', 'ho perso conoscenza', 'ha perso conoscenza', 'sono svenuto', 'sono svenuta', 'e svenuto', 'e svenuta', 'svenimento', 'collasso', 'incosciente', 'privo di sensi', 'priva di sensi', 'non risponde', 'non si sveglia', 'non reagisce', 'confusione improvvisa', 'e confuso all improvviso', 'e diventato confuso', 'e diventata confusa',
      // sangue
      'emorragia', 'non smette di sanguinare', 'non si ferma il sangue', 'sangue che non si ferma', 'sanguinamento che non si ferma', 'sanguina e non si ferma', 'perdo molto sangue', 'perde molto sangue', 'sangue dal naso che non si ferma', 'vomito sangue', 'ho vomitato sangue', 'vomitato sangue', 'sangue nel vomito', 'vomito con sangue', 'perdite di sangue in gravidanza', 'sanguino in gravidanza', 'sanguinamento in gravidanza', 'ho perdite di sangue e sono incinta', 'perdite di sangue abbondanti', 'perdite abbondanti di sangue', 'incinta e ho perdite', 'incinta e perdo sangue', 'incinta e sanguino', 'incinta e ho dolori forti', 'in gravidanza e ho perdite', 'in gravidanza e perdo sangue', 'perdite ematiche abbondanti',
      // gravidanza / neonato
      'non sento muoversi il bambino', 'non sento piu muoversi il bambino', 'non sento piu il bambino', 'il bambino non si muove piu', 'neonato con la febbre', 'neonata con la febbre', 'febbre in un neonato', 'febbre nel neonato', 'neonato con febbre', 'neonata con febbre', 'bimbo di pochi mesi con la febbre', 'bimba di pochi mesi con la febbre', 'neonato ha la febbre', 'neonata ha la febbre', 'neonato ha febbre', 'neonata ha febbre', 'neonato e la febbre', 'il mio neonato ha la febbre', 'la mia neonata ha la febbre', 'di pochi giorni ha la febbre', 'di un mese ha la febbre', 'di due mesi ha la febbre', 'di tre mesi ha la febbre', 'di pochi mesi ha la febbre', 'neonato che non mangia', 'neonato che non respira',
      // intossicazione / trauma grave / ustioni
      'overdose', 'avvelenamento', 'avvelenato', 'avvelenata', 'intossicazione grave', 'ha ingerito', 'ho ingerito troppe', 'ho preso troppe pastiglie', 'ho preso troppe compresse', 'ho preso troppi farmaci', 'ha bevuto la candeggina', 'ha bevuto un detersivo', 'ha ingoiato un', 'ha ingoiato una', 'ha ingoiato la', 'ha inghiottito un', 'ha inghiottito una',
      'incidente grave', 'incidente stradale grave', 'caduta dall alto', 'frattura esposta', 'osso che spunta', 'si vede l osso', 'ustione grave', 'ustione estesa', 'folgorato', 'folgorata', 'annegato', 'annegata', 'colpo di calore', 'morso di vipera', 'morso di serpente',
      // psichiatria: rischio suicidario
      'voglio farla finita', 'farla finita', 'voglio morire', 'ho pensieri suicidi', 'pensieri suicidi', 'pensieri di suicidio', 'pensiero di suicidio', 'voglio togliermi la vita', 'togliermi la vita', 'non voglio piu vivere', 'mi voglio uccidere', 'voglio uccidermi', 'voglio ammazzarmi', 'mi ammazzo', 'suicidio', 'mi voglio fare del male', 'mi faccio del male', 'voglio farmi del male',
      // sensazioni di morte imminente
      'sto morendo', 'mi sento morire', 'sto per morire', 'credo di morire', 'penso di morire',
    ],
    // HIGH: urgenza clinica (da priorità allo staff, non necessariamente 112).
    high: [
      'dolore fortissimo', 'dolore forte', 'dolore insopportabile', 'dolore atroce', 'dolore lancinante', 'male cane', 'non resisto al dolore', 'non dormo per il dolore', 'non riesco a dormire per il dolore', 'dolore che non passa', 'non ce la faccio piu', 'non sopporto piu', 'un dolore terribile', 'mi fa un male terribile',
      'e urgente', 'urgentissimo', 'molto urgente', 'con urgenza', 'devo essere visto subito', 'serve un medico subito', 'emergenza', 'ho un emergenza',
      'febbre alta', 'febbre molto alta', 'febbre che non scende', 'febbre che non passa', 'febbre da tre giorni', 'febbre da quattro giorni', 'febbre da cinque giorni', 'febbre da una settimana', 'febbre a 39', 'febbre a 40', 'febbre a 41', 'febbre 39', 'febbre 40', '39 di febbre', '40 di febbre', '39 e mezzo di febbre', 'febbre a trentanove', 'febbre a quaranta', 'brividi e febbre', 'febbre e rigidita del collo', 'rigidita nucale', 'collo rigido e febbre',
      'dolore forte alla pancia', 'dolore fortissimo alla pancia', 'dolore forte all addome', 'pancia dura', 'addome rigido', 'addome duro', 'dolore forte allo stomaco', 'colica', 'colica renale', 'colica biliare',
      'vomito continuo', 'vomito da giorni', 'vomito da due giorni', 'non riesce a bere', 'non riesco a bere', 'non trattiene niente', 'disidratato', 'disidratata', 'disidratazione', 'sangue nelle feci', 'sangue nelle urine', 'feci nere', 'sangue dal retto', 'urine scure', 'non riesco a urinare', 'non riesco a fare la pipi', 'non urina da', 'tosse con sangue', 'sputo sangue', 'sputo con sangue', 'ho sputato sangue',
      'tachicardia improvvisa', 'battito molto veloce', 'cuore che batte fortissimo', 'pressione altissima', 'crisi ipertensiva', 'pressione a 200', 'pressione a 190', 'mi sento svenire', 'sto per svenire', 'quasi svenuto', 'quasi svenuta', 'ipoglicemia', 'coma diabetico', 'glicemia altissima', 'glicemia molto alta',
      'reazione allergica', 'viso gonfio', 'bruciore al petto', 'faccia gonfia', 'labbra gonfie', 'occhi gonfi', 'gonfiore al viso', 'gonfiore alle labbra', 'orticaria diffusa', 'puntura di vespa e', 'punto da una vespa', 'punto da un ape', 'morso di cane', 'morso di zecca',
      'ferita profonda', 'taglio profondo', 'ferita e profonda', 'taglio e profondo', 'sanguina molto', 'sanguina tanto', 'sanguina parecchio', 'sanguino molto', 'sanguina abbondantemente', 'perdite di sangue', 'mi ha morso un cane', 'mi hanno morso un cane', 'un cane mi ha morso', 'morso da un cane', 'morso da un animale', 'morso di un cane', 'mi ha morsicato', 'ha morso mio figlio', 'ha morso mia figlia', 'ferita che sanguina molto', 'ferita aperta', 'ho bisogno dei punti', 'servono i punti', 'dare i punti', 'ferita infetta', 'pus', 'ferita gonfia e rossa', 'ferita calda',
      'trauma', 'sono caduto', 'sono caduta', 'e caduto', 'e caduta', 'caduto dalle scale', 'caduta dalle scale', 'caduto dalla bici', 'caduta in bici', 'dopo una caduta', 'ho battuto la testa', 'ha battuto la testa', 'botta in testa', 'botta forte', 'incidente stradale', 'incidente in moto', 'incidente in auto', 'incidente in macchina', 'sospetta frattura', 'sospetto una frattura', 'credo di essermi rotto', 'credo di essermi rotta', 'penso di essermi rotto', 'penso di essermi rotta', 'braccio deformato', 'gamba deformata', 'arto deformato', 'non riesco ad appoggiare il piede', 'non riesco ad appoggiare la gamba',
      'perdita di forza', 'ho perso forza', 'perdita di sensibilita', 'non sento piu la gamba', 'non sento piu il braccio', 'formicolio a un braccio e al viso', 'vedo doppio', 'vedo lampi', 'dolore forte all occhio', 'trauma all occhio', 'ho qualcosa nell occhio',
      'polpaccio gonfio e rosso', 'polpaccio gonfio e caldo', 'gamba gonfia e rossa', 'gamba gonfia e calda', 'gamba rossa e calda', 'trombosi', 'petecchie', 'macchie viola e febbre',
      'attacco di panico forte', 'non riesco a calmarmi', 'allucinazioni', 'sento le voci', 'ha smesso di mangiare', 'non mangia da giorni', 'non beve da',
      'bambino con la febbre alta', 'bimbo con la febbre alta', 'bambina con la febbre alta', 'bimba con la febbre alta', 'bambino con febbre alta', 'bimbo con febbre alta', 'bambino che non si sveglia bene', 'molto sonnolento', 'molto sonnolenta',
    ],
    // MEDIUM: disturbo che merita priorità ma non urgenza clinica.
    medium: [
      'la febbre', 'ho febbre', 'ha febbre', 'di febbre', 'con febbre', 'febbre da', 'febbre alta', 'febbricola', 'tosse', 'mal di gola', 'mal di testa', 'emicrania', 'mal di schiena', 'mal di pancia', 'mal di stomaco', 'nausea', 'vomito', 'diarrea', 'capogiri', 'vertigini', 'giramenti di testa', 'mi gira la testa',
      'dolore', 'dolori', 'mi fa male', 'mi fanno male', 'male alla', 'male al', 'dolorante', 'fitta', 'fitte', 'bruciore', 'prurito', 'eruzione cutanea', 'macchie sulla pelle', 'orticaria', 'gonfio', 'gonfia', 'gonfiore', 'palpitazioni', 'battito irregolare', 'pressione alta', 'pressione bassa', 'formicolio', 'stanchezza', 'spossatezza', 'insonnia', 'ansia', 'attacco di panico', 'attacchi di panico', 'crisi di panico', 'infiammazione', 'ferita', 'ustione', 'distorsione', 'storta', 'puntura di zecca', 'cistite', 'otite', 'sinusite', 'bronchite', 'non mi sento bene', 'sto male',
    ],
  },

  escalation_rules: {
    handoff_triggers: [
      'parlare con una persona', 'parlare con un operatore', 'parlare con qualcuno', 'parlare con il dottore', 'parlare con la dottoressa', 'parlare con il medico', 'parlare con la segretaria', 'parlare con la segreteria', 'parlare con un umano',
      'voglio una persona', 'passatemi qualcuno', 'mi passate qualcuno', 'mi passi qualcuno', 'chiamatemi', 'richiamatemi', 'mi richiamate', 'mi chiamate', 'mi potete richiamare', 'mi puo richiamare', 'mi puoi richiamare', 'mi richiami', 'mi richiama', 'mi richiamano', 'richiamarmi', 'farmi richiamare', 'far richiamare', 'mi chiami', 'mi potete chiamare', 'mi puo chiamare', 'mi puoi chiamare', 'mi telefonate', 'mi puo telefonare', 'mi contattate', 'mi puo contattare', 'potete richiamarmi', 'essere richiamato', 'essere richiamata', 'non sei una persona', 'sei un robot', 'sei un bot', 'sei una macchina',
      'operatore', 'persona vera', 'persona reale',
    ],
    max_unknown_turns: 2,
    sensitive_insist: 2,
    messaggio_handoff: 'Certo, passo subito la sua richiesta a una persona dello studio, che la ricontatterà il prima possibile.',
  },

  safety_rules: {
    sensibile: true,
    // Richieste del paziente che equivalgono a chiedere diagnosi, farmaci, interpretazione di esami, prognosi.
    diagnosi_patterns: [
      // diagnosi
      'che cosa ho', 'che cos ho', 'dimmi cosa ho', 'dimmi almeno cosa ho', 'mi dica cosa ho', 'cosa potrebbe essere', 'cosa puo essere', 'che cosa puo essere', 'che cosa potrebbe essere', 'cosa sara', 'che cosa sara',
      'secondo te ho', 'secondo lei ho', 'secondo voi ho', 'secondo te e', 'secondo lei e', 'secondo voi e', 'secondo te sara', 'secondo lei sara', 'potrebbe essere un', 'potrebbe essere una', 'sara un infarto', 'sara un tumore', 'e un tumore', 'sara un tumore', 'e un infarto', 'sara covid', 'sara influenza', 'e un influenza', 'e influenza', 'e una bronchite', 'e un virus', 'sara un virus', 'e covid', 'e una gastrite', 'secondo te cos e', 'secondo lei cos e', 'secondo voi cos e', 'secondo te che cos e', 'secondo lei che cos e', 'e una polmonite', 'e un allergia', 'sara un allergia', 'e un infezione', 'sara un infezione',
      'secondo voi cosa ho', 'secondo te cosa ho', 'secondo lei cosa ho', 'cosa mi sta succedendo', 'cosa mi succede', 'che malattia ho', 'che problema ho', 'che disturbo ho', 'dammi una diagnosi', 'dammi la diagnosi', 'darmi una diagnosi', 'darmi la diagnosi', 'dimmi la diagnosi', 'fammi una diagnosi', 'mi fate una diagnosi', 'mi fai una diagnosi', 'mi diagnostica', 'diagnosticarmi', 'diagnosticare', 'diagnosi',
      // gravità / triage
      'e grave', 'e pericoloso', 'e normale che', 'devo preoccuparmi', 'mi devo preoccupare', 'e preoccupante', 'e serio', 'cosa grave', 'cosa seria', 'devo andare al pronto soccorso', 'devo andare in pronto soccorso', 'serve il pronto soccorso', 'devo chiamare il 118', 'posso aspettare', 'posso aspettare fino a', 'si puo aspettare', 'devo operarmi', 'mi devo operare', 'serve operarmi',
      // interpretazione di esami e referti
      'cosa significa il referto', 'cosa vuol dire il referto', 'cosa dice il referto', 'cosa dicono le analisi', 'cosa dice la risonanza', 'cosa dice la tac', 'cosa dice l ecografia', 'cosa dice l ecg', 'mi spiega il referto', 'mi spieghi il referto', 'mi spiegate il referto', 'mi spiega le analisi', 'mi spieghi le analisi', 'mi spiegate le analisi', 'leggere il referto', 'leggere le analisi', 'leggere la risonanza', 'interpretare il referto', 'interpretare le analisi', 'interpreti le analisi', 'valori alti', 'valori fuori norma', 'valori sono normali', 'valori sono alti', 'valori sono a posto', 'sono normali le analisi', 'sono a posto le analisi', 'analisi a posto', 'se e tutto ok', 'se e tutto a posto', 'se e tutto normale', 'se e tutto nella norma', 'se va tutto bene', 'esami a posto', 'esami sono ok', 'esami sono a posto', 'analisi sono ok', 'analisi ok', 'cosa significa questo valore', 'cosa vuol dire questo valore', 'cosa significa questo risultato', 'cosa vuol dire questo risultato', 'sono nella norma', 'colesterolo alto', 'glicemia alta',
      // farmaci e dosaggi
      'cosa posso prendere', 'che cosa posso prendere', 'che farmaco', 'che medicina', 'quale medicina', 'quale farmaco', 'che pillola', 'devo prendere un antibiotico', 'posso prendere un antibiotico', 'antibiotico', 'antibiotici', 'antinfiammatorio', 'antinfiammatori', 'antidolorifico', 'antidolorifici', 'antistaminico', 'antipiretico', 'ibuprofene', 'paracetamolo', 'tachipirina', 'aspirina', 'moment', 'nurofen', 'brufen', 'oki', 'aulin', 'voltaren', 'amoxicillina', 'augmentin', 'cortisone', 'bentelan', 'sciroppo', 'xanax', 'lexotan', 'tranquillanti', 'sonniferi', 'sonnifero', 'melatonina', 'integratore', 'integratori', 'vitamina d', 'insulina', 'anticoagulanti', 'pillola anticoncezionale', 'pillola del giorno dopo', 'viagra',
      'dosaggio', 'quante compresse', 'quante pastiglie', 'quante gocce', 'quante volte al giorno', 'ogni quante ore', 'posso associare', 'posso interrompere la terapia', 'posso sospendere la terapia', 'posso smettere di prendere', 'sospendere la cura', 'interrompere la cura', 'devo smettere di prendere', 'cambiare dosaggio', 'aumentare la dose', 'raddoppiare la dose', 'scaduto da', 'effetti collaterali', 'controindicazioni',
      // consigli generici e prognosi
      'che cura devo fare', 'mi consigli una cura', 'mi consiglia una cura', 'cosa mi consigli di fare', 'cosa mi consiglia', 'cosa mi consigliate', 'consiglia di fare', 'cosa devo fare per il dolore', 'cosa devo fare per la febbre', 'cosa devo fare per la tosse', 'cosa posso fare per il dolore', 'cosa posso fare per la febbre', 'cosa posso fare per stare meglio', 'cosa faccio nel frattempo', 'cosa devo fare nel frattempo', 'rimedi', 'rimedio', 'rimedi naturali', 'cura fai da te',
      'guarisco', 'guarire', 'guarigione', 'guariro', 'mi passa', 'passera', 'quanto tempo ci metto a guarire', 'in quanto tempo guarisco', 'tra quanto sto bene', 'mi garantite', 'garantite che', 'me lo assicura', 'me lo assicurate', 'me lo garantite', 'me lo garantisce', 'mi assicurate', 'mi assicura', 'sono contagioso', 'sono contagiosa', 'e contagioso', 'e contagiosa', 'posso andare al lavoro', 'posso andare a scuola', 'posso fare sport', 'posso allenarmi', 'posso viaggiare', 'posso guidare',
    ],
    // Frasi che la RISPOSTA del modello non deve mai contenere (verificaRisposta).
    vietato: [
      'ha l influenza', 'hai l influenza', 'ha un infezione', 'hai un infezione', 'ha una polmonite', 'e un allergia', 'si tratta di una', 'si tratta di un', 'e sicuramente', 'probabilmente e', 'probabilmente si tratta', 'sembra proprio',
      'prenda un antibiotico', 'prendi un antibiotico', 'prenda un antinfiammatorio', 'prendi un antinfiammatorio', 'assuma', 'assumere', 'le consiglio di prendere', 'ti consiglio di prendere', 'prenda ibuprofene', 'prenda tachipirina', 'prenda un antidolorifico', 'prenda paracetamolo', 'sospenda la terapia', 'sospendi la terapia', 'interrompa la terapia', 'mg', 'milligrammi', 'compresse al giorno', 'gocce al giorno',
      'i suoi valori sono', 'i tuoi valori sono', 'le analisi sono a posto', 'le analisi sono normali', 'il referto indica', 'il referto dice', 'dal referto risulta', 'e nella norma', 'sono nella norma', 'valori nella norma',
      'le faremo la ricetta', 'le prescriviamo', 'le rilasciamo il certificato', 'le faremo il certificato', 'riceverete la ricetta', 'la ricetta sara pronta', 'il certificato sara pronto', 'le rinnoviamo la terapia',
      'guarira', 'guarirai', 'guarisce', 'tornera come prima', 'convenzionati con tutte', 'convenzionati con tutti', 'accettiamo tutte le assicurazioni', 'tutte le assicurazioni',
      'non e grave', 'non e nulla', 'non e niente', 'non si preoccupi', 'non ti preoccupare', 'non preoccuparti', 'puo aspettare', 'puoi aspettare', 'nulla di grave', 'niente di grave', 'solo stress',
    ],
    messaggio_sicurezza: 'Non posso dare diagnosi né valutazioni sui sintomi, e nemmeno consigli su farmaci, terapie o esami: serve il medico, che potrà visitarla. Se pensa che sia urgente o ha sintomi gravi, chiami subito il 112 o il 118. Se vuole, la aiuto subito a fissare un appuntamento.',
    messaggio_emergenza: 'Capisco, la situazione potrebbe essere seria e non va gestita via chat. Chiami subito il 112 o il 118, oppure si rechi al pronto soccorso più vicino. Se lei o qualcuno vicino a lei è in pericolo immediato, non aspetti una risposta qui. Avviso immediatamente lo studio.',
  },

  response_rules: { max_frasi: 3, una_domanda_per_messaggio: true, emoji: 'mai' },

  default_questions: {
    prestazione: ['Che tipo di visita o prestazione le serve?', 'Per cosa vorrebbe venire: una visita, un esame, un controllo?', 'Mi dica pure di cosa ha bisogno.'],
    nome_paziente: ['Come si chiama?', 'Mi dice il suo nome, così preparo la richiesta?', 'A che nome registro la richiesta?'],
    sintomo: ['Mi racconta che disturbo ha?', 'Che cosa la preoccupa, esattamente?', 'Può descrivermi brevemente il problema?'],
    urgenza: ['Il disturbo è forte o riesce a gestirlo?', 'È molto intenso oppure sopportabile?'],
  },

  common_scenarios: [
    'Prenotazione di una visita generale, specialistica o di un esame (prestazione nota)',
    'Disturbo o sintomo non urgente: raccolta dati e passaggio allo staff, senza valutazione clinica',
    'Segnali di emergenza (petto, respiro, ictus, coscienza, emorragia, anafilassi, rischio suicidario): 112/118 e avviso immediato',
    'Ricette, impegnative, rinnovi di terapia e certificati: passaggio a segreteria/medico, nessuna promessa',
    'Referti: solo come e quando ritirarli, mai interpretarli',
    'Richieste di diagnosi, farmaci, dosaggi o prognosi: risposta di sicurezza e proposta di appuntamento',
    'Prezzi, orari, convenzioni, SSN: solo da dati del tenant',
    'Spostamenti, annullamenti, reclami: passaggio a una persona',
  ],

  confidence_thresholds: { intent_min: 0.55, intent_ok: 0.8 },
};

// FAQ di SETTORE: conoscenza generale, valida per qualunque studio medico.
// Nessun prezzo, orario, nome o indirizzo, nessun consiglio clinico: quello
// che dipende dallo studio sta solo nei dati del tenant.
const f = (intent, domanda_canonica, varianti, risposta_base) => ({ intent, domanda_canonica, varianti, risposta_base, condizioni: {} });

export const faq = [
  f('info_prestazioni', 'Cosa si fa nella prima visita?', ['come funziona la prima visita', 'cosa succede alla prima visita', 'cosa comprende la prima visita', 'cosa si fa alla prima visita'],
    'In genere il medico raccoglie la storia clinica (disturbi, malattie passate, terapie in corso), esegue la visita e, se lo ritiene utile, indica eventuali esami o controlli. Il percorso dipende dal singolo caso.'),
  f('info_prestazioni', 'Cosa devo portare alla visita?', ['cosa devo portare alla visita medica', 'cosa porto alla visita', 'cosa serve portare dal medico', 'cosa portare alla prima visita'],
    'In genere è utile portare un documento di identità, la tessera sanitaria, eventuali esami e referti precedenti e l\'elenco dei farmaci che assume. Per altre indicazioni verifichi con lo studio.'),
  f('info_documenti', 'Serve l\'impegnativa per fare una visita?', ['serve la prescrizione per la visita specialistica', 'devo avere l impegnativa', 'serve l impegnativa del medico', 'ci vuole l impegnativa'],
    'Dipende dal tipo di prestazione e dalla modalità di accesso (con il Servizio Sanitario Nazionale o in forma privata): per sapere se serve l\'impegnativa nel suo caso conviene verificare con lo studio.'),
  f('info_prestazioni', 'Che differenza c\'è tra medico di base e specialista?', ['medico di base o specialista', 'differenza tra medico di famiglia e specialista', 'a chi mi devo rivolgere medico o specialista', 'quando serve lo specialista'],
    'Il medico di base segue il paziente in modo generale e può indirizzarlo agli specialisti; lo specialista è un medico che si occupa di un\'area precisa (per esempio cuore, pelle o ossa). Quale sia la figura giusta per lei lo valuta il medico.'),
  f('info_prestazioni', 'Come ci si prepara a un prelievo del sangue?', ['serve il digiuno per il prelievo', 'devo essere a digiuno per le analisi', 'come mi preparo alle analisi del sangue', 'preparazione per le analisi'],
    'La preparazione dipende dagli esami richiesti: alcuni richiedono il digiuno, altri no. Meglio seguire le indicazioni date dallo studio o dal medico per gli esami specifici e chiedere conferma in caso di dubbio.'),
  f('info_prestazioni', 'Come ci si prepara a un\'ecografia?', ['serve preparazione per l ecografia', 'come mi preparo all ecografia', 'devo fare qualcosa prima dell ecografia', 'ecografia a digiuno'],
    'La preparazione varia a seconda del tipo di ecografia (per alcune serve il digiuno o la vescica piena, per altre nulla): lo studio comunica le indicazioni specifiche al momento della prenotazione.'),
  f('info_prestazioni', 'Cos\'è un elettrocardiogramma?', ['cos e l ecg', 'a cosa serve l elettrocardiogramma', 'come funziona l ecg', 'in cosa consiste l ecg', 'fa male l ecg'],
    'L\'elettrocardiogramma registra l\'attività elettrica del cuore con degli elettrodi appoggiati sulla pelle: è un esame non invasivo. Se e quando farlo lo decide il medico.'),
  f('info_prestazioni', 'Cos\'è l\'holter?', ['cos e l holter', 'come funziona l holter', 'cos e l holter cardiaco', 'cos e l holter pressorio', 'in cosa consiste l holter'],
    'L\'holter è un apparecchio portatile che registra per un periodo prolungato, durante la vita di tutti i giorni, il battito del cuore o la pressione. Indicazioni e durata le dà il medico.'),
  f('info_prestazioni', 'Come funziona il teleconsulto?', ['cos e la televisita', 'come funziona la visita online', 'si puo fare la visita in videochiamata', 'come funziona la visita da remoto'],
    'Il teleconsulto è un colloquio con il medico a distanza, in videochiamata o per telefono. Non sostituisce sempre la visita di persona: se è disponibile e adatto al suo caso lo indicano lo studio e il medico.'),
  f('info_prestazioni', 'Come funziona la visita a domicilio?', ['si puo avere il medico a casa', 'fate visite a domicilio come funziona', 'visita domiciliare come si richiede', 'come si richiede la visita a casa'],
    'La visita a domicilio, quando è offerta dallo studio, si richiede alla segreteria indicando chi deve essere visitato e il motivo. Disponibilità e modalità dipendono dallo studio; per un\'emergenza non va usata: in quel caso si chiama il 112 o il 118.'),
  f('info_referti', 'Come si ritirano i referti?', ['come ritiro il referto', 'dove ritiro i referti', 'come posso avere i risultati degli esami', 'si possono ritirare i referti online', 'posso farli ritirare a un altro'],
    'I referti si ritirano in genere allo sportello oppure, se lo studio lo prevede, online o per posta elettronica. Per il ritiro da parte di un\'altra persona di solito serve una delega con un documento: modalità e tempi li comunica lo studio.'),
  f('info_referti', 'Il medico mi spiega i risultati degli esami?', ['chi mi spiega gli esami', 'chi legge il referto', 'posso farmi spiegare le analisi', 'chi interpreta i risultati'],
    'I referti vengono letti e commentati dal medico durante una visita o un colloquio con lui: via chat non è possibile interpretarli, ma lo staff può aiutarla a fissare un appuntamento.'),
  f('richiesta_certificato', 'Chi rilascia i certificati medici?', ['chi fa il certificato di malattia', 'come si ottiene un certificato medico', 'serve una visita per il certificato', 'certificato medico come si richiede'],
    'Un certificato medico lo rilascia il medico, di norma dopo averla visitata e valutato il caso. La richiesta passa alla segreteria o al medico, che indicano come procedere: non è possibile garantirne il rilascio in anticipo.'),
  f('richiesta_ricetta', 'Come si richiede una ricetta?', ['come richiedo una ricetta', 'come si rinnova una ricetta', 'come rinnovo la terapia', 'come si chiede un impegnativa', 'modalita per richiedere una ricetta'],
    'Ricette, rinnovi di terapia e impegnative vengono valutati e prescritti dal medico. La richiesta passa alla segreteria o al medico, che indicano le modalità; non è possibile garantirne il rilascio in anticipo.'),
  f('info_pagamenti', 'Che differenza c\'è tra visita con il servizio sanitario e visita privata?', ['visita privata o con il ssn', 'differenza tra ssn e privato', 'visita mutuabile o privata', 'cosa cambia tra ticket e visita privata'],
    'Le prestazioni con il Servizio Sanitario Nazionale seguono regole proprie (impegnativa, eventuale ticket, tempi di accesso); quelle private sono pagate direttamente dal paziente e possono, a certe condizioni, essere detraibili o rimborsate da assicurazioni e fondi. Cosa offre lo studio e a quali condizioni lo comunica lo studio.'),
  f('info_pagamenti', 'Le spese mediche si possono detrarre?', ['la visita e detraibile', 'posso detrarre la visita nel 730', 'fattura sanitaria per la detrazione', 'spese mediche detraibili'],
    'Molte spese sanitarie sono detraibili dalla dichiarazione dei redditi se documentate con fattura o ricevuta nominativa e pagate con i mezzi previsti. Per i dettagli conviene rivolgersi a un commercialista; lo studio può dire quali documenti rilascia.'),
  f('info_pagamenti', 'Posso farmi rimborsare la visita dall\'assicurazione?', ['rimborso assicurazione sanitaria', 'la mia assicurazione copre la visita', 'fondo sanitario rimborsa la visita', 'visita rimborsabile'],
    'Il rimborso dipende dalla polizza o dal fondo sanitario del paziente: per sapere cosa è coperto serve rivolgersi alla propria assicurazione. Lo studio può dire quali documenti rilascia e se esistono convenzioni attive.'),
  f('info_prestazioni', 'Si può venire accompagnati?', ['posso venire con un accompagnatore', 'posso portare mia figlia in visita', 'un minorenne puo venire da solo', 'devo venire con un genitore', 'posso farmi accompagnare'],
    'In genere è possibile farsi accompagnare. Per i minorenni, di norma, serve la presenza di un genitore o di chi ne ha la responsabilità; per i dettagli verifichi con lo studio.'),
  f('info_prestazioni', 'Cosa fare in caso di emergenza?', ['e una emergenza cosa devo fare', 'cosa devo fare se sto molto male', 'quando chiamare il 118', 'quando devo andare al pronto soccorso', 'a chi mi rivolgo in caso di emergenza'],
    'In caso di emergenza (per esempio forte dolore al petto, difficoltà a respirare, perdita di coscienza, segni di ictus, emorragia importante) si chiama subito il 112 o il 118 o ci si reca al pronto soccorso, senza attendere una risposta in chat. Per i disturbi non urgenti si contatta lo studio o il servizio di continuità assistenziale (guardia medica) della propria zona.'),
  f('info_prestazioni', 'Il medico può dirmi per telefono o in chat cosa ho?', ['mi potete dire cosa ho via chat', 'posso avere una diagnosi su whatsapp', 'il medico risponde ai sintomi in chat', 'posso avere un consulto su whatsapp'],
    'Questa chat serve per appuntamenti e informazioni: non è possibile fare diagnosi né dare consigli su cure o farmaci a distanza. Per una valutazione serve la visita con il medico; lo staff può aiutarla a fissarla.'),
  f('info_prestazioni', 'I miei dati sanitari sono protetti?', ['privacy dei dati sanitari', 'come vengono trattati i miei dati medici', 'chi vede la mia cartella clinica', 'la privacy e garantita', 'consenso al trattamento dei dati'],
    'I dati sanitari sono dati particolarmente protetti e vengono trattati secondo la normativa sulla privacy, con un\'informativa e il consenso del paziente. Per i dettagli sul trattamento nello specifico studio si può chiedere l\'informativa alla segreteria.'),
  f('info_prestazioni', 'Quando va fatto un check up?', ['ogni quanto si fa il check up', 'a cosa serve il check up', 'ogni quanto controllo generale', 'cos e un check up', 'serve fare il check up'],
    'Un check up è un insieme di controlli ed esami di prevenzione; quali e con quale frequenza dipende da età, storia clinica e fattori di rischio. Lo stabilisce il medico in visita.'),
  f('info_prestazioni', 'Cos\'è la visita per l\'idoneità sportiva?', ['come funziona la visita sportiva', 'idoneita sportiva cos e', 'cosa comprende la visita per l idoneita', 'visita agonistica cos e', 'differenza tra agonistica e non agonistica'],
    'È una visita medica che accerta l\'idoneità a svolgere un\'attività sportiva; esami e documenti richiesti cambiano se l\'attività è agonistica o non agonistica. L\'idoneità è un giudizio del medico e non può essere garantita in anticipo.'),
  f('info_prestazioni', 'Posso vaccinarmi in studio?', ['fate i vaccini', 'dove si fa il vaccino', 'come si prenota un vaccino', 'vaccino antinfluenzale dove', 'i vaccini si fanno qui'],
    'Alcune vaccinazioni vengono eseguite da studi medici e da servizi dedicati, altre solo presso strutture specifiche. Se e quali vengano offerte lo comunica lo studio; l\'indicazione clinica la dà il medico.'),
];
