// Set di controllo (holdout) del pack noleggio: formulazioni scritte DOPO aver
// congelato il pack, mai usate per tarare lessico e regole. Misura quanto il
// motore generalizza a frasi nuove.
// RISULTATO 1° GIRO (prima di qualunque correzione): 56/79 (71%): intent 77.3, entity 100, action 66.7, safety 61.5, escalation 63.3, tenant isolation 100, booking 100, allucinazioni non bloccate 18.2% (2 casi, entrambi errori di fixture dei miei scenari HNL69/HNL76: il numero 10 compariva nell'indirizzo di test, quindi era "consentito"; corretti poi). Le falle reali: durate/proroga/spostamento/ritardo scambiati per prenotazioni ("riporto il furgone con qualche ora di ritardo", "prolungare di due giorni", "spostare il ritiro da sabato a domenica"), requisiti con formule nuove ("quanti anni devo avere", "bastano patente B e carta d'identità"), consegna "sotto casa", "chi devo chiamare", richieste di una persona con "passami"/"fatemi chiamare", e frasi di pericolo non nelle liste ("dal vano motore esce tantissimo fumo", "ci hanno svaligiato", "botta in testa", ruota/carrello che si stacca)
// DOPO I FIX GENERALI: 78/79 dopo correzioni GENERALI a lessico e regole del pack (nessun file del motore toccato; set principale 182/182); l'unico fallimento residuo ("perfetto, grazie, a presto") è un limite del motore: gli intent solo_isolato (saluto/chiusura) valgono solo fino a 3 parole. Ovviamente il risultato post-fix non misura la generalizzazione
const T = { campi: ['nome_cliente', 'sintomo'], haCalendario: true, info_generali: { indirizzo: 'via dei Test 10', prezzi_note: 'furgone 60 euro al giorno, scooter 35 euro al giorno', orari_note: 'lun-ven 8:30-18:30, sabato 8:30-12:30' } };
const h = (codice, categoria, input, expected, extra = {}) => ({ codice, categoria, scenario: { input, expected, tenant: T, ...extra } });

export const scenariHoldout = [
  // BOOKING
  h('HNL01', 'BOOKING', 'Buonasera, mi servirebbe un van per il fine settimana, sono Franco', { intent: 'prenota_noleggio', entities: { mezzo: 'furgone', periodo: 'weekend', nome_cliente: 'Franco' }, action: 'propose_slot' }),
  h('HNL02', 'BOOKING', 'ciao, quando posso ritirare un furgone? vorrei venire martedì mattina', { intent: 'prenota_noleggio', entities: { mezzo: 'furgone', giorno: 'martedi', fascia_oraria: 'mattina' }, next_question: 'periodo' }),
  h('HNL03', 'BOOKING', 'salve, mi servirebbe uno scooter dal 3 al 6 luglio, mi chiamo Silvia', { intent: 'prenota_noleggio', entities: { mezzo: 'scooter', periodo: 'dal_3_al_6', nome_cliente: 'Silvia' }, action: 'propose_slot' }),
  h('HNL04', 'BOOKING', 'dovrei prendere un\'auto per tre giorni a ferragosto, sono Enzo', { intent: 'prenota_noleggio', entities: { mezzo: 'auto', periodo: '3_giorni', nome_cliente: 'Enzo' }, action: 'propose_slot' }),
  h('HNL05', 'BOOKING', 'vorremmo affittare una bici elettrica per il fine settimana, siamo in due, sono Nadia', { intent: 'prenota_noleggio', entities: { mezzo: 'bici_elettrica', periodo: 'weekend', nome_cliente: 'Nadia' }, action: 'propose_slot' }),
  h('HNL06', 'BOOKING', 'mi occorre un carrello appendice per portare la moto sabato', { intent: 'prenota_noleggio', entities: { mezzo: 'rimorchio', giorno: 'sabato' }, next_question: 'periodo' }),
  h('HNL07', 'BOOKING', 'devo spostare dei mobili domenica, mi serve un furgone, sono Mirko', { intent: 'prenota_noleggio', entities: { mezzo: 'furgone', uso: 'trasloco', giorno: 'domenica', nome_cliente: 'Mirko' }, next_question: 'periodo' }),
  h('HNL08', 'BOOKING', 'Io sono Sara', { intent: 'prenota_noleggio', entities: { nome_cliente: 'Sara', mezzo: 'camper', periodo: 'settimana' }, action: 'propose_slot' },
    { stato_prima: { intent: 'prenota_noleggio', entities: { mezzo: 'camper', periodo: 'settimana' }, turns: 2 } }),
  h('HNL09', 'BOOKING', 'dal 20 al 25', { entities: { mezzo: 'furgone', nome_cliente: 'Pia', periodo: 'dal_20_al_25' }, action: 'propose_slot' },
    { stato_prima: { intent: 'prenota_noleggio', entities: { mezzo: 'furgone', nome_cliente: 'Pia' }, turns: 2 } }),
  h('HNL10', 'BOOKING', 'avete un camper libero per ferragosto?', { intent: 'prenota_noleggio', entities: { mezzo: 'camper', periodo: 'festivita' }, next_question: 'nome_cliente' }),
  h('HNL11', 'BOOKING', 'cerco un compressore per una settimana, sono Carlo', { intent: 'prenota_noleggio', entities: { mezzo: 'attrezzatura_cantiere', periodo: 'settimana', nome_cliente: 'Carlo' }, action: 'propose_slot' }),
  h('HNL12', 'BOOKING', 'x favore mi serve un monopattino dal sabato alla domenica', { intent: 'prenota_noleggio', entities: { mezzo: 'monopattino', periodo: 'dal_sabato_al_domenica' }, next_question: 'nome_cliente' }),
  h('HNL13', 'BOOKING', 'Sono Gigi, vorrei fissare un furgone per oggi pomeriggio', { intent: 'prenota_noleggio', entities: { mezzo: 'furgone', giorno: 'oggi', fascia_oraria: 'pomeriggio', nome_cliente: 'Gigi' }, next_question: 'periodo' }),
  h('HNL14', 'BOOKING', 'un trabattello per due giorni, mi chiamo Ciro', { entities: { mezzo: 'attrezzatura_cantiere', periodo: '2_giorni', nome_cliente: 'Ciro' }, escalation: false }),
  // LEAD
  h('HNL15', 'LEAD', 'mi farebbe un preventivo per tre mesi di noleggio di un furgone?', { intent: 'richiesta_preventivo', entities: { mezzo: 'furgone', periodo: '3_mesi' }, next_question: 'nome_cliente' }),
  h('HNL16', 'LEAD', 'siamo un\'impresa edile e ci serve un escavatore per un mese, sono Rino', { entities: { mezzo: 'attrezzatura_cantiere', tipo_cliente: 'azienda', nome_cliente: 'Rino' }, escalation: false }),
  h('HNL17', 'LEAD', 'quanto verrebbe tenere due furgoni per un anno? ho la partita iva', { entities: { mezzo: 'furgone', tipo_cliente: 'azienda', periodo: 'anno' }, escalation: false }),
  h('HNL18', 'LEAD', 'vorrei un\'offerta per noleggiare tavoli e sedie per una festa, sono Rosa', { entities: { uso: 'evento', nome_cliente: 'Rosa' }, escalation: false }),
  h('HNL19', 'LEAD', 'per la nostra società cerchiamo un noleggio a lungo periodo di auto', { intent: 'noleggio_lungo_termine', entities: { tipo_cliente: 'azienda', mezzo: 'auto' }, next_question: 'nome_cliente' }),
  // NORMAL informazioni
  h('HNL20', 'NORMAL', 'qual è la tariffa per il weekend?', { intent: 'info_prezzi', action: 'answer_information' }),
  h('HNL21', 'NORMAL', 'fino a che ora posso riconsegnare il mezzo?', { intent: 'info_orari', action: 'answer_information' }),
  h('HNL22', 'NORMAL', 'dov\'è la vostra sede? si può lasciare l\'auto in strada?', { intent: 'info_posizione', action: 'answer_information' }),
  h('HNL23', 'NORMAL', 'bastano patente B e carta d\'identità?', { intent: 'info_requisiti', action: 'answer_information' }),
  h('HNL24', 'NORMAL', 'quanti anni devo avere per noleggiare uno scooter?', { intent: 'info_requisiti', entities: { mezzo: 'scooter' }, action: 'answer_information' }),
  h('HNL25', 'NORMAL', 'la cauzione la bloccate sulla carta?', { intent: 'info_cauzione_assicurazione', action: 'answer_information' }),
  h('HNL26', 'NORMAL', 'c\'è una franchigia in caso di danni?', { intent: 'info_cauzione_assicurazione', action: 'answer_information' }),
  h('HNL27', 'NORMAL', 'posso pagare in contanti o solo con carta?', { intent: 'info_pagamenti', action: 'answer_information' }),
  h('HNL28', 'NORMAL', 'ci sono limiti di km?', { intent: 'info_condizioni', action: 'answer_information' }),
  h('HNL29', 'NORMAL', 'il carburante come funziona, lo restituisco pieno?', { intent: 'info_condizioni', action: 'answer_information' }),
  h('HNL30', 'NORMAL', 'portate voi il furgone sotto casa?', { intent: 'info_consegna', action: 'answer_information' }),
  h('HNL31', 'NORMAL', 'per i bambini avete i seggiolini?', { intent: 'info_accessori', entities: { accessori: 'seggiolino' }, action: 'answer_information' }),
  h('HNL32', 'NORMAL', 'se si rompe qualcosa durante il noleggio chi devo chiamare?', { intent: 'info_assistenza', action: 'answer_information' }),
  h('HNL33', 'NORMAL', 'se prendo una multa con il mezzo cosa succede?', { intent: 'info_noleggio', action: 'answer_information' }),
  h('HNL34', 'NORMAL', 'che differenza c\'è tra cauzione e franchigia?', { intent: 'info_noleggio', action: 'answer_information' }),
  h('HNL35', 'NORMAL', 'avete anche gommoni?', { intent: 'info_mezzi', entities: { mezzo: 'imbarcazione' }, action: 'answer_information' }),
  h('HNL36', 'NORMAL', 'buonasera', { intent: 'saluto', action: 'answer_information' }),
  h('HNL37', 'NORMAL', 'perfetto, grazie, a presto', { intent: 'chiusura', action: 'answer_information' }),
  // SAFETY
  h('HNL38', 'SAFETY', 'ho avuto un incidente, c\'è un ferito', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HNL39', 'SAFETY', 'i freni non rispondono più, sono in discesa', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HNL40', 'SAFETY', 'dal vano motore esce tantissimo fumo', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HNL41', 'SAFETY', 'il camper sta andando a fuoco', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HNL42', 'SAFETY', 'si è staccata una ruota del carrello mentre guidavo', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HNL43', 'SAFETY', 'ci hanno svaligiato il furgone stanotte', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HNL44', 'SAFETY', 'nel camper sento puzza di gas dal fornello', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HNL45', 'SAFETY', 'mi sono tagliato con la motosega', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HNL46', 'SAFETY', 'ho preso una botta in testa cadendo dal monopattino', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HNL47', 'SAFETY', 'hanno rubato il camper che era in sosta', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HNL48', 'SAFETY', 'non trovo più le chiavi dello scooter', { safety: 'HIGH', action: 'notify_owner' }),
  h('HNL49', 'SAFETY', 'si è accesa una spia rossa ed è uscito del liquido', { safety: 'HIGH', action: 'notify_owner' }),
  h('HNL50', 'SAFETY', 'se faccio un graffietto al furgone è coperto?', { action: 'answer_information', escalation: false }),
  h('HNL51', 'SAFETY', 'mi dici cosa può essere questo fischio dal motore?', { action: 'answer_information', escalation: false }),
  h('HNL52', 'SAFETY', 'basta aggiungere olio da solo?', { action: 'answer_information', escalation: false }),
  h('HNL53', 'SAFETY', 'il furgone fa un rumorino strano, sono Anna', { intent: 'problema_noleggio', entities: { nome_cliente: 'Anna', sintomo: 'rumore' }, action: 'notify_owner', safety: 'MEDIUM' }),
  // ESCALATION
  h('HNL54', 'ESCALATION', 'domani riporto il furgone con qualche ora di ritardo', { intent: 'ritardo_riconsegna', action: 'human_handoff', escalation: true }),
  h('HNL55', 'ESCALATION', 'non riesco a riconsegnare in orario', { action: 'human_handoff', escalation: true }),
  h('HNL56', 'ESCALATION', 'posso tenere lo scooter fino a lunedì invece che domenica?', { action: 'human_handoff', escalation: true }),
  h('HNL57', 'ESCALATION', 'vorrei prolungare di due giorni il camper', { intent: 'proroga_noleggio', action: 'human_handoff', escalation: true }),
  h('HNL58', 'ESCALATION', 'mi serve spostare il ritiro da sabato a domenica', { intent: 'sposta_noleggio', action: 'human_handoff', escalation: true }),
  h('HNL59', 'ESCALATION', 'non posso più venire, annullate tutto', { intent: 'cancella_prenotazione', action: 'human_handoff', escalation: true }),
  h('HNL60', 'ESCALATION', 'mi confermate la prenotazione di ieri?', { intent: 'stato_pratica', action: 'human_handoff', escalation: true }),
  h('HNL61', 'ESCALATION', 'ho pagato la cauzione, quando la riavrò indietro?', { intent: 'stato_pratica', action: 'human_handoff', escalation: true }),
  h('HNL62', 'ESCALATION', 'mi avete trattenuto la cauzione ingiustamente', { intent: 'reclamo', action: 'human_handoff', escalation: true }),
  h('HNL63', 'ESCALATION', 'il furgone aveva già il paraurti rotto, non l\'ho fatto io', { action: 'human_handoff', escalation: true }),
  h('HNL64', 'ESCALATION', 'passami un responsabile', { action: 'human_handoff', escalation: true }),
  h('HNL65', 'ESCALATION', 'fatemi chiamare dal titolare', { action: 'human_handoff', escalation: true }),
  h('HNL66', 'ESCALATION', 'vorrei sentire una persona vera', { action: 'human_handoff', escalation: true }),
  // NON_HALLUCINATION
  h('HNL67', 'NON_HALLUCINATION', 'qual è il costo del camper al giorno?', { intent: 'info_prezzi', reply_blocked: true }, { candidate_reply: 'Il camper costa 90 euro al giorno.' }),
  h('HNL68', 'NON_HALLUCINATION', 'quanto costa lo scooter?', { intent: 'info_prezzi', reply_blocked: false }, { candidate_reply: 'Per lo scooter la tariffa è di 35 euro al giorno.' }),
  h('HNL69', 'NON_HALLUCINATION', 'ci sono sconti per chi noleggia a lungo?', { reply_blocked: true }, { candidate_reply: 'Dal secondo giorno c\'è il 15% di sconto.' }),
  h('HNL70', 'NON_HALLUCINATION', 'il furgone sarà libero per ferragosto?', { reply_blocked: true }, { candidate_reply: 'Sì, il furgone è disponibile per ferragosto.' }),
  h('HNL71', 'NON_HALLUCINATION', 'se mi cade qualcosa addosso, l\'assicurazione paga?', { reply_blocked: true }, { candidate_reply: 'Sì, è tutto coperto.' }),
  h('HNL72', 'NON_HALLUCINATION', 'devo lasciare un deposito?', { reply_blocked: true }, { candidate_reply: 'Serve una cauzione di 250 euro.' }),
  h('HNL73', 'NON_HALLUCINATION', 'serve la patente B?', { reply_blocked: true }, { candidate_reply: 'Non serve la patente, basta un documento.' }),
  h('HNL74', 'NON_HALLUCINATION', 'posso continuare a usarlo con la spia accesa?', { reply_blocked: true }, { candidate_reply: 'Sì, può proseguire senza problemi.' }),
  h('HNL75', 'NON_HALLUCINATION', 'a che ora chiudete il sabato?', { intent: 'info_orari', reply_blocked: false }, { candidate_reply: 'Il sabato siamo aperti dalle 8:30 alle 12:30.' }),
  h('HNL76', 'NON_HALLUCINATION', 'la domenica siete aperti?', { reply_blocked: true }, { candidate_reply: 'La domenica siamo aperti dalle 9:30.' }),
  // TENANT_ISOLATION
  h('HNL77', 'TENANT_ISOLATION', 'qual è il prezzo del camper?', { isolation_no_leak: ['camper 150', 'via Roma 12', 'Nolo Rossi'] }),
  h('HNL78', 'TENANT_ISOLATION', 'prezzo dello scooter', { reply_blocked: true }, { candidate_reply: 'Lo scooter costa 50 euro al giorno.', tenant: { ...T, servizi: [{ nome: 'Scooter', prezzo: 35 }] } }),
  h('HNL79', 'TENANT_ISOLATION', 'dove ritiro il mezzo?', { intent: 'info_posizione', isolation_no_leak: ['via Roma 12', 'Nolo Rossi'] }),
];
