// Registro dei pack disponibili (uno per ogni settore di lib/settori.js). Import con percorsi LETTERALI (così il bundler di Vercel include i file).
// Ogni definizione = { ...modulo pack (SETTORE, VERSIONE, CHANGELOG, pack, faq), scenari, scenariHoldout }.
export const SETTORI_DISPONIBILI = ["dentista", "medico", "veterinario", "fisioterapista", "estetista", "parrucchiere", "palestra_personal_trainer", "elettricista", "fabbro", "imbianchino", "giardiniere", "autofficina", "carrozzeria", "gommista", "traslochi", "pulizie", "avvocato", "commercialista", "consulente", "amministratore_condominio", "immobiliare", "agenzia_web_grafica", "fotografo_videomaker", "organizzazione_eventi", "bar_caffetteria", "ristorante", "noleggio", "scuola_guida", "centro_corsi"];

const caricatori = {
  dentista: async () => { const p = await import('./dentista.js'); const s = await import('./dentista.scenari.js'); const h = await import('./dentista.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  medico: async () => { const p = await import('./medico.js'); const s = await import('./medico.scenari.js'); const h = await import('./medico.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  veterinario: async () => { const p = await import('./veterinario.js'); const s = await import('./veterinario.scenari.js'); const h = await import('./veterinario.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  fisioterapista: async () => { const p = await import('./fisioterapista.js'); const s = await import('./fisioterapista.scenari.js'); const h = await import('./fisioterapista.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  estetista: async () => { const p = await import('./estetista.js'); const s = await import('./estetista.scenari.js'); const h = await import('./estetista.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  parrucchiere: async () => { const p = await import('./parrucchiere.js'); const s = await import('./parrucchiere.scenari.js'); const h = await import('./parrucchiere.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  palestra_personal_trainer: async () => { const p = await import('./palestra_personal_trainer.js'); const s = await import('./palestra_personal_trainer.scenari.js'); const h = await import('./palestra_personal_trainer.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  elettricista: async () => { const p = await import('./elettricista.js'); const s = await import('./elettricista.scenari.js'); const h = await import('./elettricista.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  fabbro: async () => { const p = await import('./fabbro.js'); const s = await import('./fabbro.scenari.js'); const h = await import('./fabbro.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  imbianchino: async () => { const p = await import('./imbianchino.js'); const s = await import('./imbianchino.scenari.js'); const h = await import('./imbianchino.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  giardiniere: async () => { const p = await import('./giardiniere.js'); const s = await import('./giardiniere.scenari.js'); const h = await import('./giardiniere.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  autofficina: async () => { const p = await import('./autofficina.js'); const s = await import('./autofficina.scenari.js'); const h = await import('./autofficina.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  carrozzeria: async () => { const p = await import('./carrozzeria.js'); const s = await import('./carrozzeria.scenari.js'); const h = await import('./carrozzeria.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  gommista: async () => { const p = await import('./gommista.js'); const s = await import('./gommista.scenari.js'); const h = await import('./gommista.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  traslochi: async () => { const p = await import('./traslochi.js'); const s = await import('./traslochi.scenari.js'); const h = await import('./traslochi.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  pulizie: async () => { const p = await import('./pulizie.js'); const s = await import('./pulizie.scenari.js'); const h = await import('./pulizie.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  avvocato: async () => { const p = await import('./avvocato.js'); const s = await import('./avvocato.scenari.js'); const h = await import('./avvocato.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  commercialista: async () => { const p = await import('./commercialista.js'); const s = await import('./commercialista.scenari.js'); const h = await import('./commercialista.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  consulente: async () => { const p = await import('./consulente.js'); const s = await import('./consulente.scenari.js'); const h = await import('./consulente.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  amministratore_condominio: async () => { const p = await import('./amministratore_condominio.js'); const s = await import('./amministratore_condominio.scenari.js'); const h = await import('./amministratore_condominio.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  immobiliare: async () => { const p = await import('./immobiliare.js'); const s = await import('./immobiliare.scenari.js'); const h = await import('./immobiliare.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  agenzia_web_grafica: async () => { const p = await import('./agenzia_web_grafica.js'); const s = await import('./agenzia_web_grafica.scenari.js'); const h = await import('./agenzia_web_grafica.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  fotografo_videomaker: async () => { const p = await import('./fotografo_videomaker.js'); const s = await import('./fotografo_videomaker.scenari.js'); const h = await import('./fotografo_videomaker.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  organizzazione_eventi: async () => { const p = await import('./organizzazione_eventi.js'); const s = await import('./organizzazione_eventi.scenari.js'); const h = await import('./organizzazione_eventi.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  bar_caffetteria: async () => { const p = await import('./bar_caffetteria.js'); const s = await import('./bar_caffetteria.scenari.js'); const h = await import('./bar_caffetteria.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  ristorante: async () => { const p = await import('./ristorante.js'); const s = await import('./ristorante.scenari.js'); const h = await import('./ristorante.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  noleggio: async () => { const p = await import('./noleggio.js'); const s = await import('./noleggio.scenari.js'); const h = await import('./noleggio.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  scuola_guida: async () => { const p = await import('./scuola_guida.js'); const s = await import('./scuola_guida.scenari.js'); const h = await import('./scuola_guida.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
  centro_corsi: async () => { const p = await import('./centro_corsi.js'); const s = await import('./centro_corsi.scenari.js'); const h = await import('./centro_corsi.holdout.js'); return { ...p, scenari: s.scenari, scenariHoldout: h.scenariHoldout || h.scenari }; },
};

export async function caricaDefinizionePack(settore) {
  if (!Object.prototype.hasOwnProperty.call(caricatori, settore)) return null;
  return caricatori[settore]();
}
