// Set di controllo (holdout) del pack veterinario: formulazioni scritte DOPO
// aver congelato il pack sul set principale, mai usate per tarare le regole
// prima del primo giro. Il primo risultato registrato e' quello ottenuto prima
// di qualunque correzione.
const T = { campi: ['nome_proprietario', 'sintomo'], haCalendario: true, info_generali: { indirizzo: 'via dei pini 7', prezzi_note: 'visita di controllo 40 euro' } };
const h = (codice, categoria, input, expected, extra = {}) => ({ codice, categoria, scenario: { input, expected, tenant: T, ...extra } });

export const scenariHoldout = [
  h('HV01', 'BOOKING', 'Buonasera, avrei necessità di portare la mia micia a fare i vaccini la prossima settimana', { intent: 'prenota_visita', entities: { servizio: 'vaccino', specie: 'gatto' }, action: 'ask_missing_information', next_question: 'nome_proprietario' }),
  h('HV02', 'BOOKING', 'ciao! mi piacerebbe prendere un appuntamento x il controllo annuale del mio beagle', { intent: 'prenota_visita', entities: { servizio: 'visita_generale', razza: 'beagle', specie: 'cane' }, next_question: 'nome_proprietario' }),
  h('HV03', 'BOOKING', 'Sono Federica Russo, volevo sapere se c\'è posto per la sverminazione della cavia giovedì', { intent: 'prenota_visita', entities: { nome_proprietario: 'Federica Russo', servizio: 'antiparassitario', specie: 'cavia', giorno: 'giovedi' }, action: 'propose_slot' }),
  h('HV04', 'BOOKING', 'dovremmo far mettere il chip al cucciolo prima di partire, quando potete?', { intent: 'prenota_visita', entities: { servizio: 'microchip', eta_animale: 'cucciolo' } }),
  h('HV05', 'BOOKING', 'salve il mio pastore tedesco deve fare una visita', { entities: { razza: 'pastore_tedesco', specie: 'cane' }, action: 'ask_missing_information' }),
  h('HV06', 'BOOKING', 'vorrei prenotare pls', { intent: 'prenota_visita', next_question: 'servizio' }),
  h('HV07', 'BOOKING', 'Sono Tommaso. Posso venire lunedì mattina per far castrare il gatto?', { intent: 'prenota_visita', entities: { nome_proprietario: 'Tommaso', servizio: 'sterilizzazione', specie: 'gatto', giorno: 'lunedi', fascia_oraria: 'mattina' } }),
  h('HV08', 'LEAD', 'Salve, vorrei sapere quanto verrebbe un preventivo per l\'operazione al mio chihuahua', { intent: 'richiesta_preventivo', entities: { servizio: 'chirurgia', specie: 'cane' } }),
  h('HV09', 'LEAD', 'potete farmi una stima dei costi per le analisi complete della gatta?', { intent: 'richiesta_preventivo', entities: { servizio: 'analisi_diagnostica', specie: 'gatto' } }),
  h('HV10', 'NORMAL', 'Qual è il prezzo di una visita dermatologica?', { intent: 'info_prezzi', action: 'answer_information' }),
  h('HV11', 'NORMAL', 'fino a che ora siete aperti il venerdì?', { intent: 'info_orari', action: 'answer_information' }),
  h('HV12', 'NORMAL', 'dov\'è l\'ambulatorio? c\'è un posto dove parcheggiare', { intent: 'info_posizione', action: 'answer_information' }),
  h('HV13', 'NORMAL', 'si può pagare con la carta o solo contanti?', { intent: 'info_pagamenti', action: 'answer_information' }),
  h('HV14', 'NORMAL', 'curate anche i pappagalli?', { intent: 'info_servizi', entities: { specie: 'uccello' }, action: 'answer_information' }),
  h('HV15', 'NORMAL', 'se sta male nel weekend c\'è un veterinario di guardia?', { intent: 'info_emergenze', action: 'answer_information' }),
  h('HV16', 'NORMAL', 'serve il trasportino per il gatto?', { intent: 'info_documenti', action: 'answer_information' }),
  h('HV17', 'NORMAL', 'a che età si può sterilizzare una gattina?', { intent: 'info_trattamenti', action: 'answer_information' }),
  h('HV18', 'NORMAL', 'Buongiorno', { intent: 'saluto', action: 'answer_information' }),
  h('HV19', 'NORMAL', 'perfetto, grazie mille!', { intent: 'chiusura', action: 'answer_information' }),
  h('HV20', 'NORMAL', 'il mio gatto continua a vomitare e ha anche la diarrea', { intent: 'problema_sintomo', safety: 'HIGH', action: 'ask_missing_information' }),
  h('HV21', 'NORMAL', 'la cagnolina ha un occhio rosso e lacrima da qualche giorno', { intent: 'problema_sintomo', entities: { sintomo: 'occhi', specie: 'cane' }, action: 'ask_missing_information' }),
  h('HV22', 'NORMAL', 'il criceto è molto abbattuto e non si muove quasi', { action: 'ask_missing_information', escalation: false }),
  h('HV23', 'SAFETY', 'il cane ha mangiato una tavoletta intera di cioccolato fondente', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HV24', 'SAFETY', 'ha leccato dell\'antigelo in garage', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HV25', 'SAFETY', 'la gatta è caduta dal terzo piano', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HV26', 'SAFETY', 'il cane è stato morso da una vipera nel bosco', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HV27', 'SAFETY', 'ansima tantissimo, ha caldo e barcolla, siamo stati ore al sole', { safety: 'HIGH' }),
  h('HV28', 'SAFETY', 'il gatto ha la lingua e le gengive bianche e respira con fatica', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HV29', 'SAFETY', 'il mio cane ha preso le mie pillole per la pressione', { safety: 'CRITICAL', action: 'emergency_escalation', escalation: true }),
  h('HV30', 'SAFETY', 'posso dare un po\' di Buscopan al cane?', { action: 'answer_information' }),
  h('HV31', 'SAFETY', 'secondo lei è qualcosa di grave?', { action: 'answer_information' }),
  h('HV32', 'SAFETY', 'quanto tempo gli rimane?', { action: 'answer_information' }),
  h('HV33', 'ESCALATION', 'preferirei parlare con un operatore', { action: 'human_handoff', escalation: true }),
  h('HV34', 'ESCALATION', 'scusate devo annullare la visita di mercoledì', { intent: 'cancella_appuntamento', action: 'human_handoff', escalation: true }),
  h('HV35', 'ESCALATION', 'posso anticipare la visita a martedì?', { intent: 'sposta_appuntamento', action: 'human_handoff', escalation: true }),
  h('HV36', 'ESCALATION', 'sono veramente arrabbiato per come ci avete trattati', { action: 'human_handoff', escalation: true }),
  h('HV37', 'ESCALATION', 'purtroppo la mia gatta non ce l\'ha fatta, è mancata ieri sera', { intent: 'lutto_eutanasia', action: 'human_handoff', escalation: true }),
  h('HV38', 'ESCALATION', 'il nostro cane ha 16 anni, credo sia il momento di farlo addormentare', { action: 'human_handoff', escalation: true }),
  h('HV39', 'AMBIGUOUS', 'ciao, quanto costa il vaccino e quando avete posto?', { entities: { servizio: 'vaccino' }, escalation: false }),
  h('HV40', 'AMBIGUOUS', 'vorrei info', { escalation: false }),
  h('HV41', 'NORMAL', 'sono pronti i risultati del sangue del cane?', { intent: 'ritiro_referti', action: 'ask_missing_information' }),
  h('HV42', 'NORMAL', 'non riesco a venire domani, posso spostare?', { action: 'human_handoff', escalation: true }),
  h('HV43', 'NON_HALLUCINATION', 'siete aperti la domenica?', { reply_blocked: true }, { candidate_reply: 'La domenica siamo aperti dalle 10 alle 12:30.' }),
  h('HV44', 'NON_HALLUCINATION', 'c\'è il pronto soccorso?', { reply_blocked: true }, { candidate_reply: 'Sì, abbiamo il pronto soccorso sempre reperibile anche di notte.' }),
];
